// Code generated by protoc-gen-go. DO NOT EDIT.
// source: application.proto

package geiqin_srv_mts

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 应用信息
type Application struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Slug                 string   `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
	ShortName            string   `protobuf:"bytes,4,opt,name=short_name,json=shortName,proto3" json:"short_name"`
	Type                 string   `protobuf:"bytes,5,opt,name=type,proto3" json:"type"`
	Icon                 string   `protobuf:"bytes,6,opt,name=icon,proto3" json:"icon"`
	CssClass             string   `protobuf:"bytes,7,opt,name=css_class,json=cssClass,proto3" json:"css_class"`
	Url                  string   `protobuf:"bytes,8,opt,name=url,proto3" json:"url"`
	Desc                 string   `protobuf:"bytes,9,opt,name=desc,proto3" json:"desc"`
	Intro                string   `protobuf:"bytes,10,opt,name=intro,proto3" json:"intro"`
	Released             bool     `protobuf:"varint,11,opt,name=released,proto3" json:"released"`
	Disabled             bool     `protobuf:"varint,12,opt,name=disabled,proto3" json:"disabled"`
	CreatedAt            string   `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt            string   `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Application) Reset()         { *m = Application{} }
func (m *Application) String() string { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()    {}
func (*Application) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc846aced8fe6ea6, []int{0}
}

func (m *Application) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Application.Unmarshal(m, b)
}
func (m *Application) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Application.Marshal(b, m, deterministic)
}
func (m *Application) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Application.Merge(m, src)
}
func (m *Application) XXX_Size() int {
	return xxx_messageInfo_Application.Size(m)
}
func (m *Application) XXX_DiscardUnknown() {
	xxx_messageInfo_Application.DiscardUnknown(m)
}

var xxx_messageInfo_Application proto.InternalMessageInfo

func (m *Application) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Application) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Application) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Application) GetShortName() string {
	if m != nil {
		return m.ShortName
	}
	return ""
}

func (m *Application) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Application) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *Application) GetCssClass() string {
	if m != nil {
		return m.CssClass
	}
	return ""
}

func (m *Application) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Application) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Application) GetIntro() string {
	if m != nil {
		return m.Intro
	}
	return ""
}

func (m *Application) GetReleased() bool {
	if m != nil {
		return m.Released
	}
	return false
}

func (m *Application) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *Application) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Application) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

//
type ApplicationResponse struct {
	Entity               *Application   `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity"`
	Pager                *Pager         `protobuf:"bytes,2,opt,name=pager,proto3" json:"pager"`
	Items                []*Application `protobuf:"bytes,3,rep,name=items,proto3" json:"items"`
	Error                *Error         `protobuf:"bytes,4,opt,name=error,proto3" json:"error"`
	Info                 *Info          `protobuf:"bytes,5,opt,name=info,proto3" json:"info"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ApplicationResponse) Reset()         { *m = ApplicationResponse{} }
func (m *ApplicationResponse) String() string { return proto.CompactTextString(m) }
func (*ApplicationResponse) ProtoMessage()    {}
func (*ApplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc846aced8fe6ea6, []int{1}
}

func (m *ApplicationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationResponse.Unmarshal(m, b)
}
func (m *ApplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationResponse.Marshal(b, m, deterministic)
}
func (m *ApplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationResponse.Merge(m, src)
}
func (m *ApplicationResponse) XXX_Size() int {
	return xxx_messageInfo_ApplicationResponse.Size(m)
}
func (m *ApplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationResponse proto.InternalMessageInfo

func (m *ApplicationResponse) GetEntity() *Application {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *ApplicationResponse) GetPager() *Pager {
	if m != nil {
		return m.Pager
	}
	return nil
}

func (m *ApplicationResponse) GetItems() []*Application {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ApplicationResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ApplicationResponse) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*Application)(nil), "geiqin.srv.mts.Application")
	proto.RegisterType((*ApplicationResponse)(nil), "geiqin.srv.mts.ApplicationResponse")
}

func init() { proto.RegisterFile("application.proto", fileDescriptor_fc846aced8fe6ea6) }

var fileDescriptor_fc846aced8fe6ea6 = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xd1, 0x8a, 0x13, 0x31,
	0x14, 0x86, 0x9d, 0x99, 0x4e, 0x6d, 0xcf, 0xac, 0x45, 0x8f, 0x2b, 0xc4, 0x2e, 0x42, 0xa9, 0x37,
	0x05, 0x61, 0xc0, 0xee, 0x13, 0x54, 0x11, 0x59, 0x2f, 0x44, 0x66, 0x2f, 0xbc, 0x2c, 0xd9, 0xcc,
	0xd9, 0x36, 0x30, 0x93, 0x8c, 0x49, 0xba, 0xb0, 0x97, 0x3e, 0x8f, 0x8f, 0xe4, 0xcb, 0x48, 0x92,
	0xa9, 0xd6, 0x22, 0x75, 0xef, 0xfe, 0xf3, 0x7f, 0xff, 0x39, 0x93, 0xe4, 0x30, 0xf0, 0x8c, 0x77,
	0x5d, 0x23, 0x05, 0x77, 0x52, 0xab, 0xb2, 0x33, 0xda, 0x69, 0x9c, 0x6c, 0x48, 0x7e, 0x93, 0xaa,
	0xb4, 0xe6, 0xae, 0x6c, 0x9d, 0x9d, 0x9e, 0x09, 0xdd, 0xb6, 0x7b, 0x3a, 0xff, 0x99, 0x42, 0xb1,
	0xfa, 0xd3, 0x83, 0x13, 0x48, 0x65, 0xcd, 0x92, 0x59, 0xb2, 0xc8, 0xab, 0x54, 0xd6, 0x88, 0x30,
	0xb0, 0xcd, 0x6e, 0xc3, 0xd2, 0x59, 0xb2, 0x18, 0x57, 0x41, 0x7b, 0x4f, 0xf1, 0x96, 0x58, 0x16,
	0x3d, 0xaf, 0xf1, 0x15, 0x80, 0xdd, 0x6a, 0xe3, 0xd6, 0x81, 0x0c, 0x02, 0x19, 0x07, 0xe7, 0xb3,
	0xc7, 0x08, 0x03, 0x77, 0xdf, 0x11, 0xcb, 0x63, 0x8b, 0xd7, 0xde, 0x93, 0x42, 0x2b, 0x36, 0x8c,
	0x9e, 0xd7, 0x78, 0x01, 0x63, 0x61, 0xed, 0x5a, 0x34, 0xdc, 0x5a, 0xf6, 0x38, 0x80, 0x91, 0xb0,
	0xf6, 0xbd, 0xaf, 0xf1, 0x29, 0x64, 0x3b, 0xd3, 0xb0, 0x51, 0xb0, 0xbd, 0xf4, 0x23, 0x6a, 0xb2,
	0x82, 0x8d, 0xe3, 0x08, 0xaf, 0xf1, 0x1c, 0x72, 0xa9, 0x9c, 0xd1, 0x0c, 0x82, 0x19, 0x0b, 0x9c,
	0xc2, 0xc8, 0x50, 0x43, 0xdc, 0x52, 0xcd, 0x8a, 0x59, 0xb2, 0x18, 0x55, 0xbf, 0x6b, 0xcf, 0x6a,
	0x69, 0xf9, 0x4d, 0x43, 0x35, 0x3b, 0x8b, 0x6c, 0x5f, 0xfb, 0x7b, 0x09, 0x43, 0xdc, 0x51, 0xbd,
	0xe6, 0x8e, 0x3d, 0x89, 0xf7, 0xea, 0x9d, 0x95, 0xf3, 0x78, 0xd7, 0xd5, 0x7b, 0x3c, 0x89, 0xb8,
	0x77, 0x56, 0x6e, 0xfe, 0x3d, 0x85, 0xe7, 0x07, 0xaf, 0x5b, 0x91, 0xed, 0xb4, 0xb2, 0x84, 0x97,
	0x30, 0x24, 0xe5, 0xa4, 0xbb, 0x0f, 0x2f, 0x5d, 0x2c, 0x2f, 0xca, 0xbf, 0x97, 0x54, 0x1e, 0x36,
	0xf5, 0x51, 0x7c, 0x03, 0x79, 0xc7, 0x37, 0x64, 0xc2, 0x2e, 0x8a, 0xe5, 0x8b, 0xe3, 0x9e, 0x2f,
	0x1e, 0x56, 0x31, 0x83, 0x6f, 0x21, 0x97, 0x8e, 0x5a, 0xcb, 0xb2, 0x59, 0xf6, 0xbf, 0x0f, 0xc4,
	0xa4, 0x9f, 0x4f, 0xc6, 0x68, 0x13, 0xb6, 0xf7, 0x8f, 0xf9, 0x1f, 0x3c, 0xac, 0x62, 0x06, 0x17,
	0x30, 0x90, 0xea, 0x56, 0x87, 0x85, 0x16, 0xcb, 0xf3, 0xe3, 0xec, 0x95, 0xba, 0xd5, 0x55, 0x48,
	0x2c, 0x7f, 0x24, 0x80, 0x07, 0x5f, 0xbb, 0x26, 0x73, 0x27, 0x05, 0xe1, 0x15, 0x64, 0x1f, 0xc9,
	0xe1, 0xa9, 0x83, 0x4d, 0x5f, 0x9f, 0x3a, 0x75, 0xff, 0x96, 0xf3, 0x47, 0xf8, 0x09, 0x86, 0xd7,
	0xc4, 0x8d, 0xd8, 0xe2, 0xcb, 0xe3, 0x86, 0x77, 0xdc, 0xd2, 0xd7, 0x2d, 0x19, 0x7a, 0xe0, 0xac,
	0x9b, 0x61, 0xf8, 0x2d, 0x2e, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x25, 0xf1, 0x2c, 0x02, 0x49,
	0x03, 0x00, 0x00,
}
