// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payMethod.proto

package geiqin_srv_mts

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PayMethod struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Icon                 string   `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Memo                 string   `protobuf:"bytes,5,opt,name=memo,proto3" json:"memo,omitempty"`
	Supports             string   `protobuf:"bytes,6,opt,name=supports,proto3" json:"supports,omitempty"`
	Disabled             bool     `protobuf:"varint,7,opt,name=disabled,proto3" json:"disabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayMethod) Reset()         { *m = PayMethod{} }
func (m *PayMethod) String() string { return proto.CompactTextString(m) }
func (*PayMethod) ProtoMessage()    {}
func (*PayMethod) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba62b9ad5962a380, []int{0}
}

func (m *PayMethod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayMethod.Unmarshal(m, b)
}
func (m *PayMethod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayMethod.Marshal(b, m, deterministic)
}
func (m *PayMethod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayMethod.Merge(m, src)
}
func (m *PayMethod) XXX_Size() int {
	return xxx_messageInfo_PayMethod.Size(m)
}
func (m *PayMethod) XXX_DiscardUnknown() {
	xxx_messageInfo_PayMethod.DiscardUnknown(m)
}

var xxx_messageInfo_PayMethod proto.InternalMessageInfo

func (m *PayMethod) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PayMethod) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PayMethod) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PayMethod) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *PayMethod) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *PayMethod) GetSupports() string {
	if m != nil {
		return m.Supports
	}
	return ""
}

func (m *PayMethod) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

type PayMethodWhere struct {
	Paged                int32    `protobuf:"varint,1,opt,name=paged,proto3" json:"paged,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Sorting              string   `protobuf:"bytes,3,opt,name=sorting,proto3" json:"sorting,omitempty"`
	Id                   int64    `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Title                string   `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	StoreId              int64    `protobuf:"varint,7,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Channel              string   `protobuf:"bytes,8,opt,name=channel,proto3" json:"channel,omitempty"`
	Status               int64    `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayMethodWhere) Reset()         { *m = PayMethodWhere{} }
func (m *PayMethodWhere) String() string { return proto.CompactTextString(m) }
func (*PayMethodWhere) ProtoMessage()    {}
func (*PayMethodWhere) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba62b9ad5962a380, []int{1}
}

func (m *PayMethodWhere) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayMethodWhere.Unmarshal(m, b)
}
func (m *PayMethodWhere) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayMethodWhere.Marshal(b, m, deterministic)
}
func (m *PayMethodWhere) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayMethodWhere.Merge(m, src)
}
func (m *PayMethodWhere) XXX_Size() int {
	return xxx_messageInfo_PayMethodWhere.Size(m)
}
func (m *PayMethodWhere) XXX_DiscardUnknown() {
	xxx_messageInfo_PayMethodWhere.DiscardUnknown(m)
}

var xxx_messageInfo_PayMethodWhere proto.InternalMessageInfo

func (m *PayMethodWhere) GetPaged() int32 {
	if m != nil {
		return m.Paged
	}
	return 0
}

func (m *PayMethodWhere) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PayMethodWhere) GetSorting() string {
	if m != nil {
		return m.Sorting
	}
	return ""
}

func (m *PayMethodWhere) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PayMethodWhere) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PayMethodWhere) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PayMethodWhere) GetStoreId() int64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *PayMethodWhere) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *PayMethodWhere) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

//
type PayMethodResponse struct {
	Entity               *PayMethod   `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Pager                *Pager       `protobuf:"bytes,2,opt,name=pager,proto3" json:"pager,omitempty"`
	Items                []*PayMethod `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Error                *Error       `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Info                 *Info        `protobuf:"bytes,5,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PayMethodResponse) Reset()         { *m = PayMethodResponse{} }
func (m *PayMethodResponse) String() string { return proto.CompactTextString(m) }
func (*PayMethodResponse) ProtoMessage()    {}
func (*PayMethodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba62b9ad5962a380, []int{2}
}

func (m *PayMethodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayMethodResponse.Unmarshal(m, b)
}
func (m *PayMethodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayMethodResponse.Marshal(b, m, deterministic)
}
func (m *PayMethodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayMethodResponse.Merge(m, src)
}
func (m *PayMethodResponse) XXX_Size() int {
	return xxx_messageInfo_PayMethodResponse.Size(m)
}
func (m *PayMethodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PayMethodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PayMethodResponse proto.InternalMessageInfo

func (m *PayMethodResponse) GetEntity() *PayMethod {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *PayMethodResponse) GetPager() *Pager {
	if m != nil {
		return m.Pager
	}
	return nil
}

func (m *PayMethodResponse) GetItems() []*PayMethod {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *PayMethodResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *PayMethodResponse) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*PayMethod)(nil), "geiqin.srv.mts.PayMethod")
	proto.RegisterType((*PayMethodWhere)(nil), "geiqin.srv.mts.PayMethodWhere")
	proto.RegisterType((*PayMethodResponse)(nil), "geiqin.srv.mts.PayMethodResponse")
}

func init() {
	proto.RegisterFile("payMethod.proto", fileDescriptor_ba62b9ad5962a380)
}

var fileDescriptor_ba62b9ad5962a380 = []byte{
	// 465 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xdd, 0x6e, 0x13, 0x3d,
	0x10, 0xfd, 0x36, 0xfb, 0x93, 0xcd, 0xe4, 0x53, 0x80, 0x51, 0x41, 0x6e, 0x90, 0x50, 0xc8, 0x55,
	0x24, 0xa4, 0x45, 0x84, 0x67, 0x28, 0x50, 0xd1, 0x4a, 0xc8, 0x11, 0xe2, 0xb2, 0xda, 0xee, 0x4e,
	0x13, 0x8b, 0xac, 0xbd, 0xd8, 0x6e, 0xa5, 0xf6, 0x05, 0x78, 0x12, 0xde, 0x8c, 0xb7, 0xe0, 0x06,
	0xd9, 0xde, 0x2e, 0x3f, 0x6d, 0x10, 0x12, 0xbd, 0x9b, 0x33, 0x3e, 0x73, 0x7c, 0xce, 0xac, 0xb5,
	0x70, 0xaf, 0x2d, 0x2f, 0x8f, 0xc9, 0x6e, 0x54, 0x5d, 0xb4, 0x5a, 0x59, 0x85, 0x93, 0x35, 0x89,
	0x4f, 0x42, 0x16, 0x46, 0x5f, 0x14, 0x8d, 0x35, 0xd3, 0xff, 0x2b, 0xd5, 0x34, 0x4a, 0x86, 0xd3,
	0xf9, 0x97, 0x08, 0x46, 0xef, 0xae, 0x27, 0x70, 0x02, 0x03, 0x51, 0xb3, 0x68, 0x16, 0x2d, 0x62,
	0x3e, 0x10, 0x35, 0x22, 0x24, 0xb2, 0x6c, 0x88, 0x0d, 0x66, 0xd1, 0x62, 0xc4, 0x7d, 0x8d, 0x7b,
	0x90, 0x5a, 0x61, 0xb7, 0xc4, 0x62, 0xdf, 0x0c, 0xc0, 0x31, 0x45, 0xa5, 0x24, 0x4b, 0x02, 0xd3,
	0xd5, 0xae, 0xd7, 0x50, 0xa3, 0x58, 0x1a, 0x7a, 0xae, 0xc6, 0x29, 0xe4, 0xe6, 0xbc, 0x6d, 0x95,
	0xb6, 0x86, 0x65, 0xbe, 0xdf, 0x63, 0x77, 0x56, 0x0b, 0x53, 0x9e, 0x6e, 0xa9, 0x66, 0xc3, 0x59,
	0xb4, 0xc8, 0x79, 0x8f, 0xe7, 0x5f, 0x23, 0x98, 0xf4, 0x3e, 0x3f, 0x6c, 0x48, 0x7b, 0x23, 0x6d,
	0xb9, 0xa6, 0xe0, 0x37, 0xe5, 0x01, 0xe0, 0x63, 0x18, 0xb9, 0xe2, 0xc4, 0x88, 0xab, 0xe0, 0x3b,
	0xe5, 0xb9, 0x6b, 0xac, 0xc4, 0x15, 0x21, 0x83, 0xa1, 0x51, 0xda, 0x0a, 0xb9, 0xee, 0xdc, 0x5f,
	0xc3, 0x2e, 0x79, 0x72, 0x23, 0x79, 0x7a, 0x5b, 0xf2, 0xec, 0xe7, 0xe4, 0xfb, 0x90, 0x1b, 0xab,
	0x34, 0x9d, 0x88, 0xe0, 0x3a, 0xe6, 0x43, 0x8f, 0x0f, 0x6b, 0x77, 0x5d, 0xb5, 0x29, 0xa5, 0xa4,
	0x2d, 0xcb, 0xc3, 0x75, 0x1d, 0xc4, 0x47, 0x90, 0x19, 0x5b, 0xda, 0x73, 0xc3, 0x46, 0x7e, 0xa4,
	0x43, 0xf3, 0x6f, 0x11, 0x3c, 0xe8, 0x63, 0x72, 0x32, 0xad, 0x92, 0x86, 0xf0, 0x05, 0x64, 0x24,
	0xad, 0xb0, 0x97, 0x3e, 0xea, 0x78, 0xb9, 0x5f, 0xfc, 0xfa, 0x4d, 0x8b, 0x1f, 0x23, 0x1d, 0x11,
	0x9f, 0x85, 0xe5, 0x68, 0xbf, 0x82, 0xf1, 0xf2, 0xe1, 0xcd, 0x89, 0x35, 0xe9, 0xb0, 0x33, 0x8d,
	0xcf, 0x21, 0x15, 0x96, 0x1a, 0xc3, 0xe2, 0x59, 0xfc, 0x67, 0xf9, 0xc0, 0x73, 0xea, 0xa4, 0xb5,
	0xd2, 0x7e, 0x61, 0xb7, 0xa8, 0x1f, 0xb8, 0x43, 0x1e, 0x38, 0xb8, 0x80, 0x44, 0xc8, 0xb3, 0xf0,
	0x0c, 0xc6, 0xcb, 0xbd, 0xdf, 0xb9, 0x87, 0xf2, 0x4c, 0x71, 0xcf, 0x58, 0x7e, 0x8e, 0xe1, 0x7e,
	0x7f, 0xd7, 0x8a, 0xf4, 0x85, 0xa8, 0x08, 0x5f, 0x41, 0x72, 0xa4, 0xaa, 0x8f, 0xb8, 0xdb, 0xd5,
	0xf4, 0xe9, 0x6e, 0xc3, 0xdd, 0x0a, 0xe7, 0xff, 0xe1, 0x1b, 0xc8, 0xde, 0xcb, 0xed, 0x5d, 0x28,
	0x1d, 0x40, 0xfc, 0x9a, 0xec, 0x3f, 0xcb, 0xbc, 0x85, 0xe4, 0x48, 0x18, 0x8b, 0x4f, 0x76, 0x92,
	0xfd, 0x3b, 0xff, 0x3b, 0xb1, 0x63, 0xc8, 0x56, 0x54, 0xea, 0x6a, 0x73, 0x27, 0x72, 0xa7, 0x99,
	0xff, 0x3b, 0xbc, 0xfc, 0x1e, 0x00, 0x00, 0xff, 0xff, 0x2d, 0x2a, 0xd1, 0xb5, 0x4e, 0x04, 0x00,
	0x00,
}
