// Code generated by protoc-gen-go. DO NOT EDIT.
// source: limitDiscount.proto

package geiqin_srv_ims_discount

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LimitDiscount struct {
	Id                   int64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StartAt              string                `protobuf:"bytes,3,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt                string                `protobuf:"bytes,4,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	PeriodType           int32                 `protobuf:"varint,5,opt,name=period_type,json=periodType,proto3" json:"period_type,omitempty"`
	PeriodStartTime      string                `protobuf:"bytes,6,opt,name=period_start_time,json=periodStartTime,proto3" json:"period_start_time,omitempty"`
	PeriodEndTime        string                `protobuf:"bytes,7,opt,name=period_end_time,json=periodEndTime,proto3" json:"period_end_time,omitempty"`
	PeriodDays           string                `protobuf:"bytes,8,opt,name=period_days,json=periodDays,proto3" json:"period_days,omitempty"`
	LimitType            int32                 `protobuf:"varint,9,opt,name=limit_type,json=limitType,proto3" json:"limit_type,omitempty"`
	LimitNum             int32                 `protobuf:"varint,10,opt,name=limit_num,json=limitNum,proto3" json:"limit_num,omitempty"`
	Lable                string                `protobuf:"bytes,11,opt,name=lable,proto3" json:"lable,omitempty"`
	Erased               int32                 `protobuf:"varint,12,opt,name=erased,proto3" json:"erased,omitempty"`
	Status               int32                 `protobuf:"varint,13,opt,name=Status,proto3" json:"Status,omitempty"`
	CreatedAt            string                `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string                `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Goodses              []*LimitDiscountGoods `protobuf:"bytes,16,rep,name=goodses,proto3" json:"goodses,omitempty"`
	Ids                  []int64               `protobuf:"varint,17,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *LimitDiscount) Reset()         { *m = LimitDiscount{} }
func (m *LimitDiscount) String() string { return proto.CompactTextString(m) }
func (*LimitDiscount) ProtoMessage()    {}
func (*LimitDiscount) Descriptor() ([]byte, []int) {
	return fileDescriptor_3163fe83b6bcf4d5, []int{0}
}

func (m *LimitDiscount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LimitDiscount.Unmarshal(m, b)
}
func (m *LimitDiscount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LimitDiscount.Marshal(b, m, deterministic)
}
func (m *LimitDiscount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LimitDiscount.Merge(m, src)
}
func (m *LimitDiscount) XXX_Size() int {
	return xxx_messageInfo_LimitDiscount.Size(m)
}
func (m *LimitDiscount) XXX_DiscardUnknown() {
	xxx_messageInfo_LimitDiscount.DiscardUnknown(m)
}

var xxx_messageInfo_LimitDiscount proto.InternalMessageInfo

func (m *LimitDiscount) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LimitDiscount) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LimitDiscount) GetStartAt() string {
	if m != nil {
		return m.StartAt
	}
	return ""
}

func (m *LimitDiscount) GetEndAt() string {
	if m != nil {
		return m.EndAt
	}
	return ""
}

func (m *LimitDiscount) GetPeriodType() int32 {
	if m != nil {
		return m.PeriodType
	}
	return 0
}

func (m *LimitDiscount) GetPeriodStartTime() string {
	if m != nil {
		return m.PeriodStartTime
	}
	return ""
}

func (m *LimitDiscount) GetPeriodEndTime() string {
	if m != nil {
		return m.PeriodEndTime
	}
	return ""
}

func (m *LimitDiscount) GetPeriodDays() string {
	if m != nil {
		return m.PeriodDays
	}
	return ""
}

func (m *LimitDiscount) GetLimitType() int32 {
	if m != nil {
		return m.LimitType
	}
	return 0
}

func (m *LimitDiscount) GetLimitNum() int32 {
	if m != nil {
		return m.LimitNum
	}
	return 0
}

func (m *LimitDiscount) GetLable() string {
	if m != nil {
		return m.Lable
	}
	return ""
}

func (m *LimitDiscount) GetErased() int32 {
	if m != nil {
		return m.Erased
	}
	return 0
}

func (m *LimitDiscount) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *LimitDiscount) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *LimitDiscount) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *LimitDiscount) GetGoodses() []*LimitDiscountGoods {
	if m != nil {
		return m.Goodses
	}
	return nil
}

func (m *LimitDiscount) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

//
type LimitDiscountResponse struct {
	Entity               *LimitDiscount   `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Pager                *Pager           `protobuf:"bytes,2,opt,name=pager,proto3" json:"pager,omitempty"`
	Items                []*LimitDiscount `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Error                *Error           `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Info                 *Info            `protobuf:"bytes,5,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LimitDiscountResponse) Reset()         { *m = LimitDiscountResponse{} }
func (m *LimitDiscountResponse) String() string { return proto.CompactTextString(m) }
func (*LimitDiscountResponse) ProtoMessage()    {}
func (*LimitDiscountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3163fe83b6bcf4d5, []int{1}
}

func (m *LimitDiscountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LimitDiscountResponse.Unmarshal(m, b)
}
func (m *LimitDiscountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LimitDiscountResponse.Marshal(b, m, deterministic)
}
func (m *LimitDiscountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LimitDiscountResponse.Merge(m, src)
}
func (m *LimitDiscountResponse) XXX_Size() int {
	return xxx_messageInfo_LimitDiscountResponse.Size(m)
}
func (m *LimitDiscountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LimitDiscountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LimitDiscountResponse proto.InternalMessageInfo

func (m *LimitDiscountResponse) GetEntity() *LimitDiscount {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *LimitDiscountResponse) GetPager() *Pager {
	if m != nil {
		return m.Pager
	}
	return nil
}

func (m *LimitDiscountResponse) GetItems() []*LimitDiscount {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *LimitDiscountResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *LimitDiscountResponse) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*LimitDiscount)(nil), "geiqin.srv.ims.discount.LimitDiscount")
	proto.RegisterType((*LimitDiscountResponse)(nil), "geiqin.srv.ims.discount.LimitDiscountResponse")
}

func init() { proto.RegisterFile("limitDiscount.proto", fileDescriptor_3163fe83b6bcf4d5) }

var fileDescriptor_3163fe83b6bcf4d5 = []byte{
	// 569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xdd, 0x6a, 0x13, 0x4f,
	0x14, 0xff, 0x27, 0x9b, 0x4d, 0x9b, 0x93, 0x7e, 0xce, 0xbf, 0xd5, 0xb1, 0x52, 0x0d, 0xb9, 0x28,
	0x41, 0x61, 0xc1, 0xe8, 0xa5, 0x08, 0xb1, 0x2d, 0x45, 0x28, 0x22, 0x9b, 0x8a, 0x37, 0x62, 0x98,
	0xee, 0x9c, 0xb6, 0x03, 0xd9, 0x99, 0x75, 0x66, 0x52, 0xc8, 0x7b, 0xf8, 0x28, 0xbe, 0x82, 0xef,
	0x25, 0x73, 0x66, 0x8b, 0x16, 0x89, 0x04, 0x21, 0x77, 0x7b, 0x7e, 0x1f, 0xe7, 0x77, 0x66, 0xe6,
	0xc0, 0xc2, 0xff, 0x53, 0x55, 0x2a, 0x7f, 0xa2, 0x5c, 0x61, 0x66, 0xda, 0x67, 0x95, 0x35, 0xde,
	0xb0, 0x87, 0xd7, 0xa8, 0xbe, 0x2a, 0x9d, 0x39, 0x7b, 0x9b, 0xa9, 0xd2, 0x65, 0xb2, 0xa6, 0x0f,
	0x36, 0x0a, 0x53, 0x96, 0x46, 0x47, 0xd9, 0x01, 0xbf, 0xe7, 0x3d, 0x33, 0x46, 0xba, 0xc8, 0xf4,
	0xbf, 0xb5, 0x60, 0xf3, 0xfc, 0x77, 0x92, 0x6d, 0x41, 0x53, 0x49, 0xde, 0xe8, 0x35, 0x06, 0x49,
	0xde, 0x54, 0x92, 0x31, 0x68, 0x69, 0x51, 0x22, 0x6f, 0xf6, 0x1a, 0x83, 0x4e, 0x4e, 0xdf, 0xec,
	0x11, 0xac, 0x3b, 0x2f, 0xac, 0x9f, 0x08, 0xcf, 0x13, 0xc2, 0xd7, 0xa8, 0x1e, 0x79, 0xb6, 0x0f,
	0x6d, 0xd4, 0x32, 0x10, 0x2d, 0x22, 0x52, 0xd4, 0x72, 0xe4, 0xd9, 0x53, 0xe8, 0x56, 0x68, 0x95,
	0x91, 0x13, 0x3f, 0xaf, 0x90, 0xa7, 0xbd, 0xc6, 0x20, 0xcd, 0x21, 0x42, 0x17, 0xf3, 0x0a, 0xd9,
	0x33, 0xd8, 0xad, 0x05, 0xb1, 0xb3, 0x57, 0x25, 0xf2, 0x36, 0xb5, 0xd8, 0x8e, 0xc4, 0x38, 0xe0,
	0x17, 0xaa, 0x44, 0x76, 0x04, 0x35, 0x34, 0x09, 0x51, 0xa4, 0x5c, 0x23, 0xe5, 0x66, 0x84, 0x4f,
	0xb5, 0x24, 0xdd, 0xaf, 0x50, 0x29, 0xe6, 0x8e, 0xaf, 0x93, 0xa6, 0x0e, 0x3d, 0x11, 0x73, 0xc7,
	0x0e, 0x01, 0xe8, 0x66, 0xe2, 0x50, 0x1d, 0x1a, 0xaa, 0x43, 0x08, 0xcd, 0xf4, 0x18, 0x62, 0x31,
	0xd1, 0xb3, 0x92, 0x03, 0xb1, 0xeb, 0x04, 0xbc, 0x9f, 0x95, 0x6c, 0x0f, 0xd2, 0xa9, 0xb8, 0x9c,
	0x22, 0xef, 0xc6, 0x73, 0x52, 0xc1, 0x1e, 0x40, 0x1b, 0xad, 0x70, 0x28, 0xf9, 0x06, 0xe9, 0xeb,
	0x2a, 0xe0, 0x63, 0x2f, 0xfc, 0xcc, 0xf1, 0xcd, 0x88, 0xc7, 0x2a, 0x4c, 0x50, 0x58, 0x14, 0x1e,
	0xe9, 0xca, 0xb6, 0xa8, 0x55, 0xa7, 0x46, 0x46, 0x3e, 0xd0, 0xb3, 0x4a, 0xde, 0xd1, 0xdb, 0x91,
	0xae, 0x91, 0x91, 0x67, 0xa7, 0xb0, 0x76, 0x1d, 0x1e, 0x13, 0x1d, 0xdf, 0xe9, 0x25, 0x83, 0xee,
	0xf0, 0x79, 0xb6, 0x60, 0x21, 0xb2, 0xf3, 0x3f, 0x36, 0x20, 0xbf, 0xf3, 0xb2, 0x1d, 0x48, 0x94,
	0x74, 0x7c, 0xb7, 0x97, 0x0c, 0x92, 0x3c, 0x7c, 0xf6, 0xbf, 0x37, 0x61, 0xff, 0x9e, 0x23, 0x47,
	0x57, 0x19, 0xed, 0x90, 0xbd, 0x09, 0xef, 0xeb, 0x95, 0x9f, 0xd3, 0x8a, 0x74, 0x87, 0x47, 0xcb,
	0x25, 0xe6, 0xb5, 0x8b, 0xbd, 0x82, 0xb4, 0x12, 0xd7, 0x68, 0x69, 0x9f, 0xba, 0xc3, 0x27, 0x0b,
	0xed, 0x1f, 0x82, 0x2a, 0x8f, 0x62, 0xf6, 0x1a, 0x52, 0xe5, 0xb1, 0x74, 0x3c, 0xa1, 0x63, 0x2e,
	0x1b, 0x1a, 0x4d, 0x21, 0x13, 0xad, 0x35, 0x96, 0x56, 0xf2, 0x6f, 0x99, 0xa7, 0x41, 0x95, 0x47,
	0x31, 0x7b, 0x01, 0x2d, 0xa5, 0xaf, 0x0c, 0xed, 0x6a, 0x77, 0x78, 0xb8, 0xd0, 0xf4, 0x4e, 0x5f,
	0x99, 0x9c, 0xa4, 0xc3, 0x1f, 0x29, 0xec, 0xdd, 0x9b, 0x60, 0x8c, 0xf6, 0x56, 0x15, 0xc8, 0x2e,
	0xa1, 0x7d, 0x4c, 0x8f, 0xca, 0x96, 0x1c, 0xfd, 0x20, 0x5b, 0xf2, 0x88, 0xf5, 0xbb, 0xf4, 0xff,
	0x0b, 0x19, 0x1f, 0x69, 0x33, 0x56, 0x9b, 0x71, 0x82, 0x53, 0x5c, 0x75, 0xc6, 0xb1, 0xd0, 0x05,
	0x4e, 0x57, 0x98, 0x31, 0x81, 0xe4, 0x0c, 0xfd, 0x0a, 0x03, 0xbe, 0x40, 0x7b, 0x8c, 0xc2, 0x16,
	0x37, 0xac, 0xbf, 0xd0, 0xfb, 0x56, 0x38, 0xfc, 0x74, 0x83, 0x16, 0xff, 0xa1, 0xff, 0x67, 0x68,
	0x9d, 0x2b, 0xe7, 0x57, 0xd3, 0xfd, 0xb2, 0x4d, 0x3f, 0x87, 0x97, 0x3f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x33, 0x9b, 0x31, 0x19, 0x74, 0x06, 0x00, 0x00,
}
