// Code generated by protoc-gen-go. DO NOT EDIT.
// source: favorite.proto

//import "proto/item.proto";

package geiqin_srv_pdm

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Favorite struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId           int64    `protobuf:"varint,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	ItemId               int64    `protobuf:"varint,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Favorite) Reset()         { *m = Favorite{} }
func (m *Favorite) String() string { return proto.CompactTextString(m) }
func (*Favorite) ProtoMessage()    {}
func (*Favorite) Descriptor() ([]byte, []int) {
	return fileDescriptor_d331d96d24e0e82b, []int{0}
}

func (m *Favorite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Favorite.Unmarshal(m, b)
}
func (m *Favorite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Favorite.Marshal(b, m, deterministic)
}
func (m *Favorite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Favorite.Merge(m, src)
}
func (m *Favorite) XXX_Size() int {
	return xxx_messageInfo_Favorite.Size(m)
}
func (m *Favorite) XXX_DiscardUnknown() {
	xxx_messageInfo_Favorite.DiscardUnknown(m)
}

var xxx_messageInfo_Favorite proto.InternalMessageInfo

func (m *Favorite) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Favorite) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *Favorite) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *Favorite) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Favorite) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type FavoriteResponse struct {
	Entity               *Favorite   `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Pager                *Pager      `protobuf:"bytes,2,opt,name=pager,proto3" json:"pager,omitempty"`
	Items                []*Favorite `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Error                *Error      `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Info                 *Info       `protobuf:"bytes,5,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FavoriteResponse) Reset()         { *m = FavoriteResponse{} }
func (m *FavoriteResponse) String() string { return proto.CompactTextString(m) }
func (*FavoriteResponse) ProtoMessage()    {}
func (*FavoriteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d331d96d24e0e82b, []int{1}
}

func (m *FavoriteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FavoriteResponse.Unmarshal(m, b)
}
func (m *FavoriteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FavoriteResponse.Marshal(b, m, deterministic)
}
func (m *FavoriteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FavoriteResponse.Merge(m, src)
}
func (m *FavoriteResponse) XXX_Size() int {
	return xxx_messageInfo_FavoriteResponse.Size(m)
}
func (m *FavoriteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FavoriteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FavoriteResponse proto.InternalMessageInfo

func (m *FavoriteResponse) GetEntity() *Favorite {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *FavoriteResponse) GetPager() *Pager {
	if m != nil {
		return m.Pager
	}
	return nil
}

func (m *FavoriteResponse) GetItems() []*Favorite {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *FavoriteResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *FavoriteResponse) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*Favorite)(nil), "geiqin.srv.pdm.Favorite")
	proto.RegisterType((*FavoriteResponse)(nil), "geiqin.srv.pdm.FavoriteResponse")
}

func init() { proto.RegisterFile("favorite.proto", fileDescriptor_d331d96d24e0e82b) }

var fileDescriptor_d331d96d24e0e82b = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x86, 0xbf, 0x24, 0x4d, 0x3e, 0x3b, 0x91, 0x2a, 0x8b, 0x62, 0x2c, 0x88, 0xa1, 0xa7, 0x82,
	0x10, 0x24, 0xfe, 0x82, 0x5a, 0xdb, 0xd2, 0x9b, 0xa4, 0x07, 0x8f, 0x25, 0x66, 0xa7, 0xed, 0xa2,
	0xc9, 0xc6, 0xdd, 0x6d, 0xc1, 0xbf, 0xe1, 0x8f, 0x15, 0x8f, 0xb2, 0x9b, 0x44, 0xb0, 0x58, 0x11,
	0x7a, 0xec, 0x3c, 0xef, 0x3c, 0x7d, 0x67, 0x21, 0xd0, 0x59, 0xa4, 0x1b, 0x2e, 0x98, 0xc2, 0xa8,
	0x14, 0x5c, 0x71, 0xd2, 0x59, 0x22, 0x7b, 0x61, 0x45, 0x24, 0xc5, 0x26, 0x2a, 0x69, 0xde, 0x3d,
	0xcc, 0x78, 0x9e, 0xf3, 0xa2, 0xa2, 0xbd, 0x37, 0x0b, 0x0e, 0xc6, 0xf5, 0x02, 0xe9, 0x80, 0xcd,
	0x68, 0x60, 0x85, 0x56, 0xdf, 0x49, 0x6c, 0x46, 0xc9, 0x25, 0xf8, 0xd9, 0x5a, 0x2a, 0x9e, 0xa3,
	0x98, 0x33, 0x1a, 0xd8, 0x06, 0x40, 0x33, 0x9a, 0x52, 0x72, 0x06, 0xff, 0x99, 0xc2, 0x5c, 0x43,
	0xc7, 0x40, 0x4f, 0xff, 0x9c, 0x52, 0x72, 0x01, 0x90, 0x09, 0x4c, 0x15, 0xd2, 0x79, 0xaa, 0x82,
	0x56, 0x68, 0xf5, 0xdb, 0x49, 0xbb, 0x9e, 0x0c, 0x94, 0xc6, 0xeb, 0x92, 0x36, 0xd8, 0xad, 0x70,
	0x3d, 0x19, 0xa8, 0xde, 0x87, 0x05, 0xc7, 0x4d, 0xa9, 0x04, 0x65, 0xc9, 0x0b, 0x89, 0xe4, 0x1a,
	0x3c, 0x2c, 0x14, 0x53, 0xaf, 0xa6, 0xa0, 0x1f, 0x07, 0xd1, 0xf7, 0xc3, 0xa2, 0xaf, 0x8d, 0x3a,
	0x47, 0xae, 0xc0, 0x2d, 0xd3, 0x25, 0x0a, 0x53, 0xdc, 0x8f, 0x4f, 0xb7, 0x17, 0xee, 0x35, 0x4c,
	0xaa, 0x0c, 0x89, 0xc0, 0xd5, 0xdd, 0x65, 0xe0, 0x84, 0xce, 0xaf, 0xf6, 0x2a, 0xa6, 0xe5, 0x28,
	0x04, 0x17, 0xe6, 0xb8, 0x1f, 0xe4, 0x23, 0x0d, 0x93, 0x2a, 0x43, 0xfa, 0xd0, 0x62, 0xc5, 0x82,
	0x9b, 0x4b, 0xfd, 0xf8, 0x64, 0x3b, 0x3b, 0x2d, 0x16, 0x3c, 0x31, 0x89, 0xf8, 0xdd, 0x86, 0xa3,
	0xe6, 0xaf, 0x66, 0x28, 0x36, 0x2c, 0x43, 0x32, 0x06, 0x6f, 0x68, 0x9e, 0x8e, 0xec, 0x6c, 0xd5,
	0x0d, 0x77, 0xf6, 0xad, 0xdf, 0xaf, 0xf7, 0x4f, 0x7b, 0xee, 0xf0, 0x19, 0xf7, 0xf6, 0x0c, 0xc1,
	0x99, 0xa0, 0xda, 0x53, 0x32, 0x02, 0x77, 0xb8, 0xc2, 0xec, 0x69, 0x4f, 0xcd, 0x04, 0xbc, 0x19,
	0xa6, 0x22, 0x5b, 0x91, 0xf3, 0xed, 0xf4, 0x6d, 0x2a, 0xf1, 0x61, 0x85, 0xe2, 0x4f, 0xa2, 0x47,
	0xcf, 0x7c, 0x0f, 0x37, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x13, 0x7a, 0x52, 0xc5, 0x3f, 0x03,
	0x00, 0x00,
}
