// Code generated by protoc-gen-go. DO NOT EDIT.
// source: itemGallery.proto

package geiqin_srv_pdm

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ItemGallery struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemId               int64    `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	SkuId                int64    `protobuf:"varint,3,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Belong               string   `protobuf:"bytes,4,opt,name=belong,proto3" json:"belong,omitempty"`
	MediaId              int64    `protobuf:"varint,5,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	MediaUrl             string   `protobuf:"bytes,6,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	Defaulted            bool     `protobuf:"varint,7,opt,name=defaulted,proto3" json:"defaulted,omitempty"`
	CreatedAt            string   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemGallery) Reset()         { *m = ItemGallery{} }
func (m *ItemGallery) String() string { return proto.CompactTextString(m) }
func (*ItemGallery) ProtoMessage()    {}
func (*ItemGallery) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aadb10314c1443a, []int{0}
}

func (m *ItemGallery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemGallery.Unmarshal(m, b)
}
func (m *ItemGallery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemGallery.Marshal(b, m, deterministic)
}
func (m *ItemGallery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemGallery.Merge(m, src)
}
func (m *ItemGallery) XXX_Size() int {
	return xxx_messageInfo_ItemGallery.Size(m)
}
func (m *ItemGallery) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemGallery.DiscardUnknown(m)
}

var xxx_messageInfo_ItemGallery proto.InternalMessageInfo

func (m *ItemGallery) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ItemGallery) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *ItemGallery) GetSkuId() int64 {
	if m != nil {
		return m.SkuId
	}
	return 0
}

func (m *ItemGallery) GetBelong() string {
	if m != nil {
		return m.Belong
	}
	return ""
}

func (m *ItemGallery) GetMediaId() int64 {
	if m != nil {
		return m.MediaId
	}
	return 0
}

func (m *ItemGallery) GetMediaUrl() string {
	if m != nil {
		return m.MediaUrl
	}
	return ""
}

func (m *ItemGallery) GetDefaulted() bool {
	if m != nil {
		return m.Defaulted
	}
	return false
}

func (m *ItemGallery) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *ItemGallery) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type ItemGalleryResponse struct {
	Entity               *ItemGallery   `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Pager                *Pager         `protobuf:"bytes,2,opt,name=pager,proto3" json:"pager,omitempty"`
	Items                []*ItemGallery `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Error                *Error         `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Info                 *Info          `protobuf:"bytes,5,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ItemGalleryResponse) Reset()         { *m = ItemGalleryResponse{} }
func (m *ItemGalleryResponse) String() string { return proto.CompactTextString(m) }
func (*ItemGalleryResponse) ProtoMessage()    {}
func (*ItemGalleryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aadb10314c1443a, []int{1}
}

func (m *ItemGalleryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemGalleryResponse.Unmarshal(m, b)
}
func (m *ItemGalleryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemGalleryResponse.Marshal(b, m, deterministic)
}
func (m *ItemGalleryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemGalleryResponse.Merge(m, src)
}
func (m *ItemGalleryResponse) XXX_Size() int {
	return xxx_messageInfo_ItemGalleryResponse.Size(m)
}
func (m *ItemGalleryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemGalleryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ItemGalleryResponse proto.InternalMessageInfo

func (m *ItemGalleryResponse) GetEntity() *ItemGallery {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *ItemGalleryResponse) GetPager() *Pager {
	if m != nil {
		return m.Pager
	}
	return nil
}

func (m *ItemGalleryResponse) GetItems() []*ItemGallery {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ItemGalleryResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ItemGalleryResponse) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*ItemGallery)(nil), "geiqin.srv.pdm.ItemGallery")
	proto.RegisterType((*ItemGalleryResponse)(nil), "geiqin.srv.pdm.ItemGalleryResponse")
}

func init() { proto.RegisterFile("itemGallery.proto", fileDescriptor_4aadb10314c1443a) }

var fileDescriptor_4aadb10314c1443a = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0xcb, 0xd3, 0x40,
	0x10, 0x36, 0x49, 0x93, 0x36, 0x13, 0x29, 0x38, 0x5a, 0x8d, 0xad, 0x42, 0xa8, 0x97, 0x80, 0x10,
	0x30, 0xfd, 0x05, 0x3d, 0x88, 0x44, 0x3c, 0x48, 0xc4, 0x73, 0x4d, 0xbb, 0xd3, 0xb2, 0x34, 0xc9,
	0xc6, 0xcd, 0xa6, 0xd0, 0xa3, 0x3f, 0xdb, 0x9b, 0xec, 0x26, 0xd2, 0xbe, 0x1f, 0xf4, 0x3d, 0xce,
	0xf3, 0x35, 0xb3, 0x0f, 0x0b, 0x2f, 0xb8, 0xa2, 0xea, 0x4b, 0x51, 0x96, 0x24, 0xcf, 0x49, 0x23,
	0x85, 0x12, 0x38, 0x3d, 0x10, 0xff, 0xcd, 0xeb, 0xa4, 0x95, 0xa7, 0xa4, 0x61, 0xd5, 0xfc, 0xf9,
	0x4e, 0x54, 0x95, 0xa8, 0x7b, 0x76, 0xf9, 0xd7, 0x82, 0x20, 0xbb, 0x78, 0x70, 0x0a, 0x36, 0x67,
	0xa1, 0x15, 0x59, 0xb1, 0x93, 0xdb, 0x9c, 0xe1, 0x1b, 0x18, 0xeb, 0xc8, 0x0d, 0x67, 0xa1, 0x6d,
	0x40, 0x4f, 0x8f, 0x19, 0xc3, 0x19, 0x78, 0xed, 0xb1, 0xd3, 0xb8, 0x63, 0x70, 0xb7, 0x3d, 0x76,
	0x19, 0xc3, 0xd7, 0xe0, 0x6d, 0xa9, 0x14, 0xf5, 0x21, 0x1c, 0x45, 0x56, 0xec, 0xe7, 0xc3, 0x84,
	0x6f, 0x61, 0x52, 0x11, 0xe3, 0x85, 0x36, 0xb8, 0xc6, 0x30, 0x36, 0x73, 0xc6, 0x70, 0x01, 0x7e,
	0x4f, 0x75, 0xb2, 0x0c, 0x3d, 0xe3, 0xea, 0xb5, 0x3f, 0x65, 0x89, 0xef, 0xc0, 0x67, 0xb4, 0x2f,
	0xba, 0x52, 0x11, 0x0b, 0xc7, 0x91, 0x15, 0x4f, 0xf2, 0x0b, 0x80, 0xef, 0x01, 0x76, 0x92, 0x0a,
	0x45, 0x6c, 0x53, 0xa8, 0x70, 0x62, 0xbc, 0xfe, 0x80, 0xac, 0x95, 0xa6, 0xbb, 0x86, 0xfd, 0xa7,
	0xfd, 0x9e, 0x1e, 0x90, 0xb5, 0x5a, 0xfe, 0xb1, 0xe1, 0xe5, 0xd5, 0xdb, 0x73, 0x6a, 0x1b, 0x51,
	0xb7, 0x84, 0x2b, 0xf0, 0xa8, 0x56, 0x5c, 0x9d, 0x4d, 0x0f, 0x41, 0xba, 0x48, 0xee, 0x56, 0x98,
	0x5c, 0x9b, 0x06, 0x29, 0x7e, 0x04, 0xb7, 0x29, 0x0e, 0x24, 0x4d, 0x4d, 0x41, 0x3a, 0xbb, 0xef,
	0xf9, 0xae, 0xc9, 0xbc, 0xd7, 0xe0, 0x27, 0x70, 0x75, 0x8d, 0x6d, 0xe8, 0x44, 0xce, 0x53, 0x0b,
	0x7a, 0xa5, 0xce, 0x27, 0x29, 0x85, 0x34, 0xbd, 0x3e, 0x92, 0xff, 0x59, 0x93, 0x79, 0xaf, 0xc1,
	0x18, 0x46, 0xbc, 0xde, 0x0b, 0xd3, 0x74, 0x90, 0xbe, 0x7a, 0x10, 0x5f, 0xef, 0x45, 0x6e, 0x14,
	0xe9, 0x2f, 0xc0, 0xab, 0x65, 0x3f, 0x48, 0x9e, 0xf8, 0x8e, 0xf0, 0x2b, 0x8c, 0xbe, 0xf1, 0x56,
	0xe1, 0xad, 0xc3, 0xe6, 0x1f, 0x6e, 0x5d, 0x3d, 0x74, 0xb9, 0x7c, 0xb6, 0xf5, 0xcc, 0x47, 0x5b,
	0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x34, 0x15, 0x7a, 0xdb, 0x9b, 0x02, 0x00, 0x00,
}
