// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: sku.proto

package geiqin_srv_pdm

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for SkuService service

type SkuService interface {
	List(ctx context.Context, in *Sku, opts ...client.CallOption) (*SkuResponse, error)
}

type skuService struct {
	c    client.Client
	name string
}

func NewSkuService(name string, c client.Client) SkuService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "geiqin.srv.pdm"
	}
	return &skuService{
		c:    c,
		name: name,
	}
}

func (c *skuService) List(ctx context.Context, in *Sku, opts ...client.CallOption) (*SkuResponse, error) {
	req := c.c.NewRequest(c.name, "SkuService.List", in)
	out := new(SkuResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SkuService service

type SkuServiceHandler interface {
	List(context.Context, *Sku, *SkuResponse) error
}

func RegisterSkuServiceHandler(s server.Server, hdlr SkuServiceHandler, opts ...server.HandlerOption) error {
	type skuService interface {
		List(ctx context.Context, in *Sku, out *SkuResponse) error
	}
	type SkuService struct {
		skuService
	}
	h := &skuServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&SkuService{h}, opts...))
}

type skuServiceHandler struct {
	SkuServiceHandler
}

func (h *skuServiceHandler) List(ctx context.Context, in *Sku, out *SkuResponse) error {
	return h.SkuServiceHandler.List(ctx, in, out)
}
