// Code generated by protoc-gen-go. DO NOT EDIT.
// source: export.proto

package geiqin_srv_ord_private

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Export struct {
	DownloadUrl          string   `protobuf:"bytes,1,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	FileSize             int32    `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Export) Reset()         { *m = Export{} }
func (m *Export) String() string { return proto.CompactTextString(m) }
func (*Export) ProtoMessage()    {}
func (*Export) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aa074eea61e559c, []int{0}
}

func (m *Export) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Export.Unmarshal(m, b)
}
func (m *Export) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Export.Marshal(b, m, deterministic)
}
func (m *Export) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Export.Merge(m, src)
}
func (m *Export) XXX_Size() int {
	return xxx_messageInfo_Export.Size(m)
}
func (m *Export) XXX_DiscardUnknown() {
	xxx_messageInfo_Export.DiscardUnknown(m)
}

var xxx_messageInfo_Export proto.InternalMessageInfo

func (m *Export) GetDownloadUrl() string {
	if m != nil {
		return m.DownloadUrl
	}
	return ""
}

func (m *Export) GetFileSize() int32 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

type ExportResponse struct {
	Entity               *Export   `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Pager                *Pager    `protobuf:"bytes,2,opt,name=pager,proto3" json:"pager,omitempty"`
	Items                []*Export `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Error                *Error    `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Info                 *Info     `protobuf:"bytes,5,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ExportResponse) Reset()         { *m = ExportResponse{} }
func (m *ExportResponse) String() string { return proto.CompactTextString(m) }
func (*ExportResponse) ProtoMessage()    {}
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aa074eea61e559c, []int{1}
}

func (m *ExportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExportResponse.Unmarshal(m, b)
}
func (m *ExportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExportResponse.Marshal(b, m, deterministic)
}
func (m *ExportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExportResponse.Merge(m, src)
}
func (m *ExportResponse) XXX_Size() int {
	return xxx_messageInfo_ExportResponse.Size(m)
}
func (m *ExportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExportResponse proto.InternalMessageInfo

func (m *ExportResponse) GetEntity() *Export {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *ExportResponse) GetPager() *Pager {
	if m != nil {
		return m.Pager
	}
	return nil
}

func (m *ExportResponse) GetItems() []*Export {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ExportResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ExportResponse) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*Export)(nil), "geiqin.srv.ord.private.Export")
	proto.RegisterType((*ExportResponse)(nil), "geiqin.srv.ord.private.ExportResponse")
}

func init() {
	proto.RegisterFile("export.proto", fileDescriptor_3aa074eea61e559c)
}

var fileDescriptor_3aa074eea61e559c = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcd, 0x4e, 0xb3, 0x40,
	0x14, 0x86, 0xbf, 0xfe, 0xd0, 0x7c, 0x1d, 0xaa, 0x8b, 0x59, 0x18, 0x82, 0x3f, 0x41, 0x16, 0xa6,
	0xab, 0x89, 0xa1, 0xc6, 0x3b, 0x68, 0xa2, 0x2b, 0xcd, 0x34, 0xc6, 0x85, 0x8b, 0x06, 0xcb, 0xa1,
	0x4e, 0x02, 0x73, 0xf0, 0x30, 0xa2, 0xf6, 0x52, 0xbc, 0x5a, 0xc3, 0x0c, 0xee, 0x44, 0x5d, 0x72,
	0xf2, 0xbc, 0xef, 0xc3, 0x9c, 0xc3, 0x66, 0xf0, 0x56, 0x21, 0x19, 0x51, 0x11, 0x1a, 0xe4, 0x07,
	0x5b, 0x50, 0xcf, 0x4a, 0x8b, 0x9a, 0x1a, 0x81, 0x94, 0x89, 0x8a, 0x54, 0x93, 0x1a, 0x08, 0x67,
	0x1b, 0x2c, 0x4b, 0xd4, 0x8e, 0x0a, 0x7d, 0xa4, 0x0c, 0xc8, 0x7d, 0xc4, 0x57, 0x6c, 0xb2, 0xb4,
	0x15, 0xfc, 0x94, 0xcd, 0x32, 0x7c, 0xd5, 0x05, 0xa6, 0xd9, 0xfa, 0x85, 0x8a, 0x60, 0x10, 0x0d,
	0xe6, 0x53, 0xe9, 0x7f, 0xcd, 0xee, 0xa8, 0xe0, 0x87, 0x6c, 0x9a, 0xab, 0x02, 0xd6, 0xb5, 0xda,
	0x41, 0x30, 0x8c, 0x06, 0x73, 0x4f, 0xfe, 0x6f, 0x07, 0x2b, 0xb5, 0x83, 0xf8, 0x63, 0xc8, 0xf6,
	0x5d, 0x95, 0x84, 0xba, 0x42, 0x5d, 0x03, 0xbf, 0x64, 0x13, 0xd0, 0x46, 0x99, 0x77, 0x5b, 0xe6,
	0x27, 0x27, 0xe2, 0xfb, 0x1f, 0x14, 0x5d, 0xae, 0xa3, 0xf9, 0x82, 0x79, 0x55, 0xba, 0x05, 0xb2,
	0x0e, 0x3f, 0x39, 0xee, 0x8b, 0xdd, 0xb6, 0x90, 0x74, 0x2c, 0xbf, 0x60, 0x9e, 0x32, 0x50, 0xd6,
	0xc1, 0x28, 0x1a, 0xfd, 0xc1, 0xe5, 0xe0, 0x56, 0x05, 0x44, 0x48, 0xc1, 0xf8, 0x67, 0xd5, 0xb2,
	0x85, 0xa4, 0x63, 0xf9, 0x39, 0x1b, 0x2b, 0x9d, 0x63, 0xe0, 0xd9, 0xcc, 0x51, 0x5f, 0xe6, 0x5a,
	0xe7, 0x28, 0x2d, 0x99, 0x14, 0x6c, 0xcf, 0x79, 0x57, 0x40, 0x8d, 0xda, 0x00, 0x7f, 0x60, 0xfe,
	0x4d, 0x7b, 0x86, 0x6e, 0xf9, 0x71, 0x5f, 0x87, 0x85, 0xee, 0x9f, 0x80, 0x20, 0x3c, 0xfb, 0xe5,
	0x45, 0xdd, 0xd6, 0xe3, 0x7f, 0x8f, 0x13, 0x7b, 0xdb, 0xc5, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xa7, 0xa3, 0x54, 0x99, 0x1e, 0x02, 0x00, 0x00,
}
