// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package geiqin_srv_ord_private

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order struct {
	Id                   int64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderSn              string         `protobuf:"bytes,2,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"`
	OrderType            string         `protobuf:"bytes,3,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	CustomerId           int64          `protobuf:"varint,4,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	TotalNum             int32          `protobuf:"varint,6,opt,name=total_num,json=totalNum,proto3" json:"total_num,omitempty"`
	TotalWeight          float32        `protobuf:"fixed32,7,opt,name=total_weight,json=totalWeight,proto3" json:"total_weight,omitempty"`
	Currency             string         `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount               float32        `protobuf:"fixed32,9,opt,name=amount,proto3" json:"amount,omitempty"`
	BeforeAmount         float32        `protobuf:"fixed32,10,opt,name=before_amount,json=beforeAmount,proto3" json:"before_amount,omitempty"`
	ActualAmount         float32        `protobuf:"fixed32,11,opt,name=actual_amount,json=actualAmount,proto3" json:"actual_amount,omitempty"`
	AmountPaid           float32        `protobuf:"fixed32,12,opt,name=amount_paid,json=amountPaid,proto3" json:"amount_paid,omitempty"`
	AmountRefunded       float32        `protobuf:"fixed32,13,opt,name=amount_refunded,json=amountRefunded,proto3" json:"amount_refunded,omitempty"`
	ExpressAmount        float32        `protobuf:"fixed32,14,opt,name=express_amount,json=expressAmount,proto3" json:"express_amount,omitempty"`
	DiscountAmount       float32        `protobuf:"fixed32,15,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	Paid                 bool           `protobuf:"varint,16,opt,name=paid,proto3" json:"paid,omitempty"`
	Refunded             bool           `protobuf:"varint,17,opt,name=refunded,proto3" json:"refunded,omitempty"`
	CanDelivery          bool           `protobuf:"varint,18,opt,name=can_delivery,json=canDelivery,proto3" json:"can_delivery,omitempty"`
	CanCod               bool           `protobuf:"varint,19,opt,name=can_cod,json=canCod,proto3" json:"can_cod,omitempty"`
	Invoiced             bool           `protobuf:"varint,20,opt,name=invoiced,proto3" json:"invoiced,omitempty"`
	Modified             bool           `protobuf:"varint,21,opt,name=modified,proto3" json:"modified,omitempty"`
	Safeguarded          bool           `protobuf:"varint,22,opt,name=safeguarded,proto3" json:"safeguarded,omitempty"`
	Returnable           bool           `protobuf:"varint,23,opt,name=returnable,proto3" json:"returnable,omitempty"`
	Subject              string         `protobuf:"bytes,24,opt,name=subject,proto3" json:"subject,omitempty"`
	Body                 string         `protobuf:"bytes,25,opt,name=body,proto3" json:"body,omitempty"`
	PayType              string         `protobuf:"bytes,26,opt,name=pay_type,json=payType,proto3" json:"pay_type,omitempty"`
	BranchId             int64          `protobuf:"varint,27,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	ClientIp             string         `protobuf:"bytes,28,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Flag                 int32          `protobuf:"varint,29,opt,name=flag,proto3" json:"flag,omitempty"`
	Memo                 string         `protobuf:"bytes,30,opt,name=memo,proto3" json:"memo,omitempty"`
	BuyerMemo            string         `protobuf:"bytes,31,opt,name=buyer_memo,json=buyerMemo,proto3" json:"buyer_memo,omitempty"`
	CancelId             int32          `protobuf:"varint,32,opt,name=cancel_id,json=cancelId,proto3" json:"cancel_id,omitempty"`
	CancelReason         string         `protobuf:"bytes,33,opt,name=cancel_reason,json=cancelReason,proto3" json:"cancel_reason,omitempty"`
	Status               string         `protobuf:"bytes,34,opt,name=status,proto3" json:"status,omitempty"`
	PayStatus            string         `protobuf:"bytes,35,opt,name=pay_status,json=payStatus,proto3" json:"pay_status,omitempty"`
	RefundStatus         string         `protobuf:"bytes,36,opt,name=refund_status,json=refundStatus,proto3" json:"refund_status,omitempty"`
	ShipStatus           string         `protobuf:"bytes,37,opt,name=ship_status,json=shipStatus,proto3" json:"ship_status,omitempty"`
	ExpireAt             string         `protobuf:"bytes,38,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	PaidAt               string         `protobuf:"bytes,39,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	ShippedAt            string         `protobuf:"bytes,40,opt,name=shipped_at,json=shippedAt,proto3" json:"shipped_at,omitempty"`
	SignedAt             string         `protobuf:"bytes,41,opt,name=signed_at,json=signedAt,proto3" json:"signed_at,omitempty"`
	RefundedAt           string         `protobuf:"bytes,42,opt,name=refunded_at,json=refundedAt,proto3" json:"refunded_at,omitempty"`
	FinishedAt           string         `protobuf:"bytes,43,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Address              *OrderAddress  `protobuf:"bytes,54,opt,name=address,proto3" json:"address,omitempty"`
	Details              []*OrderDetail `protobuf:"bytes,55,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Order) GetOrderSn() string {
	if m != nil {
		return m.OrderSn
	}
	return ""
}

func (m *Order) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

func (m *Order) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *Order) GetTotalNum() int32 {
	if m != nil {
		return m.TotalNum
	}
	return 0
}

func (m *Order) GetTotalWeight() float32 {
	if m != nil {
		return m.TotalWeight
	}
	return 0
}

func (m *Order) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Order) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Order) GetBeforeAmount() float32 {
	if m != nil {
		return m.BeforeAmount
	}
	return 0
}

func (m *Order) GetActualAmount() float32 {
	if m != nil {
		return m.ActualAmount
	}
	return 0
}

func (m *Order) GetAmountPaid() float32 {
	if m != nil {
		return m.AmountPaid
	}
	return 0
}

func (m *Order) GetAmountRefunded() float32 {
	if m != nil {
		return m.AmountRefunded
	}
	return 0
}

func (m *Order) GetExpressAmount() float32 {
	if m != nil {
		return m.ExpressAmount
	}
	return 0
}

func (m *Order) GetDiscountAmount() float32 {
	if m != nil {
		return m.DiscountAmount
	}
	return 0
}

func (m *Order) GetPaid() bool {
	if m != nil {
		return m.Paid
	}
	return false
}

func (m *Order) GetRefunded() bool {
	if m != nil {
		return m.Refunded
	}
	return false
}

func (m *Order) GetCanDelivery() bool {
	if m != nil {
		return m.CanDelivery
	}
	return false
}

func (m *Order) GetCanCod() bool {
	if m != nil {
		return m.CanCod
	}
	return false
}

func (m *Order) GetInvoiced() bool {
	if m != nil {
		return m.Invoiced
	}
	return false
}

func (m *Order) GetModified() bool {
	if m != nil {
		return m.Modified
	}
	return false
}

func (m *Order) GetSafeguarded() bool {
	if m != nil {
		return m.Safeguarded
	}
	return false
}

func (m *Order) GetReturnable() bool {
	if m != nil {
		return m.Returnable
	}
	return false
}

func (m *Order) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Order) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Order) GetPayType() string {
	if m != nil {
		return m.PayType
	}
	return ""
}

func (m *Order) GetBranchId() int64 {
	if m != nil {
		return m.BranchId
	}
	return 0
}

func (m *Order) GetClientIp() string {
	if m != nil {
		return m.ClientIp
	}
	return ""
}

func (m *Order) GetFlag() int32 {
	if m != nil {
		return m.Flag
	}
	return 0
}

func (m *Order) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *Order) GetBuyerMemo() string {
	if m != nil {
		return m.BuyerMemo
	}
	return ""
}

func (m *Order) GetCancelId() int32 {
	if m != nil {
		return m.CancelId
	}
	return 0
}

func (m *Order) GetCancelReason() string {
	if m != nil {
		return m.CancelReason
	}
	return ""
}

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Order) GetPayStatus() string {
	if m != nil {
		return m.PayStatus
	}
	return ""
}

func (m *Order) GetRefundStatus() string {
	if m != nil {
		return m.RefundStatus
	}
	return ""
}

func (m *Order) GetShipStatus() string {
	if m != nil {
		return m.ShipStatus
	}
	return ""
}

func (m *Order) GetExpireAt() string {
	if m != nil {
		return m.ExpireAt
	}
	return ""
}

func (m *Order) GetPaidAt() string {
	if m != nil {
		return m.PaidAt
	}
	return ""
}

func (m *Order) GetShippedAt() string {
	if m != nil {
		return m.ShippedAt
	}
	return ""
}

func (m *Order) GetSignedAt() string {
	if m != nil {
		return m.SignedAt
	}
	return ""
}

func (m *Order) GetRefundedAt() string {
	if m != nil {
		return m.RefundedAt
	}
	return ""
}

func (m *Order) GetFinishedAt() string {
	if m != nil {
		return m.FinishedAt
	}
	return ""
}

func (m *Order) GetAddress() *OrderAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Order) GetDetails() []*OrderDetail {
	if m != nil {
		return m.Details
	}
	return nil
}

type OrderDetail struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId              int64    `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ItemId               int64    `protobuf:"varint,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	SkuId                int64    `protobuf:"varint,4,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	ItemSn               string   `protobuf:"bytes,5,opt,name=item_sn,json=itemSn,proto3" json:"item_sn,omitempty"`
	SkuSn                string   `protobuf:"bytes,6,opt,name=sku_sn,json=skuSn,proto3" json:"sku_sn,omitempty"`
	Name                 string   `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Weight               float32  `protobuf:"fixed32,8,opt,name=weight,proto3" json:"weight,omitempty"`
	Price                float32  `protobuf:"fixed32,9,opt,name=price,proto3" json:"price,omitempty"`
	Cost                 float32  `protobuf:"fixed32,10,opt,name=cost,proto3" json:"cost,omitempty"`
	Num                  int32    `protobuf:"varint,11,opt,name=num,proto3" json:"num,omitempty"`
	SendNum              int32    `protobuf:"varint,12,opt,name=send_num,json=sendNum,proto3" json:"send_num,omitempty"`
	Amount               float32  `protobuf:"fixed32,13,opt,name=amount,proto3" json:"amount,omitempty"`
	Points               int32    `protobuf:"varint,14,opt,name=points,proto3" json:"points,omitempty"`
	ItemType             string   `protobuf:"bytes,15,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	Additional           string   `protobuf:"bytes,16,opt,name=additional,proto3" json:"additional,omitempty"`
	PresentId            int64    `protobuf:"varint,19,opt,name=present_id,json=presentId,proto3" json:"present_id,omitempty"`
	OriginPrice          float32  `protobuf:"fixed32,20,opt,name=origin_price,json=originPrice,proto3" json:"origin_price,omitempty"`
	ModifyPrice          float32  `protobuf:"fixed32,21,opt,name=modify_price,json=modifyPrice,proto3" json:"modify_price,omitempty"`
	IsVipBought          bool     `protobuf:"varint,22,opt,name=is_vip_bought,json=isVipBought,proto3" json:"is_vip_bought,omitempty"`
	DistributionProfit   float32  `protobuf:"fixed32,23,opt,name=distribution_profit,json=distributionProfit,proto3" json:"distribution_profit,omitempty"`
	CreatedAt            string   `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderDetail) Reset()         { *m = OrderDetail{} }
func (m *OrderDetail) String() string { return proto.CompactTextString(m) }
func (*OrderDetail) ProtoMessage()    {}
func (*OrderDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *OrderDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDetail.Unmarshal(m, b)
}
func (m *OrderDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDetail.Marshal(b, m, deterministic)
}
func (m *OrderDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDetail.Merge(m, src)
}
func (m *OrderDetail) XXX_Size() int {
	return xxx_messageInfo_OrderDetail.Size(m)
}
func (m *OrderDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDetail.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDetail proto.InternalMessageInfo

func (m *OrderDetail) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OrderDetail) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *OrderDetail) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *OrderDetail) GetSkuId() int64 {
	if m != nil {
		return m.SkuId
	}
	return 0
}

func (m *OrderDetail) GetItemSn() string {
	if m != nil {
		return m.ItemSn
	}
	return ""
}

func (m *OrderDetail) GetSkuSn() string {
	if m != nil {
		return m.SkuSn
	}
	return ""
}

func (m *OrderDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OrderDetail) GetWeight() float32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *OrderDetail) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderDetail) GetCost() float32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *OrderDetail) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *OrderDetail) GetSendNum() int32 {
	if m != nil {
		return m.SendNum
	}
	return 0
}

func (m *OrderDetail) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *OrderDetail) GetPoints() int32 {
	if m != nil {
		return m.Points
	}
	return 0
}

func (m *OrderDetail) GetItemType() string {
	if m != nil {
		return m.ItemType
	}
	return ""
}

func (m *OrderDetail) GetAdditional() string {
	if m != nil {
		return m.Additional
	}
	return ""
}

func (m *OrderDetail) GetPresentId() int64 {
	if m != nil {
		return m.PresentId
	}
	return 0
}

func (m *OrderDetail) GetOriginPrice() float32 {
	if m != nil {
		return m.OriginPrice
	}
	return 0
}

func (m *OrderDetail) GetModifyPrice() float32 {
	if m != nil {
		return m.ModifyPrice
	}
	return 0
}

func (m *OrderDetail) GetIsVipBought() bool {
	if m != nil {
		return m.IsVipBought
	}
	return false
}

func (m *OrderDetail) GetDistributionProfit() float32 {
	if m != nil {
		return m.DistributionProfit
	}
	return 0
}

func (m *OrderDetail) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *OrderDetail) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type OrderWhere struct {
	Paged                int32    `protobuf:"varint,1,opt,name=paged,proto3" json:"paged,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Sorting              string   `protobuf:"bytes,3,opt,name=sorting,proto3" json:"sorting,omitempty"`
	Keywords             string   `protobuf:"bytes,4,opt,name=keywords,proto3" json:"keywords,omitempty"`
	OrderSn              string   `protobuf:"bytes,5,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"`
	OrderType            string   `protobuf:"bytes,6,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	PayType              string   `protobuf:"bytes,7,opt,name=pay_type,json=payType,proto3" json:"pay_type,omitempty"`
	CanDelivery          bool     `protobuf:"varint,8,opt,name=can_delivery,json=canDelivery,proto3" json:"can_delivery,omitempty"`
	CanCod               bool     `protobuf:"varint,9,opt,name=can_cod,json=canCod,proto3" json:"can_cod,omitempty"`
	CustomerId           int64    `protobuf:"varint,10,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Payment              float32  `protobuf:"fixed32,11,opt,name=payment,proto3" json:"payment,omitempty"`
	IsFree               bool     `protobuf:"varint,13,opt,name=is_free,json=isFree,proto3" json:"is_free,omitempty"`
	Status               string   `protobuf:"bytes,26,opt,name=status,proto3" json:"status,omitempty"`
	PayStatus            string   `protobuf:"bytes,27,opt,name=pay_status,json=payStatus,proto3" json:"pay_status,omitempty"`
	RefundStatus         string   `protobuf:"bytes,28,opt,name=refund_status,json=refundStatus,proto3" json:"refund_status,omitempty"`
	DeliverStatus        string   `protobuf:"bytes,29,opt,name=deliver_status,json=deliverStatus,proto3" json:"deliver_status,omitempty"`
	BranchId             int32    `protobuf:"varint,32,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	Flag                 int32    `protobuf:"varint,41,opt,name=flag,proto3" json:"flag,omitempty"`
	Safeguarded          bool     `protobuf:"varint,43,opt,name=safeguarded,proto3" json:"safeguarded,omitempty"`
	StartAt              string   `protobuf:"bytes,51,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt                string   `protobuf:"bytes,52,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderWhere) Reset()         { *m = OrderWhere{} }
func (m *OrderWhere) String() string { return proto.CompactTextString(m) }
func (*OrderWhere) ProtoMessage()    {}
func (*OrderWhere) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{2}
}

func (m *OrderWhere) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderWhere.Unmarshal(m, b)
}
func (m *OrderWhere) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderWhere.Marshal(b, m, deterministic)
}
func (m *OrderWhere) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderWhere.Merge(m, src)
}
func (m *OrderWhere) XXX_Size() int {
	return xxx_messageInfo_OrderWhere.Size(m)
}
func (m *OrderWhere) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderWhere.DiscardUnknown(m)
}

var xxx_messageInfo_OrderWhere proto.InternalMessageInfo

func (m *OrderWhere) GetPaged() int32 {
	if m != nil {
		return m.Paged
	}
	return 0
}

func (m *OrderWhere) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *OrderWhere) GetSorting() string {
	if m != nil {
		return m.Sorting
	}
	return ""
}

func (m *OrderWhere) GetKeywords() string {
	if m != nil {
		return m.Keywords
	}
	return ""
}

func (m *OrderWhere) GetOrderSn() string {
	if m != nil {
		return m.OrderSn
	}
	return ""
}

func (m *OrderWhere) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

func (m *OrderWhere) GetPayType() string {
	if m != nil {
		return m.PayType
	}
	return ""
}

func (m *OrderWhere) GetCanDelivery() bool {
	if m != nil {
		return m.CanDelivery
	}
	return false
}

func (m *OrderWhere) GetCanCod() bool {
	if m != nil {
		return m.CanCod
	}
	return false
}

func (m *OrderWhere) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *OrderWhere) GetPayment() float32 {
	if m != nil {
		return m.Payment
	}
	return 0
}

func (m *OrderWhere) GetIsFree() bool {
	if m != nil {
		return m.IsFree
	}
	return false
}

func (m *OrderWhere) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OrderWhere) GetPayStatus() string {
	if m != nil {
		return m.PayStatus
	}
	return ""
}

func (m *OrderWhere) GetRefundStatus() string {
	if m != nil {
		return m.RefundStatus
	}
	return ""
}

func (m *OrderWhere) GetDeliverStatus() string {
	if m != nil {
		return m.DeliverStatus
	}
	return ""
}

func (m *OrderWhere) GetBranchId() int32 {
	if m != nil {
		return m.BranchId
	}
	return 0
}

func (m *OrderWhere) GetFlag() int32 {
	if m != nil {
		return m.Flag
	}
	return 0
}

func (m *OrderWhere) GetSafeguarded() bool {
	if m != nil {
		return m.Safeguarded
	}
	return false
}

func (m *OrderWhere) GetStartAt() string {
	if m != nil {
		return m.StartAt
	}
	return ""
}

func (m *OrderWhere) GetEndAt() string {
	if m != nil {
		return m.EndAt
	}
	return ""
}

type OrderResponse struct {
	Entity               *Order   `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Pager                *Pager   `protobuf:"bytes,2,opt,name=pager,proto3" json:"pager,omitempty"`
	Items                []*Order `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Error                *Error   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Info                 *Info    `protobuf:"bytes,5,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderResponse) Reset()         { *m = OrderResponse{} }
func (m *OrderResponse) String() string { return proto.CompactTextString(m) }
func (*OrderResponse) ProtoMessage()    {}
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{3}
}

func (m *OrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderResponse.Unmarshal(m, b)
}
func (m *OrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderResponse.Marshal(b, m, deterministic)
}
func (m *OrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderResponse.Merge(m, src)
}
func (m *OrderResponse) XXX_Size() int {
	return xxx_messageInfo_OrderResponse.Size(m)
}
func (m *OrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderResponse proto.InternalMessageInfo

func (m *OrderResponse) GetEntity() *Order {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *OrderResponse) GetPager() *Pager {
	if m != nil {
		return m.Pager
	}
	return nil
}

func (m *OrderResponse) GetItems() []*Order {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *OrderResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *OrderResponse) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*Order)(nil), "geiqin.srv.ord.private.Order")
	proto.RegisterType((*OrderDetail)(nil), "geiqin.srv.ord.private.OrderDetail")
	proto.RegisterType((*OrderWhere)(nil), "geiqin.srv.ord.private.OrderWhere")
	proto.RegisterType((*OrderResponse)(nil), "geiqin.srv.ord.private.OrderResponse")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 1499 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x58, 0x4d, 0x73, 0x1b, 0xb9,
	0x11, 0x8d, 0x44, 0xf1, 0x0b, 0x24, 0x25, 0x1b, 0xb6, 0x65, 0x58, 0xb2, 0x24, 0x5a, 0xb2, 0x6c,
	0x3a, 0xae, 0x52, 0x52, 0x72, 0x3e, 0x4e, 0x49, 0x15, 0x2d, 0x27, 0x29, 0x1d, 0x14, 0xcb, 0xc3,
	0x24, 0xae, 0xe4, 0xc2, 0x02, 0x67, 0x40, 0x0a, 0x11, 0x89, 0x19, 0x03, 0x18, 0xd9, 0xf4, 0x69,
	0xff, 0xc5, 0xfe, 0xb9, 0x3d, 0xf9, 0xbc, 0x3f, 0x62, 0xab, 0xbb, 0x31, 0x12, 0x25, 0xdb, 0xf4,
	0x6e, 0x15, 0x2f, 0x7b, 0x43, 0xbf, 0x7e, 0x68, 0x60, 0xc0, 0xd7, 0x0f, 0x28, 0xb2, 0x46, 0x6a,
	0x13, 0x65, 0x0f, 0x32, 0x9b, 0xfa, 0x94, 0xaf, 0x8f, 0x94, 0x7e, 0xa7, 0xcd, 0x81, 0xb3, 0x17,
	0x07, 0xa9, 0x4d, 0x0e, 0x32, 0xab, 0x2f, 0xa4, 0x57, 0x1b, 0xcd, 0x38, 0x9d, 0x4c, 0x52, 0x43,
	0xac, 0x8d, 0xe6, 0x20, 0x9f, 0x6a, 0x33, 0x0a, 0x11, 0xc7, 0x02, 0xdd, 0x24, 0xb1, 0xca, 0x39,
	0xc2, 0x76, 0x7f, 0x64, 0xac, 0xfc, 0x1a, 0x60, 0xbe, 0xca, 0x96, 0x75, 0x22, 0x96, 0xda, 0x4b,
	0x9d, 0x52, 0xb4, 0xac, 0x13, 0xfe, 0x80, 0xd5, 0x90, 0xdf, 0x77, 0x46, 0x2c, 0xb7, 0x97, 0x3a,
	0xf5, 0xa8, 0x8a, 0x71, 0xcf, 0xf0, 0x2d, 0xc6, 0x28, 0xe5, 0xa7, 0x99, 0x12, 0x25, 0x4c, 0xd6,
	0x11, 0xf9, 0xd7, 0x34, 0x53, 0x7c, 0x87, 0x35, 0xe2, 0xdc, 0xf9, 0x74, 0xa2, 0x6c, 0x5f, 0x27,
	0x62, 0x05, 0x4b, 0xb2, 0x02, 0x3a, 0x4e, 0xf8, 0x26, 0xab, 0xfb, 0xd4, 0xcb, 0x71, 0xdf, 0xe4,
	0x13, 0x51, 0x69, 0x2f, 0x75, 0xca, 0x51, 0x0d, 0x81, 0x7f, 0xe6, 0x13, 0xfe, 0x88, 0x35, 0x29,
	0xf9, 0x5e, 0xe9, 0xd1, 0x99, 0x17, 0xd5, 0xf6, 0x52, 0x67, 0x39, 0x6a, 0x20, 0xf6, 0x16, 0x21,
	0xbe, 0xc1, 0x6a, 0x71, 0x6e, 0xad, 0x32, 0xf1, 0x54, 0xd4, 0x70, 0xf5, 0xcb, 0x98, 0xaf, 0xb3,
	0x8a, 0x9c, 0xa4, 0xb9, 0xf1, 0xa2, 0x8e, 0x13, 0x43, 0xc4, 0xf7, 0x58, 0x6b, 0xa0, 0x86, 0xa9,
	0x55, 0xfd, 0x90, 0x66, 0x98, 0x6e, 0x12, 0xd8, 0xbd, 0x24, 0xc9, 0xd8, 0xe7, 0x72, 0x5c, 0x90,
	0x1a, 0x44, 0x22, 0x30, 0x90, 0x76, 0x58, 0x83, 0xb2, 0xfd, 0x4c, 0xea, 0x44, 0x34, 0x91, 0xc2,
	0x08, 0x3a, 0x95, 0x3a, 0xe1, 0x4f, 0xd9, 0x5a, 0x20, 0x58, 0x35, 0xcc, 0x4d, 0xa2, 0x12, 0xd1,
	0x42, 0xd2, 0x2a, 0xc1, 0x51, 0x40, 0xf9, 0x3e, 0x5b, 0x55, 0x1f, 0x32, 0xf8, 0x35, 0x8a, 0xf5,
	0x56, 0x91, 0xd7, 0x0a, 0x68, 0x58, 0xf0, 0x29, 0x5b, 0x4b, 0xb4, 0x8b, 0xb1, 0x62, 0xe0, 0xad,
	0x51, 0xbd, 0x02, 0x0e, 0x44, 0xce, 0x56, 0x70, 0x4b, 0xb7, 0xda, 0x4b, 0x9d, 0x5a, 0x84, 0x63,
	0x38, 0xab, 0xcb, 0x5d, 0xdc, 0x46, 0xfc, 0x32, 0x86, 0xa3, 0x8e, 0xa5, 0xe9, 0x27, 0x6a, 0xac,
	0x2f, 0x94, 0x9d, 0x0a, 0x8e, 0xf9, 0x46, 0x2c, 0xcd, 0xab, 0x00, 0xf1, 0xfb, 0xac, 0x0a, 0x94,
	0x38, 0x4d, 0xc4, 0x1d, 0xcc, 0x56, 0x62, 0x69, 0x8e, 0x52, 0xac, 0xab, 0xcd, 0x45, 0xaa, 0x63,
	0x95, 0x88, 0xbb, 0x54, 0xb7, 0x88, 0x21, 0x37, 0x49, 0x13, 0x3d, 0xd4, 0x2a, 0x11, 0xf7, 0x28,
	0x57, 0xc4, 0xbc, 0xcd, 0x1a, 0x4e, 0x0e, 0xd5, 0x28, 0x97, 0x16, 0xb6, 0xb4, 0x4e, 0x4b, 0xce,
	0x40, 0x7c, 0x9b, 0x31, 0xab, 0x7c, 0x6e, 0x8d, 0x1c, 0x8c, 0x95, 0xb8, 0x8f, 0x84, 0x19, 0x84,
	0x0b, 0x56, 0x75, 0xf9, 0xe0, 0xff, 0x2a, 0xf6, 0x42, 0x90, 0x2e, 0x43, 0x08, 0xdf, 0x3f, 0x48,
	0x93, 0xa9, 0x78, 0x80, 0x30, 0x8e, 0x41, 0xc6, 0x99, 0x9c, 0x92, 0x52, 0x37, 0x88, 0x9e, 0xc9,
	0x29, 0xea, 0x74, 0x93, 0xd5, 0x07, 0x56, 0x9a, 0xf8, 0x0c, 0x54, 0xba, 0x89, 0x2a, 0xad, 0x11,
	0x40, 0x1a, 0x8d, 0xc7, 0x5a, 0x19, 0xdf, 0xd7, 0x99, 0x78, 0x18, 0x44, 0x86, 0xc0, 0x71, 0x06,
	0x0b, 0x0d, 0xc7, 0x72, 0x24, 0xb6, 0x50, 0xbb, 0x38, 0x06, 0x6c, 0xa2, 0x26, 0xa9, 0xd8, 0xa6,
	0xc5, 0x61, 0x0c, 0x8d, 0x32, 0xc8, 0xa7, 0xca, 0xf6, 0x31, 0xb3, 0x43, 0x8d, 0x82, 0xc8, 0x09,
	0xa4, 0x61, 0x0d, 0x69, 0x62, 0x35, 0x86, 0x0d, 0xb4, 0xa9, 0x0f, 0x08, 0x38, 0x4e, 0x40, 0x8b,
	0x21, 0x69, 0x95, 0x74, 0xa9, 0x11, 0x8f, 0x70, 0x7a, 0x93, 0xc0, 0x08, 0x31, 0x50, 0xbb, 0xf3,
	0xd2, 0xe7, 0x4e, 0xec, 0x62, 0x36, 0x44, 0xb0, 0x30, 0x7c, 0x75, 0xc8, 0xed, 0xd1, 0xc2, 0x99,
	0x9c, 0xf6, 0x28, 0xbd, 0xc7, 0x5a, 0x24, 0x82, 0x82, 0xf1, 0x98, 0x6a, 0x13, 0x18, 0x48, 0x3b,
	0xac, 0xe1, 0xce, 0x74, 0x56, 0x50, 0xf6, 0x91, 0xc2, 0x00, 0x0a, 0x84, 0x4d, 0x56, 0x57, 0x1f,
	0x32, 0x0d, 0x2d, 0xe5, 0xc5, 0x13, 0x3a, 0x22, 0x02, 0xba, 0x1e, 0x84, 0x03, 0xfa, 0x83, 0xd4,
	0x53, 0xda, 0x1a, 0x84, 0x5d, 0x0f, 0x5b, 0x83, 0x1a, 0x99, 0xc2, 0x5c, 0x87, 0xb6, 0x16, 0x90,
	0xae, 0x87, 0xa2, 0x4e, 0x8f, 0x0c, 0x65, 0x9f, 0x51, 0x51, 0x02, 0xba, 0xd8, 0x7a, 0x85, 0x78,
	0x21, 0xfd, 0x5b, 0xda, 0x52, 0x01, 0x11, 0x61, 0xa8, 0x8d, 0x76, 0x67, 0x44, 0x78, 0x4e, 0x84,
	0x02, 0xea, 0x7a, 0xfe, 0x57, 0x56, 0x95, 0x64, 0x80, 0xe2, 0x4f, 0xed, 0xa5, 0x4e, 0xe3, 0xf0,
	0xf1, 0xc1, 0x97, 0x9d, 0xf4, 0xe0, 0xf5, 0x8c, 0x59, 0x46, 0xc5, 0x24, 0xfe, 0x17, 0x56, 0x4d,
	0x94, 0x97, 0x7a, 0xec, 0xc4, 0x9f, 0xdb, 0xa5, 0x4e, 0xe3, 0x70, 0x6f, 0xee, 0xfc, 0x57, 0xc8,
	0x8d, 0x8a, 0x39, 0xbb, 0xdf, 0x95, 0x59, 0x63, 0x26, 0xf1, 0x75, 0xd3, 0xd5, 0x09, 0x9a, 0x6e,
	0x29, 0x98, 0xee, 0x71, 0x02, 0x07, 0xaa, 0xbd, 0x9a, 0x40, 0xa6, 0x84, 0x99, 0x0a, 0x84, 0xc7,
	0x09, 0xbf, 0xc7, 0x2a, 0xee, 0x3c, 0xbf, 0x72, 0xda, 0xb2, 0x3b, 0xcf, 0x67, 0xf8, 0xce, 0x88,
	0x32, 0xfd, 0x00, 0x10, 0xf6, 0x4c, 0xc1, 0x77, 0x06, 0xad, 0xb7, 0x8e, 0xfc, 0x9e, 0x01, 0xfd,
	0x1a, 0x39, 0x51, 0xe8, 0xb7, 0xf5, 0x08, 0xc7, 0x20, 0xaf, 0xe0, 0xc2, 0x35, 0x32, 0x53, 0x8a,
	0xf8, 0x5d, 0x56, 0xce, 0xac, 0x8e, 0x55, 0xf0, 0x58, 0x0a, 0xa0, 0x42, 0x9c, 0xba, 0xc2, 0x59,
	0x71, 0xcc, 0x6f, 0xb1, 0x12, 0x98, 0x7c, 0x03, 0xc5, 0x0d, 0x43, 0xf8, 0x44, 0xa7, 0x4c, 0x82,
	0xde, 0xdf, 0x44, 0xb8, 0x0a, 0x31, 0x58, 0xff, 0x95, 0x77, 0xb7, 0xae, 0x79, 0xf7, 0x3a, 0xab,
	0x64, 0xa9, 0x36, 0xde, 0xa1, 0x3f, 0x96, 0xa3, 0x10, 0x81, 0x56, 0xf0, 0x13, 0xb1, 0xb9, 0xd7,
	0x48, 0x2b, 0x00, 0x60, 0x77, 0x6f, 0x33, 0x26, 0x93, 0x44, 0x7b, 0x9d, 0x1a, 0x39, 0x46, 0x4b,
	0xac, 0x47, 0x33, 0x08, 0xb6, 0x88, 0x55, 0x0e, 0x3b, 0x9c, 0xcc, 0xad, 0x14, 0xd5, 0x03, 0x72,
	0x8c, 0xde, 0x98, 0x5a, 0x3d, 0xd2, 0xa6, 0x4f, 0x5f, 0x7a, 0x97, 0xae, 0x21, 0xc2, 0x4e, 0xf1,
	0x7b, 0x1f, 0xb1, 0x26, 0xda, 0xda, 0x34, 0x50, 0xee, 0x11, 0x85, 0x30, 0xa2, 0xec, 0xb2, 0x96,
	0x76, 0xfd, 0x0b, 0x9d, 0xf5, 0x07, 0x69, 0x0e, 0xe7, 0x18, 0xfc, 0x4e, 0xbb, 0xff, 0xe8, 0xec,
	0x25, 0x42, 0xfc, 0x77, 0xec, 0x4e, 0xa2, 0x9d, 0xb7, 0x7a, 0x90, 0xc3, 0xd6, 0xfa, 0x99, 0x4d,
	0x87, 0xda, 0xa3, 0xf1, 0x2d, 0x47, 0x7c, 0x36, 0x75, 0x8a, 0x19, 0xd8, 0x79, 0x6c, 0x95, 0xf4,
	0xa4, 0xf1, 0xdb, 0xd4, 0x41, 0x01, 0xa1, 0x06, 0xcb, 0xb3, 0xa4, 0x48, 0x73, 0x4a, 0x07, 0xa4,
	0xeb, 0x77, 0x3f, 0xad, 0x30, 0x86, 0x12, 0x7c, 0x7b, 0xa6, 0xac, 0xc2, 0x9f, 0x52, 0x8e, 0x14,
	0x89, 0xb0, 0x1c, 0x51, 0x00, 0x27, 0x0b, 0x83, 0xbe, 0xd3, 0x1f, 0x15, 0x0a, 0xb1, 0x1c, 0xd5,
	0x00, 0xe8, 0xe9, 0x8f, 0x64, 0xc0, 0xa9, 0xf5, 0xda, 0x8c, 0xc2, 0xdd, 0x5f, 0x84, 0x60, 0xfc,
	0xe7, 0x6a, 0xfa, 0x3e, 0xb5, 0x89, 0x43, 0x31, 0xd6, 0xa3, 0xcb, 0xf8, 0xda, 0x7b, 0xa2, 0x3c,
	0xef, 0x3d, 0x51, 0xb9, 0xf9, 0x9e, 0x98, 0xb5, 0xf0, 0xea, 0x75, 0x0b, 0xbf, 0x79, 0x83, 0xd5,
	0xe6, 0xde, 0x60, 0xf5, 0x6b, 0x37, 0xd8, 0x8d, 0x67, 0x0a, 0xfb, 0xec, 0x99, 0x22, 0xc0, 0xc2,
	0xa6, 0x13, 0x75, 0xf9, 0x0e, 0x28, 0x42, 0xec, 0x2d, 0xd7, 0x1f, 0x5a, 0xa5, 0x50, 0xa9, 0xb5,
	0xa8, 0xa2, 0xdd, 0xdf, 0xad, 0x52, 0x33, 0x7e, 0xbc, 0x31, 0xc7, 0x8f, 0x37, 0xbf, 0xe9, 0xc7,
	0x0f, 0xbf, 0xe0, 0xc7, 0xfb, 0x6c, 0x35, 0x7c, 0x67, 0xc1, 0xda, 0x42, 0x56, 0x2b, 0xa0, 0x57,
	0xae, 0x7c, 0x75, 0xab, 0x85, 0x4b, 0xe5, 0xf2, 0x56, 0x2b, 0x2e, 0xae, 0x67, 0x33, 0x17, 0xd7,
	0x8d, 0x1b, 0xf9, 0xf9, 0xe7, 0x37, 0x32, 0xb4, 0xac, 0x97, 0xd6, 0x83, 0x9e, 0x5e, 0x84, 0x5f,
	0x1c, 0xe2, 0xae, 0x07, 0x33, 0x81, 0x66, 0x96, 0x5e, 0xfc, 0x81, 0xcc, 0x44, 0x19, 0x10, 0xd9,
	0xf7, 0xcb, 0xac, 0x85, 0x22, 0x8b, 0x94, 0xcb, 0x52, 0xe3, 0x14, 0xff, 0x23, 0x10, 0xbd, 0xf6,
	0x53, 0x14, 0x5a, 0xe3, 0x70, 0x6b, 0xae, 0x6f, 0x46, 0x81, 0xcc, 0x5f, 0x90, 0x3c, 0x2d, 0x8a,
	0x70, 0xce, 0xac, 0x53, 0x20, 0x91, 0x7a, 0x2d, 0x4c, 0x02, 0x1b, 0x70, 0xa2, 0x84, 0x16, 0xfd,
	0x8d, 0xa5, 0x88, 0x0b, 0x93, 0x94, 0xb5, 0xa9, 0x45, 0xe1, 0xce, 0x99, 0xf4, 0x37, 0x20, 0x45,
	0xc4, 0xe5, 0xbf, 0x67, 0x2b, 0xda, 0x0c, 0x53, 0x14, 0x74, 0xe3, 0xf0, 0xe1, 0xd7, 0xe6, 0x1c,
	0x9b, 0x61, 0x1a, 0x21, 0xf3, 0xf0, 0x87, 0x15, 0xb6, 0x7a, 0x32, 0xc5, 0x95, 0x7b, 0xca, 0x5e,
	0x80, 0x49, 0xfc, 0x8f, 0x55, 0x8f, 0x52, 0x33, 0xd4, 0x76, 0xc2, 0xf7, 0xbf, 0x56, 0xe1, 0x25,
	0x3e, 0xe4, 0x23, 0xf5, 0x2e, 0x57, 0xce, 0x6f, 0x3c, 0xf9, 0x16, 0x8d, 0x0e, 0x7d, 0xf7, 0x37,
	0xfc, 0x0d, 0xab, 0xf4, 0xf2, 0xc1, 0x44, 0x7b, 0xbe, 0x3d, 0x7f, 0xce, 0xc6, 0xfe, 0xfc, 0x53,
	0xba, 0x2a, 0x79, 0xca, 0x2a, 0xaf, 0xd4, 0x58, 0x79, 0xc5, 0xe7, 0x1f, 0xec, 0x2f, 0xaa, 0x78,
	0x84, 0xaf, 0x9a, 0x85, 0x55, 0x7c, 0xc3, 0xaa, 0x91, 0x8a, 0x95, 0xce, 0xfc, 0xc2, 0x4a, 0x9e,
	0xb0, 0xd2, 0x3f, 0xd4, 0xe2, 0xca, 0xfd, 0x9b, 0x55, 0x7a, 0x4a, 0xda, 0xf8, 0x8c, 0xef, 0xce,
	0x9d, 0x82, 0x2e, 0xfd, 0xb3, 0xcb, 0x1e, 0x7e, 0x5a, 0x61, 0xcd, 0x6b, 0xe2, 0xfa, 0x2f, 0xab,
	0x1c, 0xe1, 0xd5, 0xb0, 0x78, 0x6d, 0xbd, 0x66, 0xe5, 0xa3, 0x33, 0x15, 0x9f, 0x2f, 0xf0, 0x4c,
	0x1a, 0x27, 0x33, 0x97, 0xe7, 0xa2, 0xca, 0xbe, 0x65, 0x2d, 0x2a, 0x1b, 0x5e, 0x73, 0x8b, 0xd4,
	0xed, 0x82, 0x3b, 0xe1, 0x57, 0x21, 0xb2, 0x41, 0x05, 0xff, 0x3b, 0x78, 0xf1, 0x53, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x91, 0x50, 0xdf, 0x8f, 0x92, 0x10, 0x00, 0x00,
}
