// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orderDetail.proto

package geiqin_srv_ord_private

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderDetail struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	OrderId              int64    `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id"`
	ItemId               int64    `protobuf:"varint,3,opt,name=item_id,json=itemId,proto3" json:"item_id"`
	ThumbId              int64    `protobuf:"varint,4,opt,name=thumb_id,json=thumbId,proto3" json:"thumb_id"`
	ThumbUrl             string   `protobuf:"bytes,5,opt,name=thumb_url,json=thumbUrl,proto3" json:"thumb_url"`
	SkuId                int64    `protobuf:"varint,6,opt,name=sku_id,json=skuId,proto3" json:"sku_id"`
	ItemSn               string   `protobuf:"bytes,7,opt,name=item_sn,json=itemSn,proto3" json:"item_sn"`
	SkuSn                string   `protobuf:"bytes,8,opt,name=sku_sn,json=skuSn,proto3" json:"sku_sn"`
	ModelType            string   `protobuf:"bytes,9,opt,name=model_type,json=modelType,proto3" json:"model_type"`
	Name                 string   `protobuf:"bytes,10,opt,name=name,proto3" json:"name"`
	Weight               float32  `protobuf:"fixed32,11,opt,name=weight,proto3" json:"weight"`
	Num                  int32    `protobuf:"varint,12,opt,name=num,proto3" json:"num"`
	Price                float32  `protobuf:"fixed32,13,opt,name=price,proto3" json:"price"`
	TotalPrice           float32  `protobuf:"fixed32,14,opt,name=total_price,json=totalPrice,proto3" json:"total_price"`
	OriginPrice          float32  `protobuf:"fixed32,15,opt,name=origin_price,json=originPrice,proto3" json:"origin_price"`
	CostPrice            float32  `protobuf:"fixed32,16,opt,name=cost_price,json=costPrice,proto3" json:"cost_price"`
	BeforePrice          float32  `protobuf:"fixed32,17,opt,name=before_price,json=beforePrice,proto3" json:"before_price"`
	Modified             bool     `protobuf:"varint,18,opt,name=modified,proto3" json:"modified"`
	ShippedNum           int32    `protobuf:"varint,19,opt,name=shipped_num,json=shippedNum,proto3" json:"shipped_num"`
	Points               int32    `protobuf:"varint,20,opt,name=points,proto3" json:"points"`
	SaleType             string   `protobuf:"bytes,21,opt,name=sale_type,json=saleType,proto3" json:"sale_type"`
	Additional           string   `protobuf:"bytes,22,opt,name=additional,proto3" json:"additional"`
	Attached             bool     `protobuf:"varint,23,opt,name=attached,proto3" json:"attached"`
	AttachType           string   `protobuf:"bytes,24,opt,name=attach_type,json=attachType,proto3" json:"attach_type"`
	ShipStatus           string   `protobuf:"bytes,25,opt,name=ship_status,json=shipStatus,proto3" json:"ship_status"`
	RefundStatus         string   `protobuf:"bytes,26,opt,name=refund_status,json=refundStatus,proto3" json:"refund_status"`
	CreatedAt            string   `protobuf:"bytes,27,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,28,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderDetail) Reset()         { *m = OrderDetail{} }
func (m *OrderDetail) String() string { return proto.CompactTextString(m) }
func (*OrderDetail) ProtoMessage()    {}
func (*OrderDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_28901a6159ef662a, []int{0}
}

func (m *OrderDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDetail.Unmarshal(m, b)
}
func (m *OrderDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDetail.Marshal(b, m, deterministic)
}
func (m *OrderDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDetail.Merge(m, src)
}
func (m *OrderDetail) XXX_Size() int {
	return xxx_messageInfo_OrderDetail.Size(m)
}
func (m *OrderDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDetail.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDetail proto.InternalMessageInfo

func (m *OrderDetail) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OrderDetail) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *OrderDetail) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *OrderDetail) GetThumbId() int64 {
	if m != nil {
		return m.ThumbId
	}
	return 0
}

func (m *OrderDetail) GetThumbUrl() string {
	if m != nil {
		return m.ThumbUrl
	}
	return ""
}

func (m *OrderDetail) GetSkuId() int64 {
	if m != nil {
		return m.SkuId
	}
	return 0
}

func (m *OrderDetail) GetItemSn() string {
	if m != nil {
		return m.ItemSn
	}
	return ""
}

func (m *OrderDetail) GetSkuSn() string {
	if m != nil {
		return m.SkuSn
	}
	return ""
}

func (m *OrderDetail) GetModelType() string {
	if m != nil {
		return m.ModelType
	}
	return ""
}

func (m *OrderDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OrderDetail) GetWeight() float32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *OrderDetail) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *OrderDetail) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderDetail) GetTotalPrice() float32 {
	if m != nil {
		return m.TotalPrice
	}
	return 0
}

func (m *OrderDetail) GetOriginPrice() float32 {
	if m != nil {
		return m.OriginPrice
	}
	return 0
}

func (m *OrderDetail) GetCostPrice() float32 {
	if m != nil {
		return m.CostPrice
	}
	return 0
}

func (m *OrderDetail) GetBeforePrice() float32 {
	if m != nil {
		return m.BeforePrice
	}
	return 0
}

func (m *OrderDetail) GetModified() bool {
	if m != nil {
		return m.Modified
	}
	return false
}

func (m *OrderDetail) GetShippedNum() int32 {
	if m != nil {
		return m.ShippedNum
	}
	return 0
}

func (m *OrderDetail) GetPoints() int32 {
	if m != nil {
		return m.Points
	}
	return 0
}

func (m *OrderDetail) GetSaleType() string {
	if m != nil {
		return m.SaleType
	}
	return ""
}

func (m *OrderDetail) GetAdditional() string {
	if m != nil {
		return m.Additional
	}
	return ""
}

func (m *OrderDetail) GetAttached() bool {
	if m != nil {
		return m.Attached
	}
	return false
}

func (m *OrderDetail) GetAttachType() string {
	if m != nil {
		return m.AttachType
	}
	return ""
}

func (m *OrderDetail) GetShipStatus() string {
	if m != nil {
		return m.ShipStatus
	}
	return ""
}

func (m *OrderDetail) GetRefundStatus() string {
	if m != nil {
		return m.RefundStatus
	}
	return ""
}

func (m *OrderDetail) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *OrderDetail) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*OrderDetail)(nil), "geiqin.srv.ord.private.OrderDetail")
}

func init() {
	proto.RegisterFile("orderDetail.proto", fileDescriptor_28901a6159ef662a)
}

var fileDescriptor_28901a6159ef662a = []byte{
	// 479 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x93, 0xc1, 0x72, 0xd3, 0x30,
	0x10, 0x86, 0xc7, 0x49, 0xe3, 0x24, 0x9b, 0xb4, 0xb4, 0xa2, 0x4d, 0xd5, 0x96, 0x82, 0x81, 0x8b,
	0x4f, 0xb9, 0xf0, 0x04, 0x9d, 0xe1, 0x92, 0x0b, 0x30, 0x0e, 0x9c, 0x3d, 0x4a, 0xa4, 0x24, 0x9a,
	0xda, 0x92, 0x91, 0xd6, 0x65, 0xfa, 0x2e, 0x3c, 0x2c, 0xa3, 0x95, 0x52, 0x7a, 0xd3, 0x7e, 0xff,
	0xb7, 0xeb, 0xb5, 0x9c, 0xc0, 0x85, 0x75, 0x52, 0xb9, 0xaf, 0x0a, 0x85, 0x6e, 0x96, 0x9d, 0xb3,
	0x68, 0xd9, 0x62, 0xaf, 0xf4, 0x6f, 0x6d, 0x96, 0xde, 0x3d, 0x2d, 0xad, 0x93, 0xcb, 0xce, 0xe9,
	0x27, 0x81, 0xea, 0xd3, 0xdf, 0x1c, 0x66, 0xdf, 0xff, 0xdb, 0xec, 0x0c, 0x06, 0x5a, 0xf2, 0xac,
	0xc8, 0xca, 0x61, 0x35, 0xd0, 0x92, 0xdd, 0xc0, 0x84, 0x86, 0xd5, 0x5a, 0xf2, 0x01, 0xd1, 0x31,
	0xd5, 0x2b, 0xc9, 0xae, 0x61, 0xac, 0x51, 0xb5, 0x21, 0x19, 0x52, 0x92, 0x87, 0x72, 0x45, 0x3d,
	0x78, 0xe8, 0xdb, 0x4d, 0x48, 0x4e, 0x62, 0x0f, 0xd5, 0x2b, 0xc9, 0xee, 0x60, 0x1a, 0xa3, 0xde,
	0x35, 0x7c, 0x54, 0x64, 0xe5, 0xb4, 0x8a, 0xee, 0x2f, 0xd7, 0xb0, 0x2b, 0xc8, 0xfd, 0x63, 0x1f,
	0xba, 0x72, 0xea, 0x1a, 0xf9, 0xc7, 0xfe, 0xd5, 0x73, 0xbc, 0xe1, 0x63, 0xea, 0xa0, 0xe7, 0xac,
	0xcd, 0xd1, 0xf7, 0x86, 0x4f, 0x88, 0x07, 0x7f, 0x6d, 0xd8, 0x3d, 0x40, 0x6b, 0xa5, 0x6a, 0x6a,
	0x7c, 0xee, 0x14, 0x9f, 0x52, 0x34, 0x25, 0xf2, 0xf3, 0xb9, 0x53, 0x8c, 0xc1, 0x89, 0x11, 0xad,
	0xe2, 0x40, 0x01, 0x9d, 0xd9, 0x02, 0xf2, 0x3f, 0x4a, 0xef, 0x0f, 0xc8, 0x67, 0x45, 0x56, 0x0e,
	0xaa, 0x54, 0xb1, 0x73, 0x18, 0x9a, 0xbe, 0xe5, 0xf3, 0x22, 0x2b, 0x47, 0x55, 0x38, 0xb2, 0x4b,
	0x18, 0x75, 0x4e, 0x6f, 0x15, 0x3f, 0x25, 0x31, 0x16, 0xec, 0x03, 0xcc, 0xd0, 0xa2, 0x68, 0xea,
	0x98, 0x9d, 0x51, 0x06, 0x84, 0x7e, 0x90, 0xf0, 0x11, 0xe6, 0xd6, 0xe9, 0xbd, 0x36, 0xc9, 0x78,
	0x43, 0xc6, 0x2c, 0xb2, 0xa8, 0xdc, 0x03, 0x6c, 0xad, 0xc7, 0x24, 0x9c, 0x93, 0x30, 0x0d, 0xe4,
	0x65, 0xc2, 0x46, 0xed, 0xac, 0x53, 0x49, 0xb8, 0x88, 0x13, 0x22, 0x8b, 0xca, 0x2d, 0x4c, 0x5a,
	0x2b, 0xf5, 0x4e, 0x2b, 0xc9, 0x59, 0x91, 0x95, 0x93, 0xea, 0xa5, 0x0e, 0x1b, 0xfa, 0x83, 0xee,
	0x3a, 0x25, 0xeb, 0xf0, 0x46, 0x6f, 0xe9, 0x8d, 0x20, 0xa1, 0x6f, 0x7d, 0x1b, 0xae, 0xa0, 0xb3,
	0xda, 0xa0, 0xe7, 0x97, 0x94, 0xa5, 0x2a, 0x7c, 0x31, 0x2f, 0x1a, 0x15, 0x2f, 0xf3, 0x2a, 0x7e,
	0xb1, 0x00, 0xe8, 0x2e, 0xdf, 0x03, 0x08, 0x29, 0x35, 0x6a, 0x6b, 0x44, 0xc3, 0x17, 0x94, 0xbe,
	0x22, 0x61, 0x23, 0x81, 0x28, 0xb6, 0x07, 0x25, 0xf9, 0x75, 0xdc, 0xe8, 0x58, 0x87, 0x8d, 0xe2,
	0x39, 0x8e, 0xe6, 0xa9, 0x99, 0x10, 0x0d, 0x4f, 0x2b, 0xd7, 0x1e, 0x05, 0xf6, 0x9e, 0xdf, 0x44,
	0x21, 0xa0, 0x35, 0x11, 0xf6, 0x19, 0x4e, 0x9d, 0xda, 0xf5, 0x46, 0x1e, 0x95, 0x5b, 0x52, 0xe6,
	0x11, 0x26, 0x29, 0x5c, 0xab, 0x53, 0x02, 0x95, 0xac, 0x05, 0xf2, 0xbb, 0xf8, 0x6b, 0x48, 0xe4,
	0x01, 0x43, 0xdc, 0x77, 0xf2, 0x18, 0xbf, 0x8b, 0x71, 0x22, 0x0f, 0xb8, 0xc9, 0xe9, 0xdf, 0xf3,
	0xe5, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x68, 0xc3, 0x61, 0xbe, 0x52, 0x03, 0x00, 0x00,
}
