// Code generated by protoc-gen-go. DO NOT EDIT.
// source: safeguard.proto

package geiqin_srv_ord_private

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Safeguard struct {
	Id                   int64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	OrderId              int64                   `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id"`
	Type                 string                  `protobuf:"bytes,3,opt,name=type,proto3" json:"type"`
	SafeguardSn          string                  `protobuf:"bytes,4,opt,name=safeguard_sn,json=safeguardSn,proto3" json:"safeguard_sn"`
	CustomerId           int64                   `protobuf:"varint,5,opt,name=customer_id,json=customerId,proto3" json:"customer_id"`
	ExchangeDeliveryId   int64                   `protobuf:"varint,6,opt,name=exchange_delivery_id,json=exchangeDeliveryId,proto3" json:"exchange_delivery_id"`
	ExpressName          string                  `protobuf:"bytes,7,opt,name=express_name,json=expressName,proto3" json:"express_name"`
	ExpressNo            string                  `protobuf:"bytes,8,opt,name=express_no,json=expressNo,proto3" json:"express_no"`
	ExpressCode          string                  `protobuf:"bytes,9,opt,name=express_code,json=expressCode,proto3" json:"express_code"`
	Mobile               string                  `protobuf:"bytes,10,opt,name=mobile,proto3" json:"mobile"`
	Refunded             bool                    `protobuf:"varint,11,opt,name=refunded,proto3" json:"refunded"`
	RefundFee            float32                 `protobuf:"fixed32,12,opt,name=refund_fee,json=refundFee,proto3" json:"refund_fee"`
	RefundMethod         string                  `protobuf:"bytes,13,opt,name=refund_method,json=refundMethod,proto3" json:"refund_method"`
	CheckStatus          string                  `protobuf:"bytes,142,opt,name=check_status,json=checkStatus,proto3" json:"check_status"`
	Status               string                  `protobuf:"bytes,15,opt,name=status,proto3" json:"status"`
	Reason               string                  `protobuf:"bytes,16,opt,name=reason,proto3" json:"reason"`
	Description          string                  `protobuf:"bytes,17,opt,name=description,proto3" json:"description"`
	OpId                 int64                   `protobuf:"varint,18,opt,name=op_id,json=opId,proto3" json:"op_id"`
	OpName               string                  `protobuf:"bytes,19,opt,name=op_name,json=opName,proto3" json:"op_name"`
	Memo                 string                  `protobuf:"bytes,20,opt,name=memo,proto3" json:"memo"`
	GoodsStatus          string                  `protobuf:"bytes,21,opt,name=goods_status,json=goodsStatus,proto3" json:"goods_status"`
	RefundedAt           string                  `protobuf:"bytes,22,opt,name=refunded_at,json=refundedAt,proto3" json:"refunded_at"`
	Metadata             string                  `protobuf:"bytes,23,opt,name=metadata,proto3" json:"metadata"`
	CheckedAt            string                  `protobuf:"bytes,24,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at"`
	CreatedAt            string                  `protobuf:"bytes,25,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt            string                  `protobuf:"bytes,26,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	Details              []*SafeguardDetail      `protobuf:"bytes,27,rep,name=details,proto3" json:"details"`
	Images               []*SafeguardImage       `protobuf:"bytes,28,rep,name=images,proto3" json:"images"`
	Address              *SafeguardAddress       `protobuf:"bytes,29,opt,name=address,proto3" json:"address"`
	ReturnExpress        *SafeguardReturnExpress `protobuf:"bytes,30,opt,name=return_express,json=returnExpress,proto3" json:"return_express"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Safeguard) Reset()         { *m = Safeguard{} }
func (m *Safeguard) String() string { return proto.CompactTextString(m) }
func (*Safeguard) ProtoMessage()    {}
func (*Safeguard) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3d93130ef4c1d08, []int{0}
}

func (m *Safeguard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Safeguard.Unmarshal(m, b)
}
func (m *Safeguard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Safeguard.Marshal(b, m, deterministic)
}
func (m *Safeguard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Safeguard.Merge(m, src)
}
func (m *Safeguard) XXX_Size() int {
	return xxx_messageInfo_Safeguard.Size(m)
}
func (m *Safeguard) XXX_DiscardUnknown() {
	xxx_messageInfo_Safeguard.DiscardUnknown(m)
}

var xxx_messageInfo_Safeguard proto.InternalMessageInfo

func (m *Safeguard) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Safeguard) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *Safeguard) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Safeguard) GetSafeguardSn() string {
	if m != nil {
		return m.SafeguardSn
	}
	return ""
}

func (m *Safeguard) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *Safeguard) GetExchangeDeliveryId() int64 {
	if m != nil {
		return m.ExchangeDeliveryId
	}
	return 0
}

func (m *Safeguard) GetExpressName() string {
	if m != nil {
		return m.ExpressName
	}
	return ""
}

func (m *Safeguard) GetExpressNo() string {
	if m != nil {
		return m.ExpressNo
	}
	return ""
}

func (m *Safeguard) GetExpressCode() string {
	if m != nil {
		return m.ExpressCode
	}
	return ""
}

func (m *Safeguard) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *Safeguard) GetRefunded() bool {
	if m != nil {
		return m.Refunded
	}
	return false
}

func (m *Safeguard) GetRefundFee() float32 {
	if m != nil {
		return m.RefundFee
	}
	return 0
}

func (m *Safeguard) GetRefundMethod() string {
	if m != nil {
		return m.RefundMethod
	}
	return ""
}

func (m *Safeguard) GetCheckStatus() string {
	if m != nil {
		return m.CheckStatus
	}
	return ""
}

func (m *Safeguard) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Safeguard) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Safeguard) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Safeguard) GetOpId() int64 {
	if m != nil {
		return m.OpId
	}
	return 0
}

func (m *Safeguard) GetOpName() string {
	if m != nil {
		return m.OpName
	}
	return ""
}

func (m *Safeguard) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *Safeguard) GetGoodsStatus() string {
	if m != nil {
		return m.GoodsStatus
	}
	return ""
}

func (m *Safeguard) GetRefundedAt() string {
	if m != nil {
		return m.RefundedAt
	}
	return ""
}

func (m *Safeguard) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

func (m *Safeguard) GetCheckedAt() string {
	if m != nil {
		return m.CheckedAt
	}
	return ""
}

func (m *Safeguard) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Safeguard) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Safeguard) GetDetails() []*SafeguardDetail {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *Safeguard) GetImages() []*SafeguardImage {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *Safeguard) GetAddress() *SafeguardAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Safeguard) GetReturnExpress() *SafeguardReturnExpress {
	if m != nil {
		return m.ReturnExpress
	}
	return nil
}

type SafeguardDetail struct {
	Id                   int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	SafeguardId          int64        `protobuf:"varint,2,opt,name=safeguard_id,json=safeguardId,proto3" json:"safeguard_id"`
	OrderDetailId        int64        `protobuf:"varint,3,opt,name=order_detail_id,json=orderDetailId,proto3" json:"order_detail_id"`
	ItemId               int64        `protobuf:"varint,4,opt,name=item_id,json=itemId,proto3" json:"item_id"`
	SkuId                int64        `protobuf:"varint,5,opt,name=sku_id,json=skuId,proto3" json:"sku_id"`
	Num                  int32        `protobuf:"varint,6,opt,name=num,proto3" json:"num"`
	Detail               *OrderDetail `protobuf:"bytes,7,opt,name=detail,proto3" json:"detail"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SafeguardDetail) Reset()         { *m = SafeguardDetail{} }
func (m *SafeguardDetail) String() string { return proto.CompactTextString(m) }
func (*SafeguardDetail) ProtoMessage()    {}
func (*SafeguardDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3d93130ef4c1d08, []int{1}
}

func (m *SafeguardDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SafeguardDetail.Unmarshal(m, b)
}
func (m *SafeguardDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SafeguardDetail.Marshal(b, m, deterministic)
}
func (m *SafeguardDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SafeguardDetail.Merge(m, src)
}
func (m *SafeguardDetail) XXX_Size() int {
	return xxx_messageInfo_SafeguardDetail.Size(m)
}
func (m *SafeguardDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_SafeguardDetail.DiscardUnknown(m)
}

var xxx_messageInfo_SafeguardDetail proto.InternalMessageInfo

func (m *SafeguardDetail) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SafeguardDetail) GetSafeguardId() int64 {
	if m != nil {
		return m.SafeguardId
	}
	return 0
}

func (m *SafeguardDetail) GetOrderDetailId() int64 {
	if m != nil {
		return m.OrderDetailId
	}
	return 0
}

func (m *SafeguardDetail) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *SafeguardDetail) GetSkuId() int64 {
	if m != nil {
		return m.SkuId
	}
	return 0
}

func (m *SafeguardDetail) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *SafeguardDetail) GetDetail() *OrderDetail {
	if m != nil {
		return m.Detail
	}
	return nil
}

type SafeguardImage struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	SafeguardId          int64    `protobuf:"varint,2,opt,name=safeguard_id,json=safeguardId,proto3" json:"safeguard_id"`
	ImageId              int64    `protobuf:"varint,3,opt,name=image_id,json=imageId,proto3" json:"image_id"`
	ImageUrl             string   `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SafeguardImage) Reset()         { *m = SafeguardImage{} }
func (m *SafeguardImage) String() string { return proto.CompactTextString(m) }
func (*SafeguardImage) ProtoMessage()    {}
func (*SafeguardImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3d93130ef4c1d08, []int{2}
}

func (m *SafeguardImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SafeguardImage.Unmarshal(m, b)
}
func (m *SafeguardImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SafeguardImage.Marshal(b, m, deterministic)
}
func (m *SafeguardImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SafeguardImage.Merge(m, src)
}
func (m *SafeguardImage) XXX_Size() int {
	return xxx_messageInfo_SafeguardImage.Size(m)
}
func (m *SafeguardImage) XXX_DiscardUnknown() {
	xxx_messageInfo_SafeguardImage.DiscardUnknown(m)
}

var xxx_messageInfo_SafeguardImage proto.InternalMessageInfo

func (m *SafeguardImage) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SafeguardImage) GetSafeguardId() int64 {
	if m != nil {
		return m.SafeguardId
	}
	return 0
}

func (m *SafeguardImage) GetImageId() int64 {
	if m != nil {
		return m.ImageId
	}
	return 0
}

func (m *SafeguardImage) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

// 维权收货人地址
type SafeguardAddress struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	AreaId               int64     `protobuf:"varint,2,opt,name=area_id,json=areaId,proto3" json:"area_id"`
	Addr                 string    `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr"`
	Mobile               string    `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile"`
	Area                 *AreaInfo `protobuf:"bytes,5,opt,name=area,proto3" json:"area"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SafeguardAddress) Reset()         { *m = SafeguardAddress{} }
func (m *SafeguardAddress) String() string { return proto.CompactTextString(m) }
func (*SafeguardAddress) ProtoMessage()    {}
func (*SafeguardAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3d93130ef4c1d08, []int{3}
}

func (m *SafeguardAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SafeguardAddress.Unmarshal(m, b)
}
func (m *SafeguardAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SafeguardAddress.Marshal(b, m, deterministic)
}
func (m *SafeguardAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SafeguardAddress.Merge(m, src)
}
func (m *SafeguardAddress) XXX_Size() int {
	return xxx_messageInfo_SafeguardAddress.Size(m)
}
func (m *SafeguardAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_SafeguardAddress.DiscardUnknown(m)
}

var xxx_messageInfo_SafeguardAddress proto.InternalMessageInfo

func (m *SafeguardAddress) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SafeguardAddress) GetAreaId() int64 {
	if m != nil {
		return m.AreaId
	}
	return 0
}

func (m *SafeguardAddress) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *SafeguardAddress) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *SafeguardAddress) GetArea() *AreaInfo {
	if m != nil {
		return m.Area
	}
	return nil
}

// 买家退货填写的退货物流信息
type SafeguardReturnExpress struct {
	ExpressName          string            `protobuf:"bytes,1,opt,name=express_name,json=expressName,proto3" json:"express_name"`
	ExpressNo            string            `protobuf:"bytes,2,opt,name=express_no,json=expressNo,proto3" json:"express_no"`
	ExpressCode          string            `protobuf:"bytes,3,opt,name=express_code,json=expressCode,proto3" json:"express_code"`
	Mobile               string            `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile"`
	Images               []*SafeguardImage `protobuf:"bytes,5,rep,name=images,proto3" json:"images"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SafeguardReturnExpress) Reset()         { *m = SafeguardReturnExpress{} }
func (m *SafeguardReturnExpress) String() string { return proto.CompactTextString(m) }
func (*SafeguardReturnExpress) ProtoMessage()    {}
func (*SafeguardReturnExpress) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3d93130ef4c1d08, []int{4}
}

func (m *SafeguardReturnExpress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SafeguardReturnExpress.Unmarshal(m, b)
}
func (m *SafeguardReturnExpress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SafeguardReturnExpress.Marshal(b, m, deterministic)
}
func (m *SafeguardReturnExpress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SafeguardReturnExpress.Merge(m, src)
}
func (m *SafeguardReturnExpress) XXX_Size() int {
	return xxx_messageInfo_SafeguardReturnExpress.Size(m)
}
func (m *SafeguardReturnExpress) XXX_DiscardUnknown() {
	xxx_messageInfo_SafeguardReturnExpress.DiscardUnknown(m)
}

var xxx_messageInfo_SafeguardReturnExpress proto.InternalMessageInfo

func (m *SafeguardReturnExpress) GetExpressName() string {
	if m != nil {
		return m.ExpressName
	}
	return ""
}

func (m *SafeguardReturnExpress) GetExpressNo() string {
	if m != nil {
		return m.ExpressNo
	}
	return ""
}

func (m *SafeguardReturnExpress) GetExpressCode() string {
	if m != nil {
		return m.ExpressCode
	}
	return ""
}

func (m *SafeguardReturnExpress) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *SafeguardReturnExpress) GetImages() []*SafeguardImage {
	if m != nil {
		return m.Images
	}
	return nil
}

type SafeguardMetadata struct {
	Address              *SafeguardAddress       `protobuf:"bytes,1,opt,name=address,proto3" json:"address"`
	ReturnExpress        *SafeguardReturnExpress `protobuf:"bytes,2,opt,name=return_express,json=returnExpress,proto3" json:"return_express"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SafeguardMetadata) Reset()         { *m = SafeguardMetadata{} }
func (m *SafeguardMetadata) String() string { return proto.CompactTextString(m) }
func (*SafeguardMetadata) ProtoMessage()    {}
func (*SafeguardMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3d93130ef4c1d08, []int{5}
}

func (m *SafeguardMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SafeguardMetadata.Unmarshal(m, b)
}
func (m *SafeguardMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SafeguardMetadata.Marshal(b, m, deterministic)
}
func (m *SafeguardMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SafeguardMetadata.Merge(m, src)
}
func (m *SafeguardMetadata) XXX_Size() int {
	return xxx_messageInfo_SafeguardMetadata.Size(m)
}
func (m *SafeguardMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_SafeguardMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_SafeguardMetadata proto.InternalMessageInfo

func (m *SafeguardMetadata) GetAddress() *SafeguardAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *SafeguardMetadata) GetReturnExpress() *SafeguardReturnExpress {
	if m != nil {
		return m.ReturnExpress
	}
	return nil
}

type SafeguardWhere struct {
	Paged                int32    `protobuf:"varint,1,opt,name=paged,proto3" json:"paged"`
	PageSize             int32    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size"`
	Sorting              string   `protobuf:"bytes,3,opt,name=sorting,proto3" json:"sorting"`
	Id                   int64    `protobuf:"varint,4,opt,name=id,proto3" json:"id"`
	Ids                  []int64  `protobuf:"varint,5,rep,packed,name=ids,proto3" json:"ids"`
	OrderId              int64    `protobuf:"varint,6,opt,name=order_id,json=orderId,proto3" json:"order_id"`
	CustomerId           int64    `protobuf:"varint,7,opt,name=customer_id,json=customerId,proto3" json:"customer_id"`
	Type                 string   `protobuf:"bytes,8,opt,name=type,proto3" json:"type"`
	KeywordsType         string   `protobuf:"bytes,9,opt,name=keywords_type,json=keywordsType,proto3" json:"keywords_type"`
	Keywords             string   `protobuf:"bytes,10,opt,name=keywords,proto3" json:"keywords"`
	OrderDetailIds       []int64  `protobuf:"varint,11,rep,packed,name=order_detail_ids,json=orderDetailIds,proto3" json:"order_detail_ids"`
	Status               string   `protobuf:"bytes,12,opt,name=status,proto3" json:"status"`
	SafeguardSn          string   `protobuf:"bytes,13,opt,name=safeguard_sn,json=safeguardSn,proto3" json:"safeguard_sn"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SafeguardWhere) Reset()         { *m = SafeguardWhere{} }
func (m *SafeguardWhere) String() string { return proto.CompactTextString(m) }
func (*SafeguardWhere) ProtoMessage()    {}
func (*SafeguardWhere) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3d93130ef4c1d08, []int{6}
}

func (m *SafeguardWhere) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SafeguardWhere.Unmarshal(m, b)
}
func (m *SafeguardWhere) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SafeguardWhere.Marshal(b, m, deterministic)
}
func (m *SafeguardWhere) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SafeguardWhere.Merge(m, src)
}
func (m *SafeguardWhere) XXX_Size() int {
	return xxx_messageInfo_SafeguardWhere.Size(m)
}
func (m *SafeguardWhere) XXX_DiscardUnknown() {
	xxx_messageInfo_SafeguardWhere.DiscardUnknown(m)
}

var xxx_messageInfo_SafeguardWhere proto.InternalMessageInfo

func (m *SafeguardWhere) GetPaged() int32 {
	if m != nil {
		return m.Paged
	}
	return 0
}

func (m *SafeguardWhere) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *SafeguardWhere) GetSorting() string {
	if m != nil {
		return m.Sorting
	}
	return ""
}

func (m *SafeguardWhere) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SafeguardWhere) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *SafeguardWhere) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *SafeguardWhere) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *SafeguardWhere) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SafeguardWhere) GetKeywordsType() string {
	if m != nil {
		return m.KeywordsType
	}
	return ""
}

func (m *SafeguardWhere) GetKeywords() string {
	if m != nil {
		return m.Keywords
	}
	return ""
}

func (m *SafeguardWhere) GetOrderDetailIds() []int64 {
	if m != nil {
		return m.OrderDetailIds
	}
	return nil
}

func (m *SafeguardWhere) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *SafeguardWhere) GetSafeguardSn() string {
	if m != nil {
		return m.SafeguardSn
	}
	return ""
}

type SafeguardType struct {
	OrderId              int64             `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id"`
	IsRefund             bool              `protobuf:"varint,2,opt,name=is_refund,json=isRefund,proto3" json:"is_refund"`
	IsReturn             bool              `protobuf:"varint,3,opt,name=is_return,json=isReturn,proto3" json:"is_return"`
	IsExchange           bool              `protobuf:"varint,4,opt,name=is_exchange,json=isExchange,proto3" json:"is_exchange"`
	IsRepair             bool              `protobuf:"varint,5,opt,name=is_repair,json=isRepair,proto3" json:"is_repair"`
	MaxRefundPrice       float32           `protobuf:"fixed32,6,opt,name=max_refund_price,json=maxRefundPrice,proto3" json:"max_refund_price"`
	ExpressFee           float32           `protobuf:"fixed32,7,opt,name=express_fee,json=expressFee,proto3" json:"express_fee"`
	Address              *SafeguardAddress `protobuf:"bytes,8,opt,name=address,proto3" json:"address"`
	Details              []*OrderDetail    `protobuf:"bytes,9,rep,name=details,proto3" json:"details"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SafeguardType) Reset()         { *m = SafeguardType{} }
func (m *SafeguardType) String() string { return proto.CompactTextString(m) }
func (*SafeguardType) ProtoMessage()    {}
func (*SafeguardType) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3d93130ef4c1d08, []int{7}
}

func (m *SafeguardType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SafeguardType.Unmarshal(m, b)
}
func (m *SafeguardType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SafeguardType.Marshal(b, m, deterministic)
}
func (m *SafeguardType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SafeguardType.Merge(m, src)
}
func (m *SafeguardType) XXX_Size() int {
	return xxx_messageInfo_SafeguardType.Size(m)
}
func (m *SafeguardType) XXX_DiscardUnknown() {
	xxx_messageInfo_SafeguardType.DiscardUnknown(m)
}

var xxx_messageInfo_SafeguardType proto.InternalMessageInfo

func (m *SafeguardType) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *SafeguardType) GetIsRefund() bool {
	if m != nil {
		return m.IsRefund
	}
	return false
}

func (m *SafeguardType) GetIsReturn() bool {
	if m != nil {
		return m.IsReturn
	}
	return false
}

func (m *SafeguardType) GetIsExchange() bool {
	if m != nil {
		return m.IsExchange
	}
	return false
}

func (m *SafeguardType) GetIsRepair() bool {
	if m != nil {
		return m.IsRepair
	}
	return false
}

func (m *SafeguardType) GetMaxRefundPrice() float32 {
	if m != nil {
		return m.MaxRefundPrice
	}
	return 0
}

func (m *SafeguardType) GetExpressFee() float32 {
	if m != nil {
		return m.ExpressFee
	}
	return 0
}

func (m *SafeguardType) GetAddress() *SafeguardAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *SafeguardType) GetDetails() []*OrderDetail {
	if m != nil {
		return m.Details
	}
	return nil
}

type SafeguardResponse struct {
	Entity               *Safeguard   `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity"`
	Pager                *Pager       `protobuf:"bytes,2,opt,name=pager,proto3" json:"pager"`
	Items                []*Safeguard `protobuf:"bytes,3,rep,name=items,proto3" json:"items"`
	Error                *Error       `protobuf:"bytes,4,opt,name=error,proto3" json:"error"`
	Info                 *Info        `protobuf:"bytes,5,opt,name=info,proto3" json:"info"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SafeguardResponse) Reset()         { *m = SafeguardResponse{} }
func (m *SafeguardResponse) String() string { return proto.CompactTextString(m) }
func (*SafeguardResponse) ProtoMessage()    {}
func (*SafeguardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3d93130ef4c1d08, []int{8}
}

func (m *SafeguardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SafeguardResponse.Unmarshal(m, b)
}
func (m *SafeguardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SafeguardResponse.Marshal(b, m, deterministic)
}
func (m *SafeguardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SafeguardResponse.Merge(m, src)
}
func (m *SafeguardResponse) XXX_Size() int {
	return xxx_messageInfo_SafeguardResponse.Size(m)
}
func (m *SafeguardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SafeguardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SafeguardResponse proto.InternalMessageInfo

func (m *SafeguardResponse) GetEntity() *Safeguard {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *SafeguardResponse) GetPager() *Pager {
	if m != nil {
		return m.Pager
	}
	return nil
}

func (m *SafeguardResponse) GetItems() []*Safeguard {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *SafeguardResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *SafeguardResponse) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

type SafeguardTypeResponse struct {
	Entity               *SafeguardType   `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity"`
	Pager                *Pager           `protobuf:"bytes,2,opt,name=pager,proto3" json:"pager"`
	Items                []*SafeguardType `protobuf:"bytes,3,rep,name=items,proto3" json:"items"`
	Error                *Error           `protobuf:"bytes,4,opt,name=error,proto3" json:"error"`
	Info                 *Info            `protobuf:"bytes,5,opt,name=info,proto3" json:"info"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SafeguardTypeResponse) Reset()         { *m = SafeguardTypeResponse{} }
func (m *SafeguardTypeResponse) String() string { return proto.CompactTextString(m) }
func (*SafeguardTypeResponse) ProtoMessage()    {}
func (*SafeguardTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3d93130ef4c1d08, []int{9}
}

func (m *SafeguardTypeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SafeguardTypeResponse.Unmarshal(m, b)
}
func (m *SafeguardTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SafeguardTypeResponse.Marshal(b, m, deterministic)
}
func (m *SafeguardTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SafeguardTypeResponse.Merge(m, src)
}
func (m *SafeguardTypeResponse) XXX_Size() int {
	return xxx_messageInfo_SafeguardTypeResponse.Size(m)
}
func (m *SafeguardTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SafeguardTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SafeguardTypeResponse proto.InternalMessageInfo

func (m *SafeguardTypeResponse) GetEntity() *SafeguardType {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *SafeguardTypeResponse) GetPager() *Pager {
	if m != nil {
		return m.Pager
	}
	return nil
}

func (m *SafeguardTypeResponse) GetItems() []*SafeguardType {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *SafeguardTypeResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *SafeguardTypeResponse) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*Safeguard)(nil), "geiqin.srv.ord.private.Safeguard")
	proto.RegisterType((*SafeguardDetail)(nil), "geiqin.srv.ord.private.SafeguardDetail")
	proto.RegisterType((*SafeguardImage)(nil), "geiqin.srv.ord.private.SafeguardImage")
	proto.RegisterType((*SafeguardAddress)(nil), "geiqin.srv.ord.private.SafeguardAddress")
	proto.RegisterType((*SafeguardReturnExpress)(nil), "geiqin.srv.ord.private.SafeguardReturnExpress")
	proto.RegisterType((*SafeguardMetadata)(nil), "geiqin.srv.ord.private.SafeguardMetadata")
	proto.RegisterType((*SafeguardWhere)(nil), "geiqin.srv.ord.private.SafeguardWhere")
	proto.RegisterType((*SafeguardType)(nil), "geiqin.srv.ord.private.SafeguardType")
	proto.RegisterType((*SafeguardResponse)(nil), "geiqin.srv.ord.private.SafeguardResponse")
	proto.RegisterType((*SafeguardTypeResponse)(nil), "geiqin.srv.ord.private.SafeguardTypeResponse")
}

func init() { proto.RegisterFile("safeguard.proto", fileDescriptor_a3d93130ef4c1d08) }

var fileDescriptor_a3d93130ef4c1d08 = []byte{
	// 1380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0x4d, 0x6f, 0x1b, 0xc5,
	0x1b, 0xff, 0xaf, 0x5f, 0x37, 0x8f, 0x5f, 0x92, 0x4e, 0xdb, 0x74, 0x9b, 0xb6, 0xff, 0xba, 0xae,
	0x28, 0xe6, 0x40, 0x54, 0xa5, 0x48, 0x08, 0x55, 0x45, 0x32, 0x6d, 0xa8, 0x7c, 0x28, 0x54, 0x1b,
	0x2a, 0xca, 0x01, 0x2d, 0x5b, 0xcf, 0xd8, 0x19, 0xc5, 0xbb, 0xb3, 0xcc, 0xac, 0x43, 0x5c, 0xbe,
	0x03, 0xdf, 0x01, 0x71, 0x07, 0x84, 0xc4, 0x47, 0xe1, 0x53, 0x70, 0xe1, 0xc2, 0x1d, 0xcd, 0x33,
	0xb3, 0xeb, 0x75, 0xd2, 0xd4, 0xa1, 0xc4, 0x9c, 0xb8, 0xcd, 0xf3, 0x3e, 0xfb, 0x9b, 0xe7, 0xf9,
	0xcd, 0x68, 0x61, 0x5d, 0x85, 0x23, 0x36, 0x9e, 0x86, 0x92, 0x6e, 0x27, 0x52, 0xa4, 0x82, 0x6c,
	0x8e, 0x19, 0xff, 0x9a, 0xc7, 0xdb, 0x4a, 0x1e, 0x6e, 0x0b, 0xd4, 0xf2, 0xc3, 0x30, 0x65, 0x5b,
	0xcd, 0xa1, 0x88, 0x22, 0x11, 0x1b, 0xaf, 0xad, 0x0b, 0x42, 0x52, 0x26, 0x1f, 0xb1, 0x34, 0xe4,
	0x13, 0xab, 0x6a, 0x87, 0x92, 0x85, 0x83, 0x78, 0x24, 0x8c, 0xdc, 0xfd, 0xd9, 0x85, 0xb5, 0xbd,
	0x2c, 0x39, 0x69, 0x43, 0x89, 0x53, 0xcf, 0xe9, 0x38, 0xbd, 0xb2, 0x5f, 0xe2, 0x94, 0x5c, 0x05,
	0x17, 0x53, 0x04, 0x9c, 0x7a, 0x25, 0xd4, 0xd6, 0x51, 0x1e, 0x50, 0x42, 0xa0, 0x92, 0xce, 0x12,
	0xe6, 0x95, 0x3b, 0x4e, 0x6f, 0xcd, 0xc7, 0x35, 0xb9, 0x05, 0xcd, 0x7c, 0xa3, 0x81, 0x8a, 0xbd,
	0x0a, 0xda, 0x1a, 0xb9, 0x6e, 0x2f, 0x26, 0x37, 0xa1, 0x31, 0x9c, 0xaa, 0x54, 0x44, 0x26, 0x69,
	0x15, 0x93, 0x42, 0xa6, 0x1a, 0x50, 0x72, 0x17, 0x2e, 0xb1, 0xa3, 0xe1, 0x7e, 0x18, 0x8f, 0x59,
	0x40, 0xd9, 0x84, 0x1f, 0x32, 0x39, 0xd3, 0x9e, 0x35, 0xf4, 0x24, 0x99, 0xed, 0x91, 0x35, 0x0d,
	0xa8, 0xae, 0xca, 0x8e, 0x12, 0xc9, 0x94, 0x0a, 0xe2, 0x30, 0x62, 0x5e, 0xdd, 0x54, 0xb5, 0xba,
	0x4f, 0xc2, 0x88, 0x91, 0x1b, 0x00, 0xb9, 0x8b, 0xf0, 0x5c, 0x74, 0x58, 0xcb, 0x1c, 0x44, 0x31,
	0xc3, 0x50, 0x50, 0xe6, 0xad, 0x2d, 0x64, 0x78, 0x28, 0x28, 0x23, 0x9b, 0x50, 0x8b, 0xc4, 0x0b,
	0x3e, 0x61, 0x1e, 0xa0, 0xd1, 0x4a, 0x64, 0x0b, 0x5c, 0xc9, 0x46, 0xd3, 0x98, 0x32, 0xea, 0x35,
	0x3a, 0x4e, 0xcf, 0xf5, 0x73, 0x59, 0x57, 0x35, 0xeb, 0x60, 0xc4, 0x98, 0xd7, 0xec, 0x38, 0xbd,
	0x92, 0xbf, 0x66, 0x34, 0x1f, 0x33, 0x46, 0x6e, 0x43, 0xcb, 0x9a, 0x23, 0x96, 0xee, 0x0b, 0xea,
	0xb5, 0x30, 0x73, 0xd3, 0x28, 0x9f, 0xa0, 0x8e, 0x74, 0xa1, 0x39, 0xdc, 0x67, 0xc3, 0x83, 0x40,
	0xa5, 0x61, 0x3a, 0x55, 0xde, 0x77, 0x8e, 0xd9, 0x1b, 0x2a, 0xf7, 0x50, 0xa7, 0xf7, 0x66, 0xad,
	0xeb, 0x66, 0x6f, 0x2a, 0xd7, 0x4b, 0x16, 0x2a, 0x11, 0x7b, 0x1b, 0x46, 0x6f, 0x24, 0xd2, 0x81,
	0x06, 0x65, 0x6a, 0x28, 0x79, 0x92, 0x72, 0x11, 0x7b, 0x17, 0x4c, 0xc6, 0x82, 0x8a, 0x5c, 0x84,
	0xaa, 0x48, 0x34, 0xea, 0x04, 0x51, 0xaf, 0x88, 0x64, 0x40, 0xc9, 0x15, 0xa8, 0x8b, 0xc4, 0x40,
	0x7c, 0xd1, 0xe4, 0x13, 0x09, 0xa2, 0x4b, 0xa0, 0x12, 0xb1, 0x48, 0x78, 0x97, 0x4c, 0x2b, 0xe8,
	0xb5, 0x86, 0x74, 0x2c, 0x04, 0x55, 0xd9, 0xbe, 0x2f, 0x9b, 0x22, 0xa8, 0xb3, 0xdb, 0xbe, 0x09,
	0x8d, 0x0c, 0xaa, 0x20, 0x4c, 0xbd, 0x4d, 0xf4, 0x80, 0x4c, 0xd5, 0x4f, 0x35, 0xb6, 0x11, 0x4b,
	0x43, 0x1a, 0xa6, 0xa1, 0x77, 0x05, 0xad, 0xb9, 0xac, 0xb1, 0x45, 0x08, 0x4c, 0xac, 0x67, 0x4e,
	0xd4, 0x6a, 0xfa, 0x29, 0x9a, 0x25, 0x0b, 0x53, 0x63, 0xbe, 0x6a, 0xcd, 0x46, 0x63, 0xcc, 0xd3,
	0x84, 0x66, 0xe6, 0x2d, 0x63, 0xb6, 0x9a, 0x7e, 0x4a, 0xfa, 0x50, 0xa7, 0x38, 0x34, 0xca, 0xbb,
	0xd6, 0x29, 0xf7, 0x1a, 0x3b, 0x6f, 0x6f, 0xbf, 0x7a, 0xde, 0xb6, 0xf3, 0xd1, 0x31, 0x43, 0xe6,
	0x67, 0x71, 0xe4, 0x43, 0xa8, 0xf1, 0x28, 0x1c, 0x33, 0xe5, 0x5d, 0xc7, 0x0c, 0x77, 0x96, 0x66,
	0x18, 0x68, 0x77, 0xdf, 0x46, 0x91, 0x8f, 0xa0, 0x1e, 0x52, 0xaa, 0xdb, 0xcf, 0xbb, 0xd1, 0x71,
	0x7a, 0x8d, 0x9d, 0xde, 0xd2, 0x04, 0x7d, 0xe3, 0xef, 0x67, 0x81, 0xe4, 0x19, 0xb4, 0x25, 0x4b,
	0xa7, 0x32, 0x0e, 0x6c, 0x27, 0x7b, 0xff, 0xc7, 0x54, 0xdb, 0x4b, 0x53, 0xf9, 0x18, 0xb6, 0x6b,
	0xa2, 0xfc, 0x96, 0x2c, 0x8a, 0xdd, 0xdf, 0x1d, 0x58, 0x3f, 0xf6, 0xdd, 0x27, 0x88, 0x63, 0x81,
	0x09, 0x72, 0xf2, 0x98, 0x33, 0xc1, 0x80, 0x92, 0x3b, 0xb0, 0x6e, 0xb8, 0xc5, 0x40, 0xa6, 0xbd,
	0xca, 0xe8, 0xd5, 0x2a, 0xb0, 0x96, 0x69, 0x3b, 0x9e, 0xb2, 0x48, 0xdb, 0x2b, 0x68, 0xaf, 0x69,
	0x71, 0x40, 0xc9, 0x65, 0xa8, 0xa9, 0x83, 0xe9, 0x9c, 0x45, 0xaa, 0xea, 0x60, 0x3a, 0xa0, 0x64,
	0x03, 0xca, 0xf1, 0x34, 0x42, 0xbe, 0xa8, 0xfa, 0x7a, 0x49, 0xee, 0x43, 0xcd, 0xd4, 0x40, 0x6a,
	0x68, 0xec, 0xdc, 0x3e, 0xed, 0xfb, 0x3f, 0x9d, 0x17, 0xf6, 0x6d, 0x48, 0xf7, 0x5b, 0x68, 0x2f,
	0x1e, 0xd1, 0x9b, 0x7c, 0xeb, 0x55, 0x70, 0xf1, 0x5c, 0xe7, 0x1f, 0x59, 0x47, 0x79, 0x40, 0xc9,
	0x35, 0x58, 0x33, 0xa6, 0xa9, 0x9c, 0x58, 0xc2, 0x34, 0xbe, 0xcf, 0xe4, 0xa4, 0xfb, 0xbd, 0x03,
	0x1b, 0xc7, 0xcf, 0x57, 0x8f, 0x1b, 0x0e, 0xa1, 0x61, 0x02, 0x5c, 0x6b, 0x90, 0x34, 0xb1, 0xcf,
	0xcb, 0xd7, 0x90, 0xe7, 0x91, 0xa6, 0x75, 0x3b, 0x64, 0x34, 0xad, 0xd7, 0x05, 0x2e, 0xab, 0x2c,
	0x70, 0xd9, 0x7b, 0x50, 0xd1, 0x51, 0x08, 0x67, 0x63, 0xa7, 0x73, 0x1a, 0x4a, 0x7d, 0x7b, 0x83,
	0xf8, 0xe8, 0xdd, 0xfd, 0xcd, 0x81, 0xcd, 0x57, 0x37, 0xce, 0x09, 0x66, 0x76, 0x96, 0x31, 0x73,
	0x69, 0x19, 0x33, 0x97, 0x5f, 0xc7, 0xcc, 0x8b, 0x5f, 0x33, 0x9f, 0xc0, 0xea, 0x9b, 0x4c, 0x60,
	0xf7, 0x47, 0x07, 0x2e, 0xe4, 0xa6, 0x27, 0x19, 0xef, 0x14, 0xe6, 0xd2, 0x39, 0xbf, 0xb9, 0x2c,
	0x9d, 0xc7, 0x5c, 0xfe, 0x59, 0x2a, 0xb4, 0xea, 0xe7, 0xfb, 0x4c, 0x32, 0x72, 0x09, 0xaa, 0x49,
	0x38, 0x66, 0xa6, 0x5b, 0xab, 0xbe, 0x11, 0x74, 0xcb, 0xe9, 0x45, 0xa0, 0xf8, 0x4b, 0x86, 0xa5,
	0xab, 0xbe, 0xab, 0x15, 0x7b, 0xfc, 0x25, 0x23, 0x1e, 0xd4, 0x95, 0x90, 0x29, 0x8f, 0xc7, 0x16,
	0xec, 0x4c, 0xb4, 0x7d, 0x5f, 0xc9, 0xfb, 0x7e, 0x03, 0xca, 0x9c, 0x1a, 0x74, 0xcb, 0xbe, 0x5e,
	0x2e, 0x3c, 0x17, 0x6a, 0x8b, 0xcf, 0x85, 0x63, 0xf7, 0x7e, 0xfd, 0xc4, 0xbd, 0x9f, 0xbd, 0x27,
	0xdc, 0xc2, 0x7b, 0xe2, 0x36, 0xb4, 0x0e, 0xd8, 0xec, 0x1b, 0x21, 0xa9, 0x0a, 0xd0, 0x68, 0x2e,
	0xe6, 0x66, 0xa6, 0xfc, 0x4c, 0x3b, 0x6d, 0x81, 0x9b, 0xc9, 0xf6, 0x6e, 0xce, 0x65, 0xd2, 0x83,
	0x8d, 0x63, 0x1c, 0xa3, 0xbc, 0x06, 0xee, 0xb7, 0xbd, 0x40, 0x32, 0xc5, 0x3b, 0xb4, 0xb9, 0x70,
	0x87, 0x1e, 0x7f, 0xd2, 0xb4, 0x4e, 0x3c, 0x69, 0xba, 0x7f, 0x94, 0xa0, 0x95, 0xe3, 0x8e, 0x5b,
	0x2a, 0xe2, 0xe0, 0x2c, 0xe2, 0xa0, 0xc7, 0x5d, 0x05, 0xe6, 0x92, 0x43, 0xec, 0x5d, 0xdf, 0xe5,
	0xca, 0x47, 0x39, 0x37, 0xea, 0x53, 0x45, 0xf4, 0xad, 0x51, 0xcb, 0x1a, 0x41, 0xae, 0x82, 0xec,
	0xfd, 0x83, 0xe7, 0xe0, 0xfa, 0xc0, 0xd5, 0xae, 0xd5, 0xe4, 0xd1, 0x49, 0xc8, 0x25, 0xce, 0xb0,
	0x8d, 0xd6, 0xb2, 0x46, 0x22, 0x0a, 0x8f, 0x6c, 0xe1, 0x20, 0x91, 0x7c, 0xc8, 0xf0, 0x88, 0x4a,
	0x7e, 0x3b, 0x0a, 0x8f, 0x4c, 0xfd, 0xa7, 0x5a, 0xab, 0xeb, 0x64, 0x23, 0xa7, 0x9f, 0x2d, 0x75,
	0x74, 0xca, 0x86, 0x54, 0xbf, 0x5b, 0x0a, 0x23, 0xe0, 0xbe, 0xe9, 0x08, 0x3c, 0x98, 0xdf, 0xb0,
	0x6b, 0x38, 0x9d, 0x67, 0xe2, 0xe4, 0x2c, 0xa6, 0xfb, 0x43, 0xa9, 0x30, 0x9b, 0x3e, 0x53, 0x89,
	0x88, 0x15, 0x23, 0x1f, 0x40, 0x8d, 0xc5, 0x29, 0x4f, 0x67, 0x76, 0x34, 0x6f, 0x2d, 0x9f, 0x27,
	0x1b, 0x40, 0xee, 0x99, 0x41, 0x91, 0x76, 0x12, 0x6f, 0x9c, 0x16, 0xf9, 0x54, 0x3b, 0x99, 0x39,
	0x92, 0xe4, 0x7d, 0xa8, 0xea, 0xab, 0x48, 0x79, 0x65, 0xfc, 0x84, 0x33, 0x94, 0x33, 0xfe, 0xba,
	0x1a, 0x93, 0x52, 0x48, 0x3c, 0xc4, 0xd7, 0x54, 0xdb, 0xd5, 0x4e, 0xbe, 0xf1, 0x25, 0x77, 0xa1,
	0xc2, 0xe3, 0x91, 0xb0, 0xec, 0x7c, 0xfd, 0xb4, 0x18, 0xc3, 0xcc, 0xda, 0xb3, 0xfb, 0x53, 0x09,
	0x2e, 0x2f, 0x34, 0x66, 0x8e, 0xd4, 0x83, 0x63, 0x48, 0xbd, 0xb5, 0x74, 0xeb, 0x18, 0xfe, 0x8f,
	0xd0, 0xba, 0xbf, 0x88, 0xd6, 0x19, 0x4b, 0xfe, 0xab, 0x88, 0xed, 0xfc, 0xea, 0x02, 0x79, 0x32,
	0xcb, 0x77, 0xb0, 0xc7, 0xe4, 0xa1, 0x1e, 0x89, 0x2f, 0xa1, 0xd1, 0x4f, 0x92, 0xc9, 0xcc, 0x8e,
	0xe9, 0xf2, 0x83, 0xde, 0x7a, 0xe7, 0x0c, 0x54, 0x6e, 0xce, 0xa2, 0xfb, 0xbf, 0x42, 0x7a, 0x1c,
	0xf4, 0xf3, 0x4e, 0x1f, 0x40, 0x0b, 0xd3, 0xe7, 0x44, 0xb1, 0xba, 0xfd, 0x23, 0xd5, 0x9c, 0x77,
	0xfa, 0x17, 0x36, 0xfd, 0xc3, 0x30, 0x1e, 0xb2, 0x09, 0x59, 0x7e, 0x8f, 0xe3, 0xdd, 0xf7, 0x77,
	0x6b, 0xd4, 0x1f, 0xb3, 0x14, 0xc9, 0xfb, 0xac, 0xf9, 0xdf, 0x3d, 0x5b, 0x03, 0xcf, 0x6b, 0x8c,
	0xa0, 0xf1, 0x50, 0xc4, 0x23, 0x2e, 0xa3, 0xd5, 0xd6, 0xf9, 0x0a, 0xda, 0xbb, 0xd9, 0xfb, 0x08,
	0xcb, 0x9d, 0xfb, 0x89, 0x3c, 0x83, 0xf2, 0x63, 0x96, 0x9e, 0x7b, 0xda, 0x2f, 0xa0, 0xfe, 0x88,
	0xab, 0x64, 0x12, 0xce, 0x56, 0xd0, 0xa2, 0xb5, 0x3d, 0x16, 0xca, 0xe1, 0xfe, 0x4a, 0xda, 0x67,
	0xe7, 0x97, 0x4a, 0xe1, 0x9d, 0x9e, 0xb1, 0xc6, 0x73, 0xa8, 0xf5, 0xc7, 0x92, 0x31, 0xba, 0x0a,
	0xa0, 0x34, 0x15, 0xa9, 0x15, 0xa4, 0x7e, 0x0e, 0xb5, 0x15, 0xb1, 0xdc, 0x7f, 0x4d, 0xb3, 0x98,
	0xfe, 0x45, 0x0d, 0xff, 0xc0, 0xdd, 0xfb, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x57, 0x90, 0xab, 0x34,
	0xdd, 0x13, 0x00, 0x00,
}
