// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shipment.proto

package geiqin_srv_ord_private

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 下单的配送信息
type OrderShipment struct {
	Lng                  string        `protobuf:"bytes,1,opt,name=lng,proto3" json:"lng,omitempty"`
	Lat                  string        `protobuf:"bytes,2,opt,name=lat,proto3" json:"lat,omitempty"`
	IsFetch              bool          `protobuf:"varint,3,opt,name=is_fetch,json=isFetch,proto3" json:"is_fetch,omitempty"`
	IsDelivery           bool          `protobuf:"varint,4,opt,name=is_delivery,json=isDelivery,proto3" json:"is_delivery,omitempty"`
	IsExpress            bool          `protobuf:"varint,5,opt,name=is_express,json=isExpress,proto3" json:"is_express,omitempty"`
	Method               string        `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`
	FetchCount           int32         `protobuf:"varint,7,opt,name=fetch_count,json=fetchCount,proto3" json:"fetch_count,omitempty"`
	FetchLocationId      int64         `protobuf:"varint,8,opt,name=fetch_location_id,json=fetchLocationId,proto3" json:"fetch_location_id,omitempty"`
	FetchAt              string        `protobuf:"bytes,9,opt,name=fetch_at,json=fetchAt,proto3" json:"fetch_at,omitempty"`
	Deliverable          bool          `protobuf:"varint,10,opt,name=deliverable,proto3" json:"deliverable,omitempty"`
	DeliveryAt           string        `protobuf:"bytes,11,opt,name=delivery_at,json=deliveryAt,proto3" json:"delivery_at,omitempty"`
	ExpressFee           float32       `protobuf:"fixed32,12,opt,name=express_fee,json=expressFee,proto3" json:"express_fee,omitempty"`
	DeliveryFee          float32       `protobuf:"fixed32,13,opt,name=delivery_fee,json=deliveryFee,proto3" json:"delivery_fee,omitempty"`
	DeliveryInfo         *DeliveryInfo `protobuf:"bytes,14,opt,name=delivery_info,json=deliveryInfo,proto3" json:"delivery_info,omitempty"`
	FetchInfo            *FetchInfo    `protobuf:"bytes,15,opt,name=fetch_info,json=fetchInfo,proto3" json:"fetch_info,omitempty"`
	ExpressInfo          *ExpressInfo  `protobuf:"bytes,16,opt,name=express_info,json=expressInfo,proto3" json:"express_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *OrderShipment) Reset()         { *m = OrderShipment{} }
func (m *OrderShipment) String() string { return proto.CompactTextString(m) }
func (*OrderShipment) ProtoMessage()    {}
func (*OrderShipment) Descriptor() ([]byte, []int) {
	return fileDescriptor_832505ff9d8a41db, []int{0}
}

func (m *OrderShipment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderShipment.Unmarshal(m, b)
}
func (m *OrderShipment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderShipment.Marshal(b, m, deterministic)
}
func (m *OrderShipment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderShipment.Merge(m, src)
}
func (m *OrderShipment) XXX_Size() int {
	return xxx_messageInfo_OrderShipment.Size(m)
}
func (m *OrderShipment) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderShipment.DiscardUnknown(m)
}

var xxx_messageInfo_OrderShipment proto.InternalMessageInfo

func (m *OrderShipment) GetLng() string {
	if m != nil {
		return m.Lng
	}
	return ""
}

func (m *OrderShipment) GetLat() string {
	if m != nil {
		return m.Lat
	}
	return ""
}

func (m *OrderShipment) GetIsFetch() bool {
	if m != nil {
		return m.IsFetch
	}
	return false
}

func (m *OrderShipment) GetIsDelivery() bool {
	if m != nil {
		return m.IsDelivery
	}
	return false
}

func (m *OrderShipment) GetIsExpress() bool {
	if m != nil {
		return m.IsExpress
	}
	return false
}

func (m *OrderShipment) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *OrderShipment) GetFetchCount() int32 {
	if m != nil {
		return m.FetchCount
	}
	return 0
}

func (m *OrderShipment) GetFetchLocationId() int64 {
	if m != nil {
		return m.FetchLocationId
	}
	return 0
}

func (m *OrderShipment) GetFetchAt() string {
	if m != nil {
		return m.FetchAt
	}
	return ""
}

func (m *OrderShipment) GetDeliverable() bool {
	if m != nil {
		return m.Deliverable
	}
	return false
}

func (m *OrderShipment) GetDeliveryAt() string {
	if m != nil {
		return m.DeliveryAt
	}
	return ""
}

func (m *OrderShipment) GetExpressFee() float32 {
	if m != nil {
		return m.ExpressFee
	}
	return 0
}

func (m *OrderShipment) GetDeliveryFee() float32 {
	if m != nil {
		return m.DeliveryFee
	}
	return 0
}

func (m *OrderShipment) GetDeliveryInfo() *DeliveryInfo {
	if m != nil {
		return m.DeliveryInfo
	}
	return nil
}

func (m *OrderShipment) GetFetchInfo() *FetchInfo {
	if m != nil {
		return m.FetchInfo
	}
	return nil
}

func (m *OrderShipment) GetExpressInfo() *ExpressInfo {
	if m != nil {
		return m.ExpressInfo
	}
	return nil
}

// 上门自提信息
type FetchInfo struct {
	Id                   int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AreaId               int64     `protobuf:"varint,3,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	Addr                 string    `protobuf:"bytes,4,opt,name=addr,proto3" json:"addr,omitempty"`
	Lng                  string    `protobuf:"bytes,5,opt,name=lng,proto3" json:"lng,omitempty"`
	Lat                  string    `protobuf:"bytes,6,opt,name=lat,proto3" json:"lat,omitempty"`
	Tel                  string    `protobuf:"bytes,7,opt,name=tel,proto3" json:"tel,omitempty"`
	Mobile               string    `protobuf:"bytes,8,opt,name=mobile,proto3" json:"mobile,omitempty"`
	IsFetchTime          bool      `protobuf:"varint,9,opt,name=is_fetch_time,json=isFetchTime,proto3" json:"is_fetch_time,omitempty"`
	Distance             float32   `protobuf:"fixed32,10,opt,name=distance,proto3" json:"distance,omitempty"`
	Galleries            []string  `protobuf:"bytes,11,rep,name=galleries,proto3" json:"galleries,omitempty"`
	Area                 *AreaInfo `protobuf:"bytes,12,opt,name=area,proto3" json:"area,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FetchInfo) Reset()         { *m = FetchInfo{} }
func (m *FetchInfo) String() string { return proto.CompactTextString(m) }
func (*FetchInfo) ProtoMessage()    {}
func (*FetchInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_832505ff9d8a41db, []int{1}
}

func (m *FetchInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchInfo.Unmarshal(m, b)
}
func (m *FetchInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchInfo.Marshal(b, m, deterministic)
}
func (m *FetchInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchInfo.Merge(m, src)
}
func (m *FetchInfo) XXX_Size() int {
	return xxx_messageInfo_FetchInfo.Size(m)
}
func (m *FetchInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FetchInfo proto.InternalMessageInfo

func (m *FetchInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FetchInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FetchInfo) GetAreaId() int64 {
	if m != nil {
		return m.AreaId
	}
	return 0
}

func (m *FetchInfo) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *FetchInfo) GetLng() string {
	if m != nil {
		return m.Lng
	}
	return ""
}

func (m *FetchInfo) GetLat() string {
	if m != nil {
		return m.Lat
	}
	return ""
}

func (m *FetchInfo) GetTel() string {
	if m != nil {
		return m.Tel
	}
	return ""
}

func (m *FetchInfo) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *FetchInfo) GetIsFetchTime() bool {
	if m != nil {
		return m.IsFetchTime
	}
	return false
}

func (m *FetchInfo) GetDistance() float32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *FetchInfo) GetGalleries() []string {
	if m != nil {
		return m.Galleries
	}
	return nil
}

func (m *FetchInfo) GetArea() *AreaInfo {
	if m != nil {
		return m.Area
	}
	return nil
}

// 同城配送信息
type DeliveryInfo struct {
	LocationId           int64    `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Method               int32    `protobuf:"varint,2,opt,name=method,proto3" json:"method,omitempty"`
	Template             int32    `protobuf:"varint,3,opt,name=template,proto3" json:"template,omitempty"`
	RangeName            string   `protobuf:"bytes,4,opt,name=range_name,json=rangeName,proto3" json:"range_name,omitempty"`
	RangeContent         string   `protobuf:"bytes,5,opt,name=range_content,json=rangeContent,proto3" json:"range_content,omitempty"`
	RangeImageUrl        string   `protobuf:"bytes,6,opt,name=range_image_url,json=rangeImageUrl,proto3" json:"range_image_url,omitempty"`
	RangeStartPrice      float32  `protobuf:"fixed32,7,opt,name=range_start_price,json=rangeStartPrice,proto3" json:"range_start_price,omitempty"`
	RangeFee             float32  `protobuf:"fixed32,8,opt,name=range_fee,json=rangeFee,proto3" json:"range_fee,omitempty"`
	IsDeliveryTime       bool     `protobuf:"varint,9,opt,name=is_delivery_time,json=isDeliveryTime,proto3" json:"is_delivery_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeliveryInfo) Reset()         { *m = DeliveryInfo{} }
func (m *DeliveryInfo) String() string { return proto.CompactTextString(m) }
func (*DeliveryInfo) ProtoMessage()    {}
func (*DeliveryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_832505ff9d8a41db, []int{2}
}

func (m *DeliveryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliveryInfo.Unmarshal(m, b)
}
func (m *DeliveryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliveryInfo.Marshal(b, m, deterministic)
}
func (m *DeliveryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliveryInfo.Merge(m, src)
}
func (m *DeliveryInfo) XXX_Size() int {
	return xxx_messageInfo_DeliveryInfo.Size(m)
}
func (m *DeliveryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliveryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DeliveryInfo proto.InternalMessageInfo

func (m *DeliveryInfo) GetLocationId() int64 {
	if m != nil {
		return m.LocationId
	}
	return 0
}

func (m *DeliveryInfo) GetMethod() int32 {
	if m != nil {
		return m.Method
	}
	return 0
}

func (m *DeliveryInfo) GetTemplate() int32 {
	if m != nil {
		return m.Template
	}
	return 0
}

func (m *DeliveryInfo) GetRangeName() string {
	if m != nil {
		return m.RangeName
	}
	return ""
}

func (m *DeliveryInfo) GetRangeContent() string {
	if m != nil {
		return m.RangeContent
	}
	return ""
}

func (m *DeliveryInfo) GetRangeImageUrl() string {
	if m != nil {
		return m.RangeImageUrl
	}
	return ""
}

func (m *DeliveryInfo) GetRangeStartPrice() float32 {
	if m != nil {
		return m.RangeStartPrice
	}
	return 0
}

func (m *DeliveryInfo) GetRangeFee() float32 {
	if m != nil {
		return m.RangeFee
	}
	return 0
}

func (m *DeliveryInfo) GetIsDeliveryTime() bool {
	if m != nil {
		return m.IsDeliveryTime
	}
	return false
}

type ExpressInfo struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExpressInfo) Reset()         { *m = ExpressInfo{} }
func (m *ExpressInfo) String() string { return proto.CompactTextString(m) }
func (*ExpressInfo) ProtoMessage()    {}
func (*ExpressInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_832505ff9d8a41db, []int{3}
}

func (m *ExpressInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpressInfo.Unmarshal(m, b)
}
func (m *ExpressInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpressInfo.Marshal(b, m, deterministic)
}
func (m *ExpressInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpressInfo.Merge(m, src)
}
func (m *ExpressInfo) XXX_Size() int {
	return xxx_messageInfo_ExpressInfo.Size(m)
}
func (m *ExpressInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpressInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ExpressInfo proto.InternalMessageInfo

// 订单发货的请求数据
type ShipmentRequest struct {
	Method               string                   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Type                 string                   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	OrderId              int64                    `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	IsDelivery           bool                     `protobuf:"varint,4,opt,name=is_delivery,json=isDelivery,proto3" json:"is_delivery,omitempty"`
	ShipperId            int32                    `protobuf:"varint,5,opt,name=shipper_id,json=shipperId,proto3" json:"shipper_id,omitempty"`
	LogisticsNo          string                   `protobuf:"bytes,6,opt,name=logistics_no,json=logisticsNo,proto3" json:"logistics_no,omitempty"`
	LocationId           int64                    `protobuf:"varint,7,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	FetchAt              string                   `protobuf:"bytes,8,opt,name=fetch_at,json=fetchAt,proto3" json:"fetch_at,omitempty"`
	DeliveryAt           string                   `protobuf:"bytes,9,opt,name=delivery_at,json=deliveryAt,proto3" json:"delivery_at,omitempty"`
	Details              []*ShipmentRequestDetail `protobuf:"bytes,10,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ShipmentRequest) Reset()         { *m = ShipmentRequest{} }
func (m *ShipmentRequest) String() string { return proto.CompactTextString(m) }
func (*ShipmentRequest) ProtoMessage()    {}
func (*ShipmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_832505ff9d8a41db, []int{4}
}

func (m *ShipmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShipmentRequest.Unmarshal(m, b)
}
func (m *ShipmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShipmentRequest.Marshal(b, m, deterministic)
}
func (m *ShipmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShipmentRequest.Merge(m, src)
}
func (m *ShipmentRequest) XXX_Size() int {
	return xxx_messageInfo_ShipmentRequest.Size(m)
}
func (m *ShipmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShipmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShipmentRequest proto.InternalMessageInfo

func (m *ShipmentRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *ShipmentRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ShipmentRequest) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *ShipmentRequest) GetIsDelivery() bool {
	if m != nil {
		return m.IsDelivery
	}
	return false
}

func (m *ShipmentRequest) GetShipperId() int32 {
	if m != nil {
		return m.ShipperId
	}
	return 0
}

func (m *ShipmentRequest) GetLogisticsNo() string {
	if m != nil {
		return m.LogisticsNo
	}
	return ""
}

func (m *ShipmentRequest) GetLocationId() int64 {
	if m != nil {
		return m.LocationId
	}
	return 0
}

func (m *ShipmentRequest) GetFetchAt() string {
	if m != nil {
		return m.FetchAt
	}
	return ""
}

func (m *ShipmentRequest) GetDeliveryAt() string {
	if m != nil {
		return m.DeliveryAt
	}
	return ""
}

func (m *ShipmentRequest) GetDetails() []*ShipmentRequestDetail {
	if m != nil {
		return m.Details
	}
	return nil
}

type ShipmentRequestDetail struct {
	OrderDetailId        int64    `protobuf:"varint,1,opt,name=order_detail_id,json=orderDetailId,proto3" json:"order_detail_id,omitempty"`
	ItemId               int64    `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	SkuId                int64    `protobuf:"varint,3,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Num                  int32    `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShipmentRequestDetail) Reset()         { *m = ShipmentRequestDetail{} }
func (m *ShipmentRequestDetail) String() string { return proto.CompactTextString(m) }
func (*ShipmentRequestDetail) ProtoMessage()    {}
func (*ShipmentRequestDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_832505ff9d8a41db, []int{5}
}

func (m *ShipmentRequestDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShipmentRequestDetail.Unmarshal(m, b)
}
func (m *ShipmentRequestDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShipmentRequestDetail.Marshal(b, m, deterministic)
}
func (m *ShipmentRequestDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShipmentRequestDetail.Merge(m, src)
}
func (m *ShipmentRequestDetail) XXX_Size() int {
	return xxx_messageInfo_ShipmentRequestDetail.Size(m)
}
func (m *ShipmentRequestDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_ShipmentRequestDetail.DiscardUnknown(m)
}

var xxx_messageInfo_ShipmentRequestDetail proto.InternalMessageInfo

func (m *ShipmentRequestDetail) GetOrderDetailId() int64 {
	if m != nil {
		return m.OrderDetailId
	}
	return 0
}

func (m *ShipmentRequestDetail) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *ShipmentRequestDetail) GetSkuId() int64 {
	if m != nil {
		return m.SkuId
	}
	return 0
}

func (m *ShipmentRequestDetail) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func init() {
	proto.RegisterType((*OrderShipment)(nil), "geiqin.srv.ord.private.OrderShipment")
	proto.RegisterType((*FetchInfo)(nil), "geiqin.srv.ord.private.FetchInfo")
	proto.RegisterType((*DeliveryInfo)(nil), "geiqin.srv.ord.private.DeliveryInfo")
	proto.RegisterType((*ExpressInfo)(nil), "geiqin.srv.ord.private.ExpressInfo")
	proto.RegisterType((*ShipmentRequest)(nil), "geiqin.srv.ord.private.ShipmentRequest")
	proto.RegisterType((*ShipmentRequestDetail)(nil), "geiqin.srv.ord.private.ShipmentRequestDetail")
}

func init() {
	proto.RegisterFile("shipment.proto", fileDescriptor_832505ff9d8a41db)
}

var fileDescriptor_832505ff9d8a41db = []byte{
	// 847 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xcd, 0x8e, 0xdc, 0x44,
	0x10, 0xd6, 0x78, 0x7e, 0x5d, 0x9e, 0x99, 0x5d, 0x5a, 0x4a, 0x30, 0x0b, 0x08, 0x67, 0x82, 0x90,
	0x85, 0xc4, 0x1c, 0x16, 0x1e, 0x80, 0x55, 0xc2, 0x22, 0x4b, 0x28, 0xa0, 0x0e, 0x9c, 0xad, 0xde,
	0xe9, 0x9a, 0xd9, 0x56, 0xfc, 0x33, 0x71, 0xf7, 0xac, 0xc8, 0x91, 0x17, 0xe3, 0xc0, 0x9b, 0x70,
	0xe5, 0x29, 0x50, 0x55, 0xdb, 0x9e, 0x49, 0x76, 0x57, 0xca, 0xad, 0xeb, 0xeb, 0xaf, 0xcb, 0xdd,
	0x55, 0x5f, 0x7d, 0x86, 0xa5, 0xbd, 0x35, 0xfb, 0x12, 0x2b, 0xb7, 0xde, 0x37, 0xb5, 0xab, 0xc5,
	0xd3, 0x1d, 0x9a, 0xb7, 0xa6, 0x5a, 0xdb, 0xe6, 0x6e, 0x5d, 0x37, 0x7a, 0xbd, 0x6f, 0xcc, 0x9d,
	0x72, 0x78, 0xb1, 0x54, 0x0d, 0xaa, 0xac, 0xda, 0xd6, 0x9e, 0xb7, 0xfa, 0x6f, 0x04, 0x8b, 0x5f,
	0x1b, 0x8d, 0xcd, 0xeb, 0xf6, 0xbc, 0x38, 0x87, 0x61, 0x51, 0xed, 0xe2, 0x41, 0x32, 0x48, 0x43,
	0x49, 0x4b, 0x46, 0x94, 0x8b, 0x83, 0x16, 0x51, 0x4e, 0x7c, 0x06, 0x33, 0x63, 0xf3, 0x2d, 0xba,
	0xcd, 0x6d, 0x3c, 0x4c, 0x06, 0xe9, 0x4c, 0x4e, 0x8d, 0xbd, 0xa6, 0x50, 0x7c, 0x05, 0x91, 0xb1,
	0xb9, 0xc6, 0xc2, 0xdc, 0x61, 0xf3, 0x2e, 0x1e, 0xf1, 0x2e, 0x18, 0xfb, 0xb2, 0x45, 0xc4, 0x97,
	0x00, 0xc6, 0xe6, 0xf8, 0xe7, 0xbe, 0x41, 0x6b, 0xe3, 0x31, 0xef, 0x87, 0xc6, 0xfe, 0xe4, 0x01,
	0xf1, 0x14, 0x26, 0x25, 0xba, 0xdb, 0x5a, 0xc7, 0x13, 0xfe, 0x5e, 0x1b, 0x51, 0x5e, 0xfe, 0x5e,
	0xbe, 0xa9, 0x0f, 0x95, 0x8b, 0xa7, 0xc9, 0x20, 0x1d, 0x4b, 0x60, 0xe8, 0x05, 0x21, 0xe2, 0x5b,
	0xf8, 0xc4, 0x13, 0x8a, 0x7a, 0xa3, 0x9c, 0xa9, 0xab, 0xdc, 0xe8, 0x78, 0x96, 0x0c, 0xd2, 0xa1,
	0x3c, 0xe3, 0x8d, 0x5f, 0x5a, 0x3c, 0xd3, 0x74, 0x7f, 0xcf, 0x55, 0x2e, 0x0e, 0xf9, 0x33, 0x53,
	0x8e, 0xaf, 0x9c, 0x48, 0x20, 0x6a, 0x2f, 0xaf, 0x6e, 0x0a, 0x8c, 0x81, 0xef, 0x77, 0x0a, 0xd1,
	0x4d, 0xba, 0xe7, 0xd1, 0xf9, 0x88, 0xcf, 0x43, 0x07, 0x5d, 0x39, 0x22, 0xb4, 0xcf, 0xcb, 0xb7,
	0x88, 0xf1, 0x3c, 0x19, 0xa4, 0x81, 0x84, 0x16, 0xba, 0x46, 0x14, 0xcf, 0x60, 0xde, 0x67, 0x20,
	0xc6, 0x82, 0x19, 0x7d, 0x56, 0xa2, 0x64, 0xb0, 0xe8, 0x29, 0xa6, 0xda, 0xd6, 0xf1, 0x32, 0x19,
	0xa4, 0xd1, 0xe5, 0xd7, 0xeb, 0x87, 0xfb, 0xba, 0xee, 0xca, 0x4b, 0xad, 0x95, 0x7d, 0x76, 0x8a,
	0xc4, 0x8f, 0xe0, 0xcb, 0xe4, 0xf3, 0x9c, 0x71, 0x9e, 0x67, 0x8f, 0xe5, 0xe1, 0x26, 0x72, 0x92,
	0x70, 0xdb, 0x2d, 0xc5, 0x35, 0xcc, 0xbb, 0x07, 0x71, 0x8e, 0x73, 0xce, 0xf1, 0xfc, 0xb1, 0x1c,
	0x6d, 0x2b, 0x39, 0x4b, 0x57, 0x09, 0x0a, 0x56, 0x7f, 0x07, 0x10, 0xf6, 0x1f, 0x10, 0x4b, 0x08,
	0x8c, 0x66, 0x9d, 0x0d, 0x65, 0x60, 0xb4, 0x10, 0x30, 0xaa, 0x54, 0x89, 0xad, 0xce, 0x78, 0x2d,
	0x3e, 0x85, 0x29, 0x09, 0x96, 0x5a, 0x39, 0x64, 0xe2, 0x84, 0xf5, 0xcb, 0x64, 0xa5, 0x75, 0xc3,
	0xfa, 0x0a, 0x25, 0xaf, 0x3b, 0xe5, 0x8e, 0xef, 0x29, 0x77, 0x72, 0x54, 0xee, 0x39, 0x0c, 0x1d,
	0x16, 0x2c, 0x9f, 0x50, 0xd2, 0x92, 0x05, 0x57, 0xdf, 0x98, 0x02, 0x59, 0x2c, 0x24, 0x38, 0x8e,
	0xc4, 0x0a, 0x16, 0x9d, 0xc6, 0x73, 0x67, 0x4a, 0x64, 0xa1, 0xcc, 0x64, 0xd4, 0x0a, 0xfd, 0x77,
	0x53, 0xa2, 0xb8, 0x80, 0x99, 0x36, 0xd6, 0xa9, 0x6a, 0xe3, 0x95, 0x12, 0xc8, 0x3e, 0x16, 0x5f,
	0x40, 0xb8, 0x53, 0x45, 0x81, 0x8d, 0x41, 0x1b, 0x47, 0xc9, 0x30, 0x0d, 0xe5, 0x11, 0x10, 0x3f,
	0xc0, 0x88, 0x5e, 0xc2, 0xe2, 0x88, 0x2e, 0x93, 0xc7, 0x4a, 0x79, 0xd5, 0x4e, 0xab, 0x64, 0xf6,
	0xea, 0x9f, 0x00, 0xe6, 0xa7, 0x9d, 0x26, 0xa9, 0x9d, 0xca, 0xdd, 0x17, 0x13, 0x8a, 0xa3, 0xd2,
	0x8f, 0xe3, 0x14, 0xf0, 0xc4, 0x74, 0xe3, 0x74, 0x01, 0x33, 0x87, 0xe5, 0xbe, 0x50, 0x0e, 0xb9,
	0xb2, 0x63, 0xd9, 0xc7, 0x34, 0xa1, 0x8d, 0xaa, 0x76, 0x98, 0x73, 0x3b, 0x7c, 0x85, 0x43, 0x46,
	0x5e, 0x51, 0x4f, 0x9e, 0xc3, 0xc2, 0x6f, 0x6f, 0xea, 0xca, 0x61, 0xe5, 0xda, 0x82, 0xcf, 0x19,
	0x7c, 0xe1, 0x31, 0xf1, 0x0d, 0x9c, 0x79, 0x92, 0x29, 0xd5, 0x0e, 0xf3, 0x43, 0x53, 0xb4, 0x5d,
	0xf0, 0x67, 0x33, 0x42, 0xff, 0x68, 0x0a, 0x9a, 0x5a, 0xcf, 0xb3, 0x4e, 0x35, 0x2e, 0xdf, 0x37,
	0x66, 0x83, 0xdc, 0x9d, 0x40, 0xfa, 0x04, 0xaf, 0x09, 0xff, 0x8d, 0x60, 0xf1, 0x39, 0xf8, 0x5b,
	0xf0, 0xcc, 0xcc, 0x7c, 0xb9, 0x19, 0xa0, 0x81, 0x49, 0xe1, 0xfc, 0xc4, 0x77, 0x4e, 0x3b, 0xb6,
	0x3c, 0x9a, 0x0f, 0x35, 0x6d, 0xb5, 0x80, 0xe8, 0x44, 0xa1, 0xab, 0x7f, 0x03, 0x38, 0xeb, 0xcc,
	0x4f, 0xe2, 0xdb, 0x03, 0x5a, 0x77, 0x52, 0xb5, 0xc1, 0x7b, 0x26, 0x24, 0x60, 0xe4, 0xde, 0xed,
	0x7b, 0x89, 0xd2, 0x9a, 0xbc, 0xa4, 0x26, 0x03, 0x3d, 0x6a, 0x74, 0xca, 0x71, 0xa6, 0x3f, 0xca,
	0x0b, 0xc9, 0xb7, 0xf7, 0xfe, 0xf4, 0x98, 0xfb, 0x10, 0xb6, 0x48, 0xa6, 0xc9, 0x27, 0x8a, 0x7a,
	0x67, 0xac, 0x33, 0x1b, 0x9b, 0x57, 0x75, 0x5b, 0xc1, 0xa8, 0xc7, 0x5e, 0xdd, 0x13, 0xc0, 0xf4,
	0x9e, 0x00, 0x4e, 0xad, 0x6e, 0xf6, 0xbe, 0xd5, 0x7d, 0x60, 0x64, 0xe1, 0x3d, 0x23, 0xfb, 0x19,
	0xa6, 0x1a, 0x9d, 0x32, 0x85, 0x8d, 0x21, 0x19, 0xa6, 0xd1, 0xe5, 0x77, 0x8f, 0xe9, 0xf4, 0x83,
	0x02, 0xbe, 0xe4, 0x53, 0xb2, 0x3b, 0xbd, 0xfa, 0x6b, 0x00, 0x4f, 0x1e, 0xa4, 0x90, 0x4e, 0x7c,
	0xf5, 0x3c, 0xf5, 0x28, 0xe2, 0x05, 0xc3, 0x9e, 0x95, 0x69, 0x32, 0x02, 0xe3, 0xb0, 0xa4, 0xfd,
	0xc0, 0x1b, 0x01, 0x85, 0x99, 0x16, 0x4f, 0x60, 0x62, 0xdf, 0x1c, 0x8e, 0xc5, 0x1f, 0xdb, 0x37,
	0x87, 0x4c, 0xd3, 0x9c, 0x57, 0x87, 0x92, 0x4b, 0x3e, 0x96, 0xb4, 0xbc, 0x99, 0xf0, 0x0f, 0xef,
	0xfb, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0xfc, 0x67, 0x97, 0xaa, 0x2a, 0x07, 0x00, 0x00,
}
