// Code generated by protoc-gen-go. DO NOT EDIT.
// source: track.proto

package geiqin_srv_tms

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Track struct {
	Id                   int64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ShipperCode          string         `protobuf:"bytes,2,opt,name=shipper_code,json=shipperCode,proto3" json:"shipper_code,omitempty"`
	OrderCode            string         `protobuf:"bytes,3,opt,name=order_code,json=orderCode,proto3" json:"order_code,omitempty"`
	LogisticCode         string         `protobuf:"bytes,4,opt,name=logistic_code,json=logisticCode,proto3" json:"logistic_code,omitempty"`
	Success              bool           `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	Reason               string         `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	State                string         `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	StateEx              string         `protobuf:"bytes,8,opt,name=stateEx,proto3" json:"stateEx,omitempty"`
	Location             string         `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	Details              []*TrackDetail `protobuf:"bytes,10,rep,name=details,proto3" json:"details,omitempty"`
	CustomerName         string         `protobuf:"bytes,11,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Track) Reset()         { *m = Track{} }
func (m *Track) String() string { return proto.CompactTextString(m) }
func (*Track) ProtoMessage()    {}
func (*Track) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4b44cacdae97aca, []int{0}
}

func (m *Track) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Track.Unmarshal(m, b)
}
func (m *Track) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Track.Marshal(b, m, deterministic)
}
func (m *Track) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Track.Merge(m, src)
}
func (m *Track) XXX_Size() int {
	return xxx_messageInfo_Track.Size(m)
}
func (m *Track) XXX_DiscardUnknown() {
	xxx_messageInfo_Track.DiscardUnknown(m)
}

var xxx_messageInfo_Track proto.InternalMessageInfo

func (m *Track) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Track) GetShipperCode() string {
	if m != nil {
		return m.ShipperCode
	}
	return ""
}

func (m *Track) GetOrderCode() string {
	if m != nil {
		return m.OrderCode
	}
	return ""
}

func (m *Track) GetLogisticCode() string {
	if m != nil {
		return m.LogisticCode
	}
	return ""
}

func (m *Track) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Track) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Track) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Track) GetStateEx() string {
	if m != nil {
		return m.StateEx
	}
	return ""
}

func (m *Track) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Track) GetDetails() []*TrackDetail {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *Track) GetCustomerName() string {
	if m != nil {
		return m.CustomerName
	}
	return ""
}

type TrackDetail struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TrackId              int32    `protobuf:"varint,2,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	AcceptTime           string   `protobuf:"bytes,3,opt,name=accept_time,json=acceptTime,proto3" json:"accept_time,omitempty"`
	AcceptStation        string   `protobuf:"bytes,4,opt,name=accept_station,json=acceptStation,proto3" json:"accept_station,omitempty"`
	Location             string   `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Action               string   `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`
	Remark               string   `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackDetail) Reset()         { *m = TrackDetail{} }
func (m *TrackDetail) String() string { return proto.CompactTextString(m) }
func (*TrackDetail) ProtoMessage()    {}
func (*TrackDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4b44cacdae97aca, []int{1}
}

func (m *TrackDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackDetail.Unmarshal(m, b)
}
func (m *TrackDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackDetail.Marshal(b, m, deterministic)
}
func (m *TrackDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackDetail.Merge(m, src)
}
func (m *TrackDetail) XXX_Size() int {
	return xxx_messageInfo_TrackDetail.Size(m)
}
func (m *TrackDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackDetail.DiscardUnknown(m)
}

var xxx_messageInfo_TrackDetail proto.InternalMessageInfo

func (m *TrackDetail) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TrackDetail) GetTrackId() int32 {
	if m != nil {
		return m.TrackId
	}
	return 0
}

func (m *TrackDetail) GetAcceptTime() string {
	if m != nil {
		return m.AcceptTime
	}
	return ""
}

func (m *TrackDetail) GetAcceptStation() string {
	if m != nil {
		return m.AcceptStation
	}
	return ""
}

func (m *TrackDetail) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *TrackDetail) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *TrackDetail) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

type TrackResponse struct {
	Entity               *Track   `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Pager                *Pager   `protobuf:"bytes,2,opt,name=pager,proto3" json:"pager,omitempty"`
	Items                []*Track `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Error                *Error   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Info                 *Info    `protobuf:"bytes,5,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackResponse) Reset()         { *m = TrackResponse{} }
func (m *TrackResponse) String() string { return proto.CompactTextString(m) }
func (*TrackResponse) ProtoMessage()    {}
func (*TrackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4b44cacdae97aca, []int{2}
}

func (m *TrackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackResponse.Unmarshal(m, b)
}
func (m *TrackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackResponse.Marshal(b, m, deterministic)
}
func (m *TrackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackResponse.Merge(m, src)
}
func (m *TrackResponse) XXX_Size() int {
	return xxx_messageInfo_TrackResponse.Size(m)
}
func (m *TrackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TrackResponse proto.InternalMessageInfo

func (m *TrackResponse) GetEntity() *Track {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *TrackResponse) GetPager() *Pager {
	if m != nil {
		return m.Pager
	}
	return nil
}

func (m *TrackResponse) GetItems() []*Track {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *TrackResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *TrackResponse) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*Track)(nil), "geiqin.srv.tms.Track")
	proto.RegisterType((*TrackDetail)(nil), "geiqin.srv.tms.TrackDetail")
	proto.RegisterType((*TrackResponse)(nil), "geiqin.srv.tms.TrackResponse")
}

func init() {
	proto.RegisterFile("track.proto", fileDescriptor_f4b44cacdae97aca)
}

var fileDescriptor_f4b44cacdae97aca = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xcd, 0x6e, 0x13, 0x31,
	0x14, 0x85, 0x99, 0xa4, 0x93, 0x9f, 0x3b, 0x49, 0x16, 0x56, 0xa9, 0x4c, 0x50, 0x45, 0x08, 0x42,
	0x1a, 0x09, 0x31, 0x8b, 0x20, 0xd6, 0x2c, 0xa0, 0x8b, 0x6e, 0xf8, 0x71, 0xbb, 0x8f, 0x8c, 0xe7,
	0x36, 0x58, 0x8d, 0xc7, 0x83, 0xed, 0x54, 0xf4, 0x1d, 0x79, 0x00, 0xde, 0x82, 0x57, 0x40, 0x73,
	0x3d, 0x83, 0x68, 0x99, 0xee, 0xe6, 0x9c, 0xfb, 0xd9, 0xe3, 0x73, 0x2c, 0x43, 0x16, 0x9c, 0x54,
	0xd7, 0x45, 0xed, 0x6c, 0xb0, 0x6c, 0xb1, 0x43, 0xfd, 0x5d, 0x57, 0x85, 0x77, 0x37, 0x45, 0x30,
	0x7e, 0x39, 0x53, 0xd6, 0x18, 0x5b, 0xc5, 0xe9, 0xfa, 0xd7, 0x00, 0xd2, 0xcb, 0x86, 0x66, 0x0b,
	0x18, 0xe8, 0x92, 0x27, 0xab, 0x24, 0x1f, 0x8a, 0x81, 0x2e, 0xd9, 0x73, 0x98, 0xf9, 0x6f, 0xba,
	0xae, 0xd1, 0x6d, 0x95, 0x2d, 0x91, 0x0f, 0x56, 0x49, 0x3e, 0x15, 0x59, 0xeb, 0xbd, 0xb7, 0x25,
	0xb2, 0x53, 0x00, 0xeb, 0xca, 0x0e, 0x18, 0x12, 0x30, 0x25, 0x87, 0xc6, 0x2f, 0x60, 0xbe, 0xb7,
	0x3b, 0xed, 0x83, 0x56, 0x91, 0x38, 0x22, 0x62, 0xd6, 0x99, 0x04, 0x71, 0x18, 0xfb, 0x83, 0x52,
	0xe8, 0x3d, 0x4f, 0x57, 0x49, 0x3e, 0x11, 0x9d, 0x64, 0x27, 0x30, 0x72, 0x28, 0xbd, 0xad, 0xf8,
	0x88, 0xd6, 0xb5, 0x8a, 0x1d, 0x43, 0xea, 0x83, 0x0c, 0xc8, 0xc7, 0x64, 0x47, 0x41, 0xfb, 0x34,
	0x1f, 0x67, 0x3f, 0xf8, 0x84, 0xfc, 0x4e, 0xb2, 0x25, 0x4c, 0xf6, 0x56, 0xc9, 0xa0, 0x6d, 0xc5,
	0xa7, 0x34, 0xfa, 0xab, 0xd9, 0x5b, 0x18, 0x97, 0x18, 0xa4, 0xde, 0x7b, 0x0e, 0xab, 0x61, 0x9e,
	0x6d, 0x9e, 0x16, 0x77, 0xeb, 0x2a, 0xa8, 0x9c, 0x0f, 0xc4, 0x88, 0x8e, 0x6d, 0x92, 0xa9, 0x83,
	0x0f, 0xd6, 0xa0, 0xdb, 0x56, 0xd2, 0x20, 0xcf, 0x62, 0xb2, 0xce, 0xfc, 0x28, 0x0d, 0xae, 0x7f,
	0x26, 0x90, 0xfd, 0xb3, 0xfa, 0xbf, 0x82, 0x9f, 0xc0, 0x84, 0xee, 0x69, 0xab, 0x4b, 0x2a, 0x37,
	0x15, 0x63, 0xd2, 0xe7, 0x25, 0x7b, 0x06, 0x99, 0x54, 0x0a, 0xeb, 0xb0, 0x0d, 0xda, 0x74, 0xcd,
	0x42, 0xb4, 0x2e, 0xb5, 0x41, 0xf6, 0x12, 0x16, 0x2d, 0xd0, 0xa4, 0x6c, 0x92, 0xc5, 0x6e, 0xe7,
	0xd1, 0xbd, 0x88, 0xe6, 0x9d, 0xe8, 0xe9, 0xbd, 0xe8, 0x27, 0x30, 0x92, 0x8a, 0x26, 0x6d, 0xbd,
	0x51, 0xc5, 0xda, 0x8d, 0x74, 0xd7, 0x6d, 0xbf, 0xad, 0x5a, 0xff, 0x4e, 0x60, 0x4e, 0x71, 0x04,
	0xfa, 0xda, 0x56, 0x1e, 0xd9, 0x6b, 0x18, 0x61, 0x15, 0x74, 0xb8, 0xa5, 0x50, 0xd9, 0xe6, 0x71,
	0x6f, 0x77, 0xa2, 0x85, 0xd8, 0x2b, 0x48, 0x6b, 0xb9, 0x43, 0x47, 0x61, 0x7b, 0xe8, 0xcf, 0xcd,
	0x50, 0x44, 0xa6, 0x81, 0x75, 0x40, 0xe3, 0xf9, 0x90, 0xae, 0xe5, 0x81, 0xad, 0x23, 0xd3, 0xc0,
	0xe8, 0x9c, 0x75, 0x54, 0x42, 0x0f, 0x7c, 0xd6, 0x0c, 0x45, 0x64, 0x58, 0x0e, 0x47, 0xba, 0xba,
	0xb2, 0xd4, 0x47, 0xb6, 0x39, 0xbe, 0xcf, 0x9e, 0x57, 0x57, 0x56, 0x10, 0xb1, 0xf9, 0x04, 0x33,
	0xfa, 0xcd, 0x05, 0xba, 0x1b, 0xad, 0x90, 0xbd, 0x83, 0xf4, 0xcb, 0x01, 0xdd, 0x2d, 0xeb, 0x3f,
	0xcd, 0xf2, 0xb4, 0xff, 0x90, 0x6d, 0x5d, 0xeb, 0x47, 0x5f, 0x47, 0xf4, 0xe6, 0xde, 0xfc, 0x09,
	0x00, 0x00, 0xff, 0xff, 0x3f, 0xc4, 0x6d, 0xf8, 0xa0, 0x03, 0x00, 0x00,
}
