// Code generated by protoc-gen-go. DO NOT EDIT.
// source: buying.proto

package geiqin_srv_eat

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//购买清单
type Buying struct {
	Solution             string        `protobuf:"bytes,1,opt,name=solution,proto3" json:"solution,omitempty"`
	Count                int32         `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Total                float32       `protobuf:"fixed32,3,opt,name=total,proto3" json:"total,omitempty"`
	Discount             float32       `protobuf:"fixed32,4,opt,name=discount,proto3" json:"discount,omitempty"`
	Freight              float32       `protobuf:"fixed32,5,opt,name=freight,proto3" json:"freight,omitempty"`
	Amount               float32       `protobuf:"fixed32,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Point                int32         `protobuf:"varint,7,opt,name=point,proto3" json:"point,omitempty"`
	Items                []*BuyingItem `protobuf:"bytes,8,rep,name=items,proto3" json:"items,omitempty"`
	Changed              bool          `protobuf:"varint,9,opt,name=changed,proto3" json:"changed,omitempty"`
	Error                string        `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	Food                 *OrderFood    `protobuf:"bytes,11,opt,name=food,proto3" json:"food,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Buying) Reset()         { *m = Buying{} }
func (m *Buying) String() string { return proto.CompactTextString(m) }
func (*Buying) ProtoMessage()    {}
func (*Buying) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc0a9e5c6a9833d6, []int{0}
}

func (m *Buying) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Buying.Unmarshal(m, b)
}
func (m *Buying) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Buying.Marshal(b, m, deterministic)
}
func (m *Buying) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Buying.Merge(m, src)
}
func (m *Buying) XXX_Size() int {
	return xxx_messageInfo_Buying.Size(m)
}
func (m *Buying) XXX_DiscardUnknown() {
	xxx_messageInfo_Buying.DiscardUnknown(m)
}

var xxx_messageInfo_Buying proto.InternalMessageInfo

func (m *Buying) GetSolution() string {
	if m != nil {
		return m.Solution
	}
	return ""
}

func (m *Buying) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Buying) GetTotal() float32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Buying) GetDiscount() float32 {
	if m != nil {
		return m.Discount
	}
	return 0
}

func (m *Buying) GetFreight() float32 {
	if m != nil {
		return m.Freight
	}
	return 0
}

func (m *Buying) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Buying) GetPoint() int32 {
	if m != nil {
		return m.Point
	}
	return 0
}

func (m *Buying) GetItems() []*BuyingItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Buying) GetChanged() bool {
	if m != nil {
		return m.Changed
	}
	return false
}

func (m *Buying) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Buying) GetFood() *OrderFood {
	if m != nil {
		return m.Food
	}
	return nil
}

//购买清单明细
type BuyingItem struct {
	ItemId               int64    `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	SkuId                int64    `protobuf:"varint,2,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Num                  int32    `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	Price                float32  `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	OriginPrice          float32  `protobuf:"fixed32,5,opt,name=origin_price,json=originPrice,proto3" json:"origin_price,omitempty"`
	SubTotal             float32  `protobuf:"fixed32,6,opt,name=sub_total,json=subTotal,proto3" json:"sub_total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuyingItem) Reset()         { *m = BuyingItem{} }
func (m *BuyingItem) String() string { return proto.CompactTextString(m) }
func (*BuyingItem) ProtoMessage()    {}
func (*BuyingItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc0a9e5c6a9833d6, []int{1}
}

func (m *BuyingItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuyingItem.Unmarshal(m, b)
}
func (m *BuyingItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuyingItem.Marshal(b, m, deterministic)
}
func (m *BuyingItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyingItem.Merge(m, src)
}
func (m *BuyingItem) XXX_Size() int {
	return xxx_messageInfo_BuyingItem.Size(m)
}
func (m *BuyingItem) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyingItem.DiscardUnknown(m)
}

var xxx_messageInfo_BuyingItem proto.InternalMessageInfo

func (m *BuyingItem) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *BuyingItem) GetSkuId() int64 {
	if m != nil {
		return m.SkuId
	}
	return 0
}

func (m *BuyingItem) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *BuyingItem) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *BuyingItem) GetOriginPrice() float32 {
	if m != nil {
		return m.OriginPrice
	}
	return 0
}

func (m *BuyingItem) GetSubTotal() float32 {
	if m != nil {
		return m.SubTotal
	}
	return 0
}

type BuyingResponse struct {
	Entity               *Buying   `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Pager                *Pager    `protobuf:"bytes,2,opt,name=pager,proto3" json:"pager,omitempty"`
	Items                []*Buying `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Error                *Error    `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Info                 *Info     `protobuf:"bytes,5,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BuyingResponse) Reset()         { *m = BuyingResponse{} }
func (m *BuyingResponse) String() string { return proto.CompactTextString(m) }
func (*BuyingResponse) ProtoMessage()    {}
func (*BuyingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc0a9e5c6a9833d6, []int{2}
}

func (m *BuyingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuyingResponse.Unmarshal(m, b)
}
func (m *BuyingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuyingResponse.Marshal(b, m, deterministic)
}
func (m *BuyingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyingResponse.Merge(m, src)
}
func (m *BuyingResponse) XXX_Size() int {
	return xxx_messageInfo_BuyingResponse.Size(m)
}
func (m *BuyingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BuyingResponse proto.InternalMessageInfo

func (m *BuyingResponse) GetEntity() *Buying {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *BuyingResponse) GetPager() *Pager {
	if m != nil {
		return m.Pager
	}
	return nil
}

func (m *BuyingResponse) GetItems() []*Buying {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *BuyingResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *BuyingResponse) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*Buying)(nil), "geiqin.srv.eat.Buying")
	proto.RegisterType((*BuyingItem)(nil), "geiqin.srv.eat.BuyingItem")
	proto.RegisterType((*BuyingResponse)(nil), "geiqin.srv.eat.BuyingResponse")
}

func init() {
	proto.RegisterFile("buying.proto", fileDescriptor_fc0a9e5c6a9833d6)
}

var fileDescriptor_fc0a9e5c6a9833d6 = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xe1, 0x6e, 0xd3, 0x3c,
	0x14, 0xfd, 0xd2, 0x34, 0x69, 0x7b, 0xd3, 0x6f, 0x20, 0x6b, 0x1b, 0x26, 0x48, 0x28, 0xf4, 0x57,
	0xa4, 0x41, 0x84, 0xc2, 0x1b, 0x80, 0x86, 0xd4, 0x5f, 0x4c, 0x06, 0xf1, 0xb7, 0x4a, 0x13, 0x37,
	0xb3, 0xd6, 0xd8, 0xc5, 0x76, 0x26, 0xed, 0x7d, 0x78, 0x15, 0x5e, 0x88, 0x27, 0x40, 0xbe, 0x4e,
	0x86, 0xa8, 0xd6, 0x7f, 0x39, 0xf7, 0x1c, 0xdf, 0x73, 0xef, 0xb9, 0x0a, 0x2c, 0xb7, 0xfd, 0x83,
	0x90, 0x6d, 0x71, 0xd0, 0xca, 0x2a, 0x72, 0xd6, 0x72, 0xf1, 0x43, 0xc8, 0xc2, 0xe8, 0xfb, 0x82,
	0x57, 0x36, 0x5d, 0xd6, 0xaa, 0xeb, 0x94, 0xf4, 0x6c, 0xfa, 0x4c, 0xe9, 0x86, 0xeb, 0xcf, 0x4a,
	0x35, 0xbe, 0xb0, 0xfa, 0x35, 0x81, 0xf8, 0x23, 0xbe, 0x27, 0x29, 0xcc, 0x8d, 0xda, 0xf7, 0x56,
	0x28, 0x49, 0x83, 0x2c, 0xc8, 0x17, 0xec, 0x11, 0x93, 0x73, 0x88, 0x6a, 0xd5, 0x4b, 0x4b, 0x27,
	0x59, 0x90, 0x47, 0xcc, 0x03, 0x57, 0xb5, 0xca, 0x56, 0x7b, 0x1a, 0x66, 0x41, 0x3e, 0x61, 0x1e,
	0xb8, 0x3e, 0x8d, 0x30, 0x5e, 0x3e, 0x45, 0xe2, 0x11, 0x13, 0x0a, 0xb3, 0x9d, 0xe6, 0xa2, 0xbd,
	0xb5, 0x34, 0x42, 0x6a, 0x84, 0xe4, 0x12, 0xe2, 0xaa, 0xc3, 0x37, 0x31, 0x12, 0x03, 0x72, 0x1e,
	0x07, 0x25, 0xa4, 0xa5, 0x33, 0xef, 0x8c, 0x80, 0xbc, 0x87, 0x48, 0x58, 0xde, 0x19, 0x3a, 0xcf,
	0xc2, 0x3c, 0x29, 0xd3, 0xe2, 0xdf, 0xad, 0x0b, 0xbf, 0xd2, 0xda, 0xf2, 0x8e, 0x79, 0xa1, 0x73,
	0xae, 0x6f, 0x2b, 0xd9, 0xf2, 0x86, 0x2e, 0xb2, 0x20, 0x9f, 0xb3, 0x11, 0x3a, 0x07, 0xae, 0xb5,
	0xd2, 0x14, 0x70, 0x69, 0x0f, 0xc8, 0x3b, 0x98, 0xee, 0x94, 0x6a, 0x68, 0x92, 0x05, 0x79, 0x52,
	0xbe, 0x3c, 0x36, 0xf8, 0x32, 0xe6, 0xc8, 0x50, 0xb6, 0xfa, 0x19, 0x00, 0xfc, 0x35, 0x25, 0x2f,
	0x60, 0xe6, 0x6c, 0x37, 0xa2, 0xc1, 0x28, 0x43, 0x16, 0x3b, 0xb8, 0x6e, 0xc8, 0x05, 0xc4, 0xe6,
	0xae, 0x77, 0xf5, 0x09, 0xd6, 0x23, 0x73, 0xd7, 0xaf, 0x1b, 0xf2, 0x1c, 0x42, 0xd9, 0x77, 0x98,
	0x63, 0xc4, 0xdc, 0x27, 0xee, 0xad, 0x45, 0xcd, 0x87, 0x08, 0x3d, 0x20, 0x6f, 0x60, 0xa9, 0xb4,
	0x68, 0x85, 0xdc, 0x78, 0xd2, 0x87, 0x98, 0xf8, 0xda, 0x0d, 0x4a, 0x5e, 0xc1, 0xc2, 0xf4, 0xdb,
	0x8d, 0x3f, 0x8c, 0xcf, 0x72, 0x6e, 0xfa, 0xed, 0x37, 0x87, 0x57, 0xbf, 0x03, 0x38, 0xf3, 0x63,
	0x32, 0x6e, 0x0e, 0x4a, 0x1a, 0x4e, 0x0a, 0x88, 0xb9, 0xb4, 0xc2, 0x3e, 0xe0, 0xa4, 0x49, 0x79,
	0xf9, 0x74, 0x96, 0x6c, 0x50, 0x91, 0x2b, 0x88, 0x0e, 0x55, 0xcb, 0x35, 0x2e, 0x90, 0x94, 0x17,
	0xc7, 0xf2, 0x1b, 0x47, 0x32, 0xaf, 0x21, 0x6f, 0xc7, 0x3b, 0x85, 0x78, 0xa7, 0x53, 0xbd, 0x87,
	0x1b, 0x5d, 0x8d, 0x97, 0x98, 0x3e, 0xdd, 0xfa, 0xda, 0x91, 0xe3, 0x81, 0x72, 0x98, 0x0a, 0xb9,
	0x53, 0x18, 0x41, 0x52, 0x9e, 0x1f, 0x6b, 0xd7, 0x72, 0xa7, 0x18, 0x2a, 0xca, 0xef, 0xf0, 0xbf,
	0xf7, 0xf9, 0xca, 0xf5, 0xbd, 0x8b, 0xe8, 0x1a, 0x16, 0x9f, 0xaa, 0x7d, 0xdd, 0xef, 0x2b, 0xcb,
	0xc9, 0x89, 0x99, 0xd2, 0xd7, 0x27, 0x66, 0x1d, 0x72, 0x5b, 0xfd, 0xb7, 0x8d, 0xf1, 0x17, 0xfa,
	0xf0, 0x27, 0x00, 0x00, 0xff, 0xff, 0xf2, 0x64, 0xc2, 0xd8, 0x81, 0x03, 0x00, 0x00,
}
