// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: inConfig.proto

package geiqin_srv_eat

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for InConfigService service

type InConfigService interface {
	Get(ctx context.Context, in *InConfig, opts ...client.CallOption) (*InConfigResponse, error)
	Save(ctx context.Context, in *InConfig, opts ...client.CallOption) (*InConfigResponse, error)
}

type inConfigService struct {
	c    client.Client
	name string
}

func NewInConfigService(name string, c client.Client) InConfigService {
	return &inConfigService{
		c:    c,
		name: name,
	}
}

func (c *inConfigService) Get(ctx context.Context, in *InConfig, opts ...client.CallOption) (*InConfigResponse, error) {
	req := c.c.NewRequest(c.name, "InConfigService.Get", in)
	out := new(InConfigResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inConfigService) Save(ctx context.Context, in *InConfig, opts ...client.CallOption) (*InConfigResponse, error) {
	req := c.c.NewRequest(c.name, "InConfigService.Save", in)
	out := new(InConfigResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for InConfigService service

type InConfigServiceHandler interface {
	Get(context.Context, *InConfig, *InConfigResponse) error
	Save(context.Context, *InConfig, *InConfigResponse) error
}

func RegisterInConfigServiceHandler(s server.Server, hdlr InConfigServiceHandler, opts ...server.HandlerOption) error {
	type inConfigService interface {
		Get(ctx context.Context, in *InConfig, out *InConfigResponse) error
		Save(ctx context.Context, in *InConfig, out *InConfigResponse) error
	}
	type InConfigService struct {
		inConfigService
	}
	h := &inConfigServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&InConfigService{h}, opts...))
}

type inConfigServiceHandler struct {
	InConfigServiceHandler
}

func (h *inConfigServiceHandler) Get(ctx context.Context, in *InConfig, out *InConfigResponse) error {
	return h.InConfigServiceHandler.Get(ctx, in, out)
}

func (h *inConfigServiceHandler) Save(ctx context.Context, in *InConfig, out *InConfigResponse) error {
	return h.InConfigServiceHandler.Save(ctx, in, out)
}
